packages:
  - .
  - ui
  # - packages/*
  # - extensions/*

onlyBuiltDependencies:
  - "@deneb/core-rs"
  - "@lydell/node-pty"
  - "@napi-rs/canvas"
  - "@tloncorp/api"
  - authenticate-pam
  - esbuild
  - node-llama-cpp
  - protobufjs
  - sharp
