// Code generated by scripts/gen-proto-error-codes.sh; DO NOT EDIT.
// Source of truth: proto/gateway.proto
// Regenerate with: make proto-error-codes-gen

//! Gateway error codes — auto-generated from `proto/gateway.proto`.

/// Gateway RPC error codes.
///
/// Each variant maps to a stable string code used on the wire.
/// The i32 discriminant provides a compact representation for FFI.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum ErrorCode {
    // Legacy codes (backward compatible)
    NotLinked = 1,
    NotPaired = 2,
    AgentTimeout = 3,
    InvalidRequest = 4,
    Unavailable = 5,
    // INVALID_REQUEST refinements
    MissingParam = 10,
    NotFound = 11,
    Unauthorized = 12,
    ValidationFailed = 13,
    Conflict = 14,
    Forbidden = 15,
    // UNAVAILABLE refinements
    NodeDisconnected = 20,
    DependencyFailed = 21,
    FeatureDisabled = 22,
}

impl ErrorCode {
    /// Wire-format string code used on the wire.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::NotLinked => "NOT_LINKED",
            Self::NotPaired => "NOT_PAIRED",
            Self::AgentTimeout => "AGENT_TIMEOUT",
            Self::InvalidRequest => "INVALID_REQUEST",
            Self::Unavailable => "UNAVAILABLE",
            Self::MissingParam => "MISSING_PARAM",
            Self::NotFound => "NOT_FOUND",
            Self::Unauthorized => "UNAUTHORIZED",
            Self::ValidationFailed => "VALIDATION_FAILED",
            Self::Conflict => "CONFLICT",
            Self::Forbidden => "FORBIDDEN",
            Self::NodeDisconnected => "NODE_DISCONNECTED",
            Self::DependencyFailed => "DEPENDENCY_FAILED",
            Self::FeatureDisabled => "FEATURE_DISABLED",
        }
    }

    /// Parse a wire-format string into an `ErrorCode`.
    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "NOT_LINKED" => Some(Self::NotLinked),
            "NOT_PAIRED" => Some(Self::NotPaired),
            "AGENT_TIMEOUT" => Some(Self::AgentTimeout),
            "INVALID_REQUEST" => Some(Self::InvalidRequest),
            "UNAVAILABLE" => Some(Self::Unavailable),
            "MISSING_PARAM" => Some(Self::MissingParam),
            "NOT_FOUND" => Some(Self::NotFound),
            "UNAUTHORIZED" => Some(Self::Unauthorized),
            "VALIDATION_FAILED" => Some(Self::ValidationFailed),
            "CONFLICT" => Some(Self::Conflict),
            "FORBIDDEN" => Some(Self::Forbidden),
            "NODE_DISCONNECTED" => Some(Self::NodeDisconnected),
            "DEPENDENCY_FAILED" => Some(Self::DependencyFailed),
            "FEATURE_DISABLED" => Some(Self::FeatureDisabled),
            _ => None,
        }
    }

    /// Whether this code is retryable by default.
    pub fn is_retryable(&self) -> bool {
        matches!(
            self,
            Self::AgentTimeout
                | Self::Unavailable
                | Self::NodeDisconnected
                | Self::DependencyFailed
        )
    }
}

impl std::fmt::Display for ErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// All known error codes in declaration order.
pub const ALL_ERROR_CODES: &[ErrorCode] = &[
    ErrorCode::NotLinked,
    ErrorCode::NotPaired,
    ErrorCode::AgentTimeout,
    ErrorCode::InvalidRequest,
    ErrorCode::Unavailable,
    ErrorCode::MissingParam,
    ErrorCode::NotFound,
    ErrorCode::Unauthorized,
    ErrorCode::ValidationFailed,
    ErrorCode::Conflict,
    ErrorCode::Forbidden,
    ErrorCode::NodeDisconnected,
    ErrorCode::DependencyFailed,
    ErrorCode::FeatureDisabled,
];

/// Validate that an error code string is a known code.
pub fn is_valid_error_code(code: &str) -> bool {
    ErrorCode::parse(code).is_some()
}

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    use super::*;
    use crate::protocol::gen;

    #[test]
    fn test_roundtrip() {
        for code in ALL_ERROR_CODES {
            let s = code.as_str();
            let parsed = ErrorCode::parse(s).expect("known code should round-trip through parse");
            assert_eq!(*code, parsed);
        }
    }

    #[test]
    fn test_unknown_code() {
        assert!(ErrorCode::parse("UNKNOWN_CODE").is_none());
        assert!(!is_valid_error_code("BOGUS"));
    }

    #[test]
    fn test_retryable() {
        assert!(!ErrorCode::NotLinked.is_retryable());
        assert!(!ErrorCode::NotPaired.is_retryable());
        assert!(ErrorCode::AgentTimeout.is_retryable());
        assert!(!ErrorCode::InvalidRequest.is_retryable());
        assert!(ErrorCode::Unavailable.is_retryable());
        assert!(!ErrorCode::MissingParam.is_retryable());
        assert!(!ErrorCode::NotFound.is_retryable());
        assert!(!ErrorCode::Unauthorized.is_retryable());
        assert!(!ErrorCode::ValidationFailed.is_retryable());
        assert!(!ErrorCode::Conflict.is_retryable());
        assert!(!ErrorCode::Forbidden.is_retryable());
        assert!(ErrorCode::NodeDisconnected.is_retryable());
        assert!(ErrorCode::DependencyFailed.is_retryable());
        assert!(!ErrorCode::FeatureDisabled.is_retryable());
    }

    #[test]
    fn test_discriminants_unique() {
        let mut seen = std::collections::HashSet::new();
        for code in ALL_ERROR_CODES {
            assert!(
                seen.insert(*code as i32),
                "duplicate discriminant for {code}"
            );
        }
    }

    #[test]
    fn test_display() {
        assert_eq!(format!("{}", ErrorCode::NotFound), "NOT_FOUND");
    }

    #[test]
    fn test_generated_proto_error_code_mapping_consistency() {
        let mapping = [
            (ErrorCode::NotLinked, gen::gateway::ErrorCode::NotLinked),
            (ErrorCode::NotPaired, gen::gateway::ErrorCode::NotPaired),
            (
                ErrorCode::AgentTimeout,
                gen::gateway::ErrorCode::AgentTimeout,
            ),
            (
                ErrorCode::InvalidRequest,
                gen::gateway::ErrorCode::InvalidRequest,
            ),
            (ErrorCode::Unavailable, gen::gateway::ErrorCode::Unavailable),
            (
                ErrorCode::MissingParam,
                gen::gateway::ErrorCode::MissingParam,
            ),
            (ErrorCode::NotFound, gen::gateway::ErrorCode::NotFound),
            (
                ErrorCode::Unauthorized,
                gen::gateway::ErrorCode::Unauthorized,
            ),
            (
                ErrorCode::ValidationFailed,
                gen::gateway::ErrorCode::ValidationFailed,
            ),
            (ErrorCode::Conflict, gen::gateway::ErrorCode::Conflict),
            (ErrorCode::Forbidden, gen::gateway::ErrorCode::Forbidden),
            (
                ErrorCode::NodeDisconnected,
                gen::gateway::ErrorCode::NodeDisconnected,
            ),
            (
                ErrorCode::DependencyFailed,
                gen::gateway::ErrorCode::DependencyFailed,
            ),
            (
                ErrorCode::FeatureDisabled,
                gen::gateway::ErrorCode::FeatureDisabled,
            ),
        ];

        for (local, proto) in mapping {
            assert_eq!(local as i32, proto as i32, "numeric mapping mismatch");
            let local_name = format!("ERROR_CODE_{}", local.as_str());
            assert_eq!(local_name, proto.as_str_name(), "string mapping mismatch");
        }
    }
}
