// Code generated by scripts/gen-error-codes.sh; DO NOT EDIT.
// Source of truth: proto/gateway.proto
// Regenerate with: make error-codes-gen

//! Gateway error codes and FFI return codes — auto-generated from `proto/gateway.proto`.

/// Gateway RPC error codes.
///
/// Each variant maps to a stable string code used on the wire.
/// The i32 discriminant provides a compact representation for FFI.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum ErrorCode {
    // Legacy codes (backward compatible)
    NotLinked = 1,
    NotPaired = 2,
    AgentTimeout = 3,
    InvalidRequest = 4,
    Unavailable = 5,
    // `INVALID_REQUEST` refinements
    MissingParam = 10,
    NotFound = 11,
    Unauthorized = 12,
    ValidationFailed = 13,
    Conflict = 14,
    Forbidden = 15,
    // UNAVAILABLE refinements
    NodeDisconnected = 20,
    DependencyFailed = 21,
    FeatureDisabled = 22,
}

impl ErrorCode {
    /// Wire-format string code used on the wire.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::NotLinked => "NOT_LINKED",
            Self::NotPaired => "NOT_PAIRED",
            Self::AgentTimeout => "AGENT_TIMEOUT",
            Self::InvalidRequest => "INVALID_REQUEST",
            Self::Unavailable => "UNAVAILABLE",
            Self::MissingParam => "MISSING_PARAM",
            Self::NotFound => "NOT_FOUND",
            Self::Unauthorized => "UNAUTHORIZED",
            Self::ValidationFailed => "VALIDATION_FAILED",
            Self::Conflict => "CONFLICT",
            Self::Forbidden => "FORBIDDEN",
            Self::NodeDisconnected => "NODE_DISCONNECTED",
            Self::DependencyFailed => "DEPENDENCY_FAILED",
            Self::FeatureDisabled => "FEATURE_DISABLED",
        }
    }

    /// Parse a wire-format string into an `ErrorCode`.
    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "NOT_LINKED" => Some(Self::NotLinked),
            "NOT_PAIRED" => Some(Self::NotPaired),
            "AGENT_TIMEOUT" => Some(Self::AgentTimeout),
            "INVALID_REQUEST" => Some(Self::InvalidRequest),
            "UNAVAILABLE" => Some(Self::Unavailable),
            "MISSING_PARAM" => Some(Self::MissingParam),
            "NOT_FOUND" => Some(Self::NotFound),
            "UNAUTHORIZED" => Some(Self::Unauthorized),
            "VALIDATION_FAILED" => Some(Self::ValidationFailed),
            "CONFLICT" => Some(Self::Conflict),
            "FORBIDDEN" => Some(Self::Forbidden),
            "NODE_DISCONNECTED" => Some(Self::NodeDisconnected),
            "DEPENDENCY_FAILED" => Some(Self::DependencyFailed),
            "FEATURE_DISABLED" => Some(Self::FeatureDisabled),
            _ => None,
        }
    }

    /// Whether this code is retryable by default.
    pub fn is_retryable(&self) -> bool {
        matches!(
            self,
            Self::AgentTimeout
                | Self::Unavailable
                | Self::NodeDisconnected
                | Self::DependencyFailed
        )
    }
}

impl std::fmt::Display for ErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// All known error codes in declaration order.
pub const ALL_ERROR_CODES: &[ErrorCode] = &[
    ErrorCode::NotLinked,
    ErrorCode::NotPaired,
    ErrorCode::AgentTimeout,
    ErrorCode::InvalidRequest,
    ErrorCode::Unavailable,
    ErrorCode::MissingParam,
    ErrorCode::NotFound,
    ErrorCode::Unauthorized,
    ErrorCode::ValidationFailed,
    ErrorCode::Conflict,
    ErrorCode::Forbidden,
    ErrorCode::NodeDisconnected,
    ErrorCode::DependencyFailed,
    ErrorCode::FeatureDisabled,
];

/// Validate that an error code string is a known code.
pub fn is_valid_error_code(code: &str) -> bool {
    ErrorCode::parse(code).is_some()
}

// ---------------------------------------------------------------------------
// FFI error codes — negated from proto FfiErrorCode enum values.
// Negative i32 values returned by extern "C" functions.
// Positive return values from buffer-writing functions are bytes written.
// ---------------------------------------------------------------------------

pub(crate) const FFI_ERR_NULL_POINTER: i32 = -1;
pub(crate) const FFI_ERR_INVALID_UTF8: i32 = -2;
pub(crate) const FFI_ERR_OUTPUT_TOO_SMALL: i32 = -3;
pub(crate) const FFI_ERR_INPUT_TOO_LARGE: i32 = -4;
pub(crate) const FFI_ERR_JSON_ERROR: i32 = -5;
pub(crate) const FFI_ERR_OVERFLOW: i32 = -6;
pub(crate) const FFI_ERR_VALIDATION: i32 = -7;
pub(crate) const FFI_ERR_RUST_PANIC: i32 = -99;
