// Code generated by tool-schema-gen. DO NOT EDIT.
// Source: gateway-go/internal/pipeline/chat/toolreg/tool_schemas.json
// Regenerate: make tool-schemas

package toolreg

func readToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"file_path": map[string]any{
				"type":        "string",
				"description": "The absolute path to the file to read",
			},
			"force": map[string]any{
				"type":        "boolean",
				"description": "Force re-read even if cached (default: false)",
				"default":     false,
			},
			"function": map[string]any{
				"type":        "string",
				"description": "Read only this function/method/type. For .go files uses AST; for others uses regex. Overrides offset/limit",
			},
			"hashes": map[string]any{
				"type":        "boolean",
				"description": "Prefix each line with a short content-hash anchor (columns: line<TAB>anchor<TAB>content). Pass an anchor to edit's anchor= to replace that line without reproducing it as old_string (saves output tokens). Default: false",
				"default":     false,
			},
			"limit": map[string]any{
				"type":        "number",
				"description": "The number of lines to read (default: 2000)",
				"default":     2000,
				"minimum":     1,
			},
			"offset": map[string]any{
				"type":        "number",
				"description": "The line number to start reading from (1-based)",
				"minimum":     1,
			},
		},
		"required": []string{"file_path"},
	}
}

func readSpilloverToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"spill_id": map[string]any{
				"type":        "string",
				"description": "The spillover reference ID (e.g., sp_abc123) from a previous large tool result",
			},
		},
		"required": []string{"spill_id"},
	}
}

func writeToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"content": map[string]any{
				"type":        "string",
				"description": "The content to write to the file",
			},
			"file_path": map[string]any{
				"type":        "string",
				"description": "The absolute path to the file to write",
			},
		},
		"required": []string{"file_path", "content"},
	}
}

func editToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"anchor": map[string]any{
				"type":        "string",
				"description": "Content-hash anchor from read(hashes=true) identifying the line to replace. Replaces the whole anchored line with new_string — no old_string needed. Errors if the anchor matches zero or multiple (identical) lines",
			},
			"anchor_end": map[string]any{
				"type":        "string",
				"description": "Optional second anchor. With anchor set, replaces the inclusive line range anchor..anchor_end with new_string (which may span multiple lines)",
			},
			"file_path": map[string]any{
				"type":        "string",
				"description": "The absolute path to the file to modify",
			},
			"line": map[string]any{
				"type":        "number",
				"description": "Replace at a specific line number (1-based). When set, old_string matches only on this line",
				"minimum":     1,
			},
			"new_string": map[string]any{
				"type":        "string",
				"description": "The text to replace it with. When regex=true, supports $1/$2 backreferences",
			},
			"old_string": map[string]any{
				"type":        "string",
				"description": "The text to replace (must be unique unless replace_all is true). When regex=true, treated as a regex pattern",
			},
			"regex": map[string]any{
				"type":        "boolean",
				"description": "Treat old_string as a regex pattern (default: false)",
				"default":     false,
			},
			"replace_all": map[string]any{
				"type":        "boolean",
				"description": "Replace all occurrences instead of requiring a unique match (default: false)",
				"default":     false,
			},
		},
		"required": []string{"file_path", "new_string"},
	}
}

func grepToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"after": map[string]any{
				"type":        "number",
				"description": "Lines of context after each match (overrides contextLines for after)",
				"minimum":     0,
				"maximum":     10,
			},
			"before": map[string]any{
				"type":        "number",
				"description": "Lines of context before each match (overrides contextLines for before)",
				"minimum":     0,
				"maximum":     10,
			},
			"contextLines": map[string]any{
				"type":        "number",
				"description": "Lines of context around each match (0-10)",
				"default":     0,
				"minimum":     0,
				"maximum":     10,
			},
			"fileType": map[string]any{
				"type":        "string",
				"description": "File type filter for ripgrep --type (e.g. \"go\", \"py\", \"js\")",
			},
			"ignoreCase": map[string]any{
				"type":        "boolean",
				"description": "Case-insensitive search",
				"default":     false,
			},
			"include": map[string]any{
				"type":        "string",
				"description": "Glob pattern to filter files (e.g. \"*.ts\")",
			},
			"maxResults": map[string]any{
				"type":        "number",
				"description": "Maximum matches to return",
				"default":     100,
				"minimum":     1,
				"maximum":     500,
			},
			"mode": map[string]any{
				"type":        "string",
				"description": "Output mode: content (default, matching lines), files_only (file paths only), count (match counts per file)",
				"enum":        []string{"content", "files_only", "count"},
			},
			"multiline": map[string]any{
				"type":        "boolean",
				"description": "Enable multiline matching (patterns can span lines, . matches newlines)",
				"default":     false,
			},
			"path": map[string]any{
				"type":        "string",
				"description": "File or directory to search in",
			},
			"pattern": map[string]any{
				"type":        "string",
				"description": "Regular expression pattern to search for",
			},
		},
		"required": []string{"pattern"},
	}
}

func execToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"background": map[string]any{
				"type":        "boolean",
				"description": "Run in background immediately, then use process tool to check output",
				"default":     false,
			},
			"command": map[string]any{
				"type":        "string",
				"description": "Shell command to execute",
			},
			"env": map[string]any{
				"type":        "object",
				"description": "Environment variables to set for this command (key-value pairs). Blocked keys (API keys, secrets) are filtered.",
				"additionalProperties": map[string]any{
					"type": "string",
				},
			},
			"structured": map[string]any{
				"type":        "boolean",
				"description": "Return JSON with stdout, stderr, exit_code, runtime_ms instead of plain text",
				"default":     false,
			},
			"timeout": map[string]any{
				"type":        "number",
				"description": "Timeout in seconds (default: 60, max: 600)",
				"default":     60,
				"minimum":     1,
				"maximum":     600,
			},
			"workdir": map[string]any{
				"type":        "string",
				"description": "Working directory (defaults to workspace root)",
			},
		},
		"required": []string{"command"},
	}
}

func processToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Process action",
				"enum":        []string{"list", "poll", "log", "write", "kill"},
			},
			"input": map[string]any{
				"type":        "string",
				"description": "Data to write to process stdin (required for write action)",
			},
			"sessionId": map[string]any{
				"type":        "string",
				"description": "Session ID for actions other than list",
			},
			"timeout": map[string]any{
				"type":        "number",
				"description": "Poll timeout in milliseconds",
			},
		},
		"required": []string{"action"},
	}
}

func webToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"count": map[string]any{
				"type":        "number",
				"description": "Number of search results per query (default: 5)",
			},
			"fetch": map[string]any{
				"type":        "number",
				"description": "Auto-fetch top N results per query (1-3, default: 0)",
			},
			"maxChars": map[string]any{
				"type":        "number",
				"description": "Maximum content characters total (default: 50000)",
			},
			"queries": map[string]any{
				"type":        "array",
				"description": "Multiple parallel search queries (max 5)",
				"items": map[string]any{
					"type": "string",
				},
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Web search query. Serper (Google) > Brave > DuckDuckGo fallback",
			},
			"type": map[string]any{
				"type":        "string",
				"description": "Serper search type: news (Google News), scholar (Google Scholar), autocomplete (search suggestions). Default: regular web search.",
				"enum":        []string{"news", "scholar", "autocomplete"},
			},
			"url": map[string]any{
				"type":        "string",
				"description": "URL to fetch (HTML extraction + bot evasion)",
			},
		},
	}
}

func cronToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Cron action",
				"enum":        []string{"status", "list", "add", "update", "remove", "run", "get", "runs", "wake"},
			},
			"anchorTime": map[string]any{
				"type":        "string",
				"description": "Anchor time for interval schedules (ISO 8601). Intervals count from this time instead of registration time",
			},
			"command": map[string]any{
				"type":        "string",
				"description": "Agent message/command to execute on schedule (required for add)",
			},
			"deliveryMode": map[string]any{
				"type":        "string",
				"description": "How to deliver output: announce (send to the user, default) or none (run silently)",
				"enum":        []string{"announce", "none"},
			},
			"enabled": map[string]any{
				"type":        "boolean",
				"description": "Enable or disable a job (for add/update)",
			},
			"job": map[string]any{
				"type":                 "object",
				"description":          "Job definition object (alternative to top-level name/schedule/command)",
				"additionalProperties": true,
			},
			"jobId": map[string]any{
				"type":        "string",
				"description": "Job ID for get/update/remove/run/runs actions",
			},
			"limit": map[string]any{
				"type":        "integer",
				"description": "Max entries to return (for runs action, default 10)",
			},
			"name": map[string]any{
				"type":        "string",
				"description": "Job name (required for add, used as job ID)",
			},
			"retryBackoffMs": map[string]any{
				"type":        "integer",
				"description": "Initial backoff delay between retries in ms (default 5000). Doubles each retry, capped at 60s",
			},
			"retryCount": map[string]any{
				"type":        "integer",
				"description": "Number of retry attempts on failure (0-3, default 0 = no retry)",
			},
			"schedule": map[string]any{
				"type":        "string",
				"description": "Schedule specification. Formats: cron (0 9 * * *), interval (1h, 30m, every 5m), timestamp (2026-04-06T08:00:00), shorthand (@daily, @hourly, @weekly)",
			},
			"staggerMs": map[string]any{
				"type":        "integer",
				"description": "Random delay window in ms to distribute cron jobs (cron kind only, default: auto for top-of-hour)",
			},
			"text": map[string]any{
				"type":        "string",
				"description": "System event text for wake action",
			},
			"thinking": map[string]any{
				"type":        "string",
				"description": "Per-job thinking level for the agent turn. \"off\" disables the thinking phase (use for routine, well-templated jobs - much faster on the dual-mode main model). Levels minimal/low/medium/high set a budget; \"default\" clears the override.",
				"enum":        []string{"off", "minimal", "low", "medium", "high", "default"},
			},
			"tz": map[string]any{
				"type":        "string",
				"description": "Timezone for cron schedules (e.g. Asia/Seoul, UTC). Defaults to system local timezone",
			},
		},
		"required": []string{"action"},
	}
}

func morningLetterToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
	}
}

func messageToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Message action",
				"enum":        []string{"send", "react", "reply", "thread-reply"},
			},
			"channel": map[string]any{
				"type":        "string",
				"description": "Target channel (e.g., client)",
			},
			"emoji": map[string]any{
				"type":        "string",
				"description": "Emoji for react action",
			},
			"message": map[string]any{
				"type":        "string",
				"description": "Text content to send",
			},
			"messageId": map[string]any{
				"type":        "string",
				"description": "Message ID for react/reply actions",
			},
			"replyTo": map[string]any{
				"type":        "string",
				"description": "Message ID to reply to",
			},
			"silent": map[string]any{
				"type":        "boolean",
				"description": "Send without notification sound",
			},
			"to": map[string]any{
				"type":        "string",
				"description": "Recipient (chat ID or user identifier)",
			},
		},
		"required": []string{"action"},
	}
}

func gatewayToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Gateway action. config_get/config_set: read or write a single dotted path. config.get: full config snapshot. config.apply: replace the whole config. config.patch: merge a patch object. config.schema.lookup: schema for a path. Destructive actions (restart/update/config_set/config.apply/config.patch) require approval: the first call returns a needs_approval envelope; after the user confirms, call the .confirmed variant with the same action_token.",
				"enum":        []string{"status", "config_get", "config_set", "config_set.confirmed", "update", "update.confirmed", "restart", "restart.confirmed", "config.get", "config.schema.lookup", "config.apply", "config.patch"},
			},
			"action_token": map[string]any{
				"type":        "string",
				"description": "Token returned by a prior approval envelope; required when calling a .confirmed variant.",
			},
			"path": map[string]any{
				"type":        "string",
				"description": "Dotted config path for config_get / config_set (e.g. \"model.main\"). Also used for config.schema.lookup.",
			},
			"raw": map[string]any{
				"type":        "string",
				"description": "Raw config JSON for apply/patch",
			},
			"reason": map[string]any{
				"type":        "string",
				"description": "Reason for restart or update",
			},
			"value": map[string]any{
				"description": "Leaf value to write (config_set only). Must be a scalar, array, or null — object replacement is rejected.",
			},
		},
		"required": []string{"action"},
	}
}

func sessionsToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Session action",
				"enum":        []string{"list", "history", "search", "send"},
			},
			"kinds": map[string]any{
				"type":        "array",
				"description": "Filter by session kind (list action)",
				"items": map[string]any{
					"type": "string",
					"enum": []string{"main", "group", "cron", "hook"},
				},
			},
			"limit": map[string]any{
				"type":        "number",
				"description": "Max sessions (list) or messages (history, default 20) to return",
				"default":     20,
				"minimum":     1,
			},
			"maxResults": map[string]any{
				"type":        "number",
				"description": "Max search results (search action, default 20)",
				"default":     20,
				"minimum":     1,
				"maximum":     100,
			},
			"message": map[string]any{
				"type":        "string",
				"description": "Message to send (send action)",
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Search keyword (search action)",
			},
			"sessionKey": map[string]any{
				"type":        "string",
				"description": "Target session key (history/send actions)",
			},
		},
		"required": []string{"action"},
	}
}

func sessionsSpawnToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"label": map[string]any{
				"type":        "string",
				"description": "Human-readable label",
			},
			"model": map[string]any{
				"type":        "string",
				"description": "Model role to use (default: main; implementer uses coding automatically when configured)",
				"enum":        []string{"main", "coding", "lightweight", "fallback"},
			},
			"task": map[string]any{
				"type":        "string",
				"description": "Task description for the sub-agent",
			},
			"tool_preset": map[string]any{
				"type":        "string",
				"description": "Tool preset restricting which tools the sub-agent can use. researcher=context gathering (read/grep/web/mail_archive/wiki/knowledge/polaris/contacts/graphify; no shell, no file writes, no Gmail OAuth surface), implementer=researcher+write/edit/exec/process, verifier=read/grep/exec/process only (build/test validation). Omit for the full toolset",
				"enum":        []string{"researcher", "implementer", "verifier"},
			},
		},
		"required": []string{"task"},
	}
}

func subagentsToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Sub-agent management action. 'result' returns a finished sub-agent's output (pull a result on demand, complementing the automatic completion notification).",
				"enum":        []string{"list", "result", "kill", "steer"},
			},
			"message": map[string]any{
				"type":        "string",
				"description": "Steering message for steer action",
			},
			"target": map[string]any{
				"type":        "string",
				"description": "Target sub-agent index, label, or session key (for result/kill/steer). Optional when exactly one sub-agent exists.",
			},
		},
	}
}

func sendFileToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"caption": map[string]any{
				"type":        "string",
				"description": "Caption text (optional)",
			},
			"file_path": map[string]any{
				"type":        "string",
				"description": "Path to the file to send",
			},
			"silent": map[string]any{
				"type":        "boolean",
				"description": "Send without notification sound",
			},
			"type": map[string]any{
				"type":        "string",
				"description": "Media type. Auto-detected from MIME if omitted",
				"enum":        []string{"photo", "document", "video", "audio", "voice"},
			},
		},
		"required": []string{"file_path"},
	}
}

func chartToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"chart_type": map[string]any{
				"type":        "string",
				"description": "데이터 성격에 맞게 고른다 — 시간에 따른 추이=line, 점층 누적/면적 강조=area, 항목 간 비교=bar, 전체 대비 구성비(부분의 합=전체)=doughnut. 막대+추세선 콤보는 bar로 두고 한 시리즈에 type:line을 지정.",
				"enum":        []string{"line", "area", "bar", "doughnut"},
			},
			"labels": map[string]any{
				"type":        "array",
				"description": "x축 항목(line/area/bar) 또는 도넛 조각 이름. 순서대로 series의 data와 1:1 대응.",
				"items": map[string]any{
					"type": "string",
				},
			},
			"series": map[string]any{
				"type":        "array",
				"description": "데이터 시리즈 목록. line/area/bar는 여러 시리즈 가능(겹쳐 그림), doughnut은 첫 시리즈만 사용.",
				"items": map[string]any{
					"type":     "object",
					"required": []string{"data"},
					"properties": map[string]any{
						"data": map[string]any{
							"type":        "array",
							"description": "labels와 같은 길이의 숫자 배열.",
							"items": map[string]any{
								"type": "number",
							},
						},
						"name": map[string]any{
							"type":        "string",
							"description": "시리즈 이름 (범례에 표시). 시리즈가 1개면 생략 가능.",
						},
						"type": map[string]any{
							"type":        "string",
							"description": "이 시리즈만 다른 모양으로 그릴 때 (콤보 차트). bar 차트 위에 추세선을 얹으려면 line.",
							"enum":        []string{"line", "bar"},
						},
					},
				},
			},
			"subtitle": map[string]any{
				"type":        "string",
				"description": "제목 아래 보조 설명 한 줄 (선택, 예: '2026년 상반기 · 단위 건')",
			},
			"title": map[string]any{
				"type":        "string",
				"description": "차트 상단 제목 (예: '월별 발주 추이')",
			},
			"y_unit": map[string]any{
				"type":        "string",
				"description": "y축 값의 단위 (선택, 예: '건', '만원', '%'). line/area/bar에만 적용.",
			},
		},
		"required": []string{"chart_type", "labels", "series"},
	}
}

func diagramToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"diagram_type": map[string]any{
				"type":        "string",
				"description": "flowchart=절차·흐름·관계·상태도(노드+화살표), gantt=일정(작업별 기간 막대), timeline=연혁·이력·로드맵(시점별 사건). 숫자 비교/추이는 diagram이 아니라 chart를 써라.",
				"enum":        []string{"flowchart", "gantt", "timeline"},
			},
			"direction": map[string]any{
				"type":        "string",
				"description": "flowchart 방향. TD=위→아래, LR=왼쪽→오른쪽 (기본 TD).",
				"enum":        []string{"TD", "LR", "BT", "RL"},
			},
			"edges": map[string]any{
				"type":        "array",
				"description": "flowchart 화살표 목록. from 노드 → to 노드.",
				"items": map[string]any{
					"type":     "object",
					"required": []string{"from", "to"},
					"properties": map[string]any{
						"from": map[string]any{
							"type":        "string",
							"description": "출발 노드 id.",
						},
						"label": map[string]any{
							"type":        "string",
							"description": "화살표에 붙일 조건/설명 (선택, 예: '승인', '반려').",
						},
						"to": map[string]any{
							"type":        "string",
							"description": "도착 노드 id.",
						},
					},
				},
			},
			"events": map[string]any{
				"type":        "array",
				"description": "timeline 사건 목록. 각 항목은 한 시점(period)과 그때 일어난 일들(items).",
				"items": map[string]any{
					"type":     "object",
					"required": []string{"period"},
					"properties": map[string]any{
						"items": map[string]any{
							"type":        "array",
							"description": "그 시점의 사건들 (하나 이상).",
							"items": map[string]any{
								"type": "string",
							},
						},
						"period": map[string]any{
							"type":        "string",
							"description": "시점 라벨 (예: '2021', '1분기', '2026-03').",
						},
						"section": map[string]any{
							"type":        "string",
							"description": "시점을 묶는 시대/구간 이름 (선택, 예: '창업기', '성장기').",
						},
					},
				},
			},
			"nodes": map[string]any{
				"type":        "array",
				"description": "flowchart 노드 목록. 각 노드는 고유 id로 edges에서 참조된다.",
				"items": map[string]any{
					"type":     "object",
					"required": []string{"id"},
					"properties": map[string]any{
						"id": map[string]any{
							"type":        "string",
							"description": "노드 고유 식별자 (edges의 from/to가 이 값을 참조). 예: 'apply'.",
						},
						"label": map[string]any{
							"type":        "string",
							"description": "노드에 표시할 텍스트. 생략하면 id를 표시.",
						},
						"shape": map[string]any{
							"type":        "string",
							"description": "노드 모양. 의사결정/분기는 diamond, 시작/끝은 stadium, 일반 단계는 rect.",
							"enum":        []string{"rect", "round", "stadium", "diamond", "circle"},
						},
					},
				},
			},
			"subtitle": map[string]any{
				"type":        "string",
				"description": "제목 아래 보조 설명 한 줄 (선택)",
			},
			"tasks": map[string]any{
				"type":        "array",
				"description": "gantt 작업 목록. 각 작업은 기간 막대 하나가 된다.",
				"items": map[string]any{
					"type":     "object",
					"required": []string{"name", "start"},
					"properties": map[string]any{
						"duration": map[string]any{
							"type":        "string",
							"description": "기간 (end 대신 택일, 예: '5d', '2w').",
						},
						"end": map[string]any{
							"type":        "string",
							"description": "종료일 YYYY-MM-DD (duration 대신 택일).",
						},
						"name": map[string]any{
							"type":        "string",
							"description": "작업 이름.",
						},
						"section": map[string]any{
							"type":        "string",
							"description": "작업을 묶는 구간 이름 (선택, 예: '준비', '시공'). 같은 section끼리 그룹으로 표시.",
						},
						"start": map[string]any{
							"type":        "string",
							"description": "시작일 YYYY-MM-DD.",
						},
						"status": map[string]any{
							"type":        "string",
							"description": "작업 상태 (선택). done=완료(회색), active=진행중(파랑), crit=중요/지연위험(빨강).",
							"enum":        []string{"done", "active", "crit"},
						},
					},
				},
			},
			"title": map[string]any{
				"type":        "string",
				"description": "다이어그램 상단 제목 (예: '인허가 처리 절차')",
			},
		},
		"required": []string{"diagram_type"},
	}
}

func gmailToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Gmail OAuth2 fallback/account action. Use mail_archive first for received-mail lookup, project history, and archive-backed analysis prep; use this only for send/reply/label/OAuth or Gmail-only fallback.",
				"enum":        []string{"inbox", "search", "read", "thread", "attachment", "send", "reply", "label", "analyze"},
			},
			"attachment": map[string]any{
				"type":        "string",
				"description": "Attachment selector for the attachment action: a filename (or substring) or 1-based index. Omit to list all attachments of the message. PDFs are extracted to text (OCR fallback for scans). Office docs are extracted via stdlib OOXML readers: Excel (.xlsx), Word (.docx), PowerPoint (.pptx). Image attachments go through OCR. Text files returned directly.",
			},
			"bcc": map[string]any{
				"type":        "string",
				"description": "BCC recipient(s), comma-separated",
			},
			"body": map[string]any{
				"type":        "string",
				"description": "Email body text (plain text or HTML if html=true)",
			},
			"cc": map[string]any{
				"type":        "string",
				"description": "CC recipient(s), comma-separated",
			},
			"download": map[string]any{
				"type":        "boolean",
				"description": "For the attachment action: when true, save the selected attachment to a local file and return its path instead of extracting text. Pass that path to the send_file tool to forward the file to the user.",
			},
			"html": map[string]any{
				"type":        "boolean",
				"description": "Send body as HTML (default: false)",
				"default":     false,
			},
			"label_action": map[string]any{
				"type":        "string",
				"description": "Label sub-action (for label action)",
				"enum":        []string{"list", "add", "remove"},
			},
			"label_name": map[string]any{
				"type":        "string",
				"description": "Label name (for label add/remove)",
			},
			"max": map[string]any{
				"type":        "number",
				"description": "Maximum results (for inbox/search, or messages kept for thread; default: 10, max: 50)",
				"default":     10,
				"minimum":     1,
				"maximum":     50,
			},
			"message_id": map[string]any{
				"type":        "string",
				"description": "Gmail message ID (for read, reply, label, attachment actions; for thread action, resolves the containing thread). Copy it EXACTLY from a Gmail result's 'ID:' field — never construct or guess one. For read, you may omit it and pass query instead.",
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Gmail search query (supports Gmail operators like from:, to:, subject:, newer_than:, is:unread, has:attachment, etc.). Prefer mail_archive for normal received-mail searches; use this only for Gmail-only fallback.",
			},
			"subject": map[string]any{
				"type":        "string",
				"description": "Email subject line",
			},
			"thread_id": map[string]any{
				"type":        "string",
				"description": "Gmail thread ID (for thread action; if omitted, message_id resolves the thread)",
			},
			"timeout": map[string]any{
				"type":        "number",
				"description": "Timeout in seconds (default: 30, max: 60)",
				"default":     30,
				"minimum":     1,
				"maximum":     60,
			},
			"to": map[string]any{
				"type":        "string",
				"description": "Recipient email or contact alias (auto-resolved from KV store gmail.contacts.<alias>). Use 'self' (or me/나/본인) to send to your own tracked mailbox.",
			},
		},
		"required": []string{"action"},
	}
}

func dropboxToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Dropbox action to perform",
				"enum":        []string{"list", "search", "download", "upload", "share", "analyze", "backup"},
			},
			"dest_path": map[string]any{
				"type":        "string",
				"description": "Dropbox destination path for upload (default: /<local filename>)",
			},
			"extract": map[string]any{
				"type":        "boolean",
				"description": "On download, also extract text (PDF/image OCR, Excel/Word/PowerPoint, text files)",
				"default":     false,
			},
			"local_path": map[string]any{
				"type":        "string",
				"description": "Local file path to upload (for the upload action)",
			},
			"max": map[string]any{
				"type":        "number",
				"description": "Maximum results for list/search (default: 20, max: 100)",
				"default":     20,
				"minimum":     1,
				"maximum":     100,
			},
			"overwrite": map[string]any{
				"type":        "boolean",
				"description": "Overwrite an existing file on upload; default false auto-renames",
				"default":     false,
			},
			"path": map[string]any{
				"type":        "string",
				"description": "Dropbox path for list/download/share/analyze (e.g. /folder/file.pdf). Empty means the account root (list).",
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Search query (for the search action)",
			},
			"recursive": map[string]any{
				"type":        "boolean",
				"description": "Recurse into subfolders on list",
				"default":     false,
			},
			"target": map[string]any{
				"type":        "string",
				"description": "Backup target for the backup action: which Deneb artifacts to upload to /Deneb-Backup/<date>/",
				"enum":        []string{"wiki", "weekly", "transcripts", "all"},
			},
		},
		"required": []string{"action"},
	}
}

func skillsToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Action: list (search/browse skills), create, patch, delete, read, list_files, write_file, remove_file",
				"enum":        []string{"list", "create", "patch", "delete", "read", "list_files", "write_file", "remove_file"},
			},
			"apply": map[string]any{
				"type":        "boolean",
				"description": "Immediately invalidate the system prompt skills cache so the change is visible in the current session (default: false — changes load on next session to preserve prompt-cache hit rate).",
				"default":     false,
			},
			"category": map[string]any{
				"type":        "string",
				"description": "Filter category for list, or target category for create (coding, productivity, devops, integration)",
			},
			"content": map[string]any{
				"type":        "string",
				"description": "Full SKILL.md content for create, or patch content",
			},
			"file_content": map[string]any{
				"type":        "string",
				"description": "Content for write_file support file writes",
			},
			"file_path": map[string]any{
				"type":        "string",
				"description": "Relative path within skill dir for read/write_file/remove_file. Writes/removes must stay under references/, templates/, scripts/, or assets/",
			},
			"name": map[string]any{
				"type":        "string",
				"description": "Skill name (lowercase, hyphens). Required for create/patch/delete/read/list_files/write_file/remove_file",
			},
			"new_text": map[string]any{
				"type":        "string",
				"description": "Replacement text (patch action)",
			},
			"old_text": map[string]any{
				"type":        "string",
				"description": "Text to find in SKILL.md (patch action). Fuzzy whitespace matching",
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Search filter for list action (matches name, description, category, tag)",
			},
		},
		"required": []string{"action"},
	}
}

func wikiToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Action: search (ripgrep full-text search), read (read wiki page), index (read master/category index), write (create/update page), log (append diary entry), daily (read recent diary), status (wiki stats)",
				"enum":        []string{"search", "read", "index", "write", "log", "daily", "status"},
			},
			"category": map[string]any{
				"type":        "string",
				"description": "Wiki category for write action or index filter — one of the 6: 프로젝트(일·거래·결정), 인물(사람·조직), 시스템(Deneb 구성·운영), 업무(직무 도메인 지식), 사용자(개인 선호·규칙), 기타(시사·잡학·그 외)",
				"enum":        []string{"프로젝트", "인물", "시스템", "업무", "사용자", "기타"},
			},
			"confidence": map[string]any{
				"type":        "string",
				"description": "Confidence level (write action): high (verified), medium (reasonable inference), low (uncertain)",
				"enum":        []string{"high", "medium", "low"},
			},
			"content": map[string]any{
				"type":        "string",
				"description": "Page body content in markdown (write action) or diary entry body (log action). In write bodies, link related pages inline with [[path-or-title]] (e.g. [[프로젝트/dgx-spark]] or [[홍길동]]); these become knowledge-graph edges, so prefer them over plain mentions.",
			},
			"due": map[string]any{
				"type":        "string",
				"description": "Upcoming deadline in YYYY-MM-DD (write action): payment due, delivery, or milestone date. Surfaced by the morning letter deadline scan.",
			},
			"id": map[string]any{
				"type":        "string",
				"description": "Short identifier (kebab-case, e.g. 'dgx-spark')",
			},
			"importance": map[string]any{
				"type":        "number",
				"description": "Page importance 0.0-1.0 (write action, default: 0.5)",
				"minimum":     0,
				"maximum":     1,
			},
			"limit": map[string]any{
				"type":        "integer",
				"description": "Max results (search: default 10)",
				"minimum":     1,
				"maximum":     50,
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Search query (search), page path (read/write), category name (index), or diary entry body (log)",
			},
			"related": map[string]any{
				"type":        "array",
				"description": "Related page topics (write action)",
				"items": map[string]any{
					"type": "string",
				},
			},
			"section": map[string]any{
				"type":        "string",
				"description": "Read a specific section from the page (read action)",
			},
			"summary": map[string]any{
				"type":        "string",
				"description": "한 줄 요약 (~80자)",
			},
			"tags": map[string]any{
				"type":        "array",
				"description": "Tags for the page (write action)",
				"items": map[string]any{
					"type": "string",
				},
			},
			"title": map[string]any{
				"type":        "string",
				"description": "Page title (write action)",
			},
			"type": map[string]any{
				"type":        "string",
				"description": "Page type (write action): concept, entity, source, comparison, log",
				"enum":        []string{"concept", "entity", "source", "comparison", "log"},
			},
		},
		"required": []string{"action"},
	}
}

func contactsToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "lookup: 전화번호로 인물 찾기 (정규화·+82↔0·뒷자리 폴백). search: 이름·회사·이메일·번호 부분일치 검색 (최대 20건).",
				"enum":        []string{"lookup", "search"},
			},
			"query": map[string]any{
				"type":        "string",
				"description": "조회할 전화번호 (lookup) 또는 검색어 — 이름/회사/이메일/번호 일부 (search).",
			},
		},
		"required": []string{"action", "query"},
	}
}

func calendarToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "list: 일정 조회 (기본 지금부터 48시간; from/to로 명시 범위, 또는 hours_ahead). 겹치는 일정은 ⚠️로, 연결된 일정은 [미팅]·「메일 제목」으로 출처 표시. get: id로 상세(참석자·장소·Meet·메모·연결 출처 — 미팅 준비용). create: 일정 추가(로컬). update: 로컬 일정 수정. delete: 로컬 일정 삭제. free_slots: 근무시간 내 빈 시간(미팅 넣을 자리) 찾기. brief: 오늘(기본; hours_ahead/from·to로 기간) 일정을 연결된 메일 맥락·겹침과 함께 브리핑 골격으로 정리 — 연결된 일정은 mail_archive로 맥락 보강해 '왜 중요한지·무엇을 준비할지'까지 서술. prep: 미팅 준비 — id(생략 시 다음 일정)의 상세 + 연결된 메일을 mail_archive로 열어 직전 합의·미결·준비물 체크리스트 작성 지시. capture: 회의록 정리(끝난 미팅) — id(생략 시 방금 끝난 미팅)의 메모·녹취를 결정·액션·리스크·후속으로 정리하고 update로 일정 description에 기록(일정 자체가 회의 기록). 임원 본인 후속만 강조, 위임 실무는 본문에. 구글 일정은 읽기 전용이라 수정·삭제 불가.",
				"enum":        []string{"list", "get", "create", "update", "delete", "free_slots", "brief", "prep", "capture"},
			},
			"all_day": map[string]any{
				"type":        "boolean",
				"description": "종일 일정 여부 (선택).",
			},
			"day_end": map[string]any{
				"type":        "integer",
				"description": "free_slots: 근무시간 끝 시(1-24, 기본 18 = 오후 6시).",
			},
			"day_start": map[string]any{
				"type":        "integer",
				"description": "free_slots: 근무시간 시작 시(0-23, 기본 9 = 오전 9시).",
			},
			"description": map[string]any{
				"type":        "string",
				"description": "설명·메모 (선택).",
			},
			"duration_min": map[string]any{
				"type":        "integer",
				"description": "free_slots: 찾을 빈 시간의 최소 길이(분, 기본 30).",
			},
			"end": map[string]any{
				"type":        "string",
				"description": "종료 시각 (RFC3339, 선택). 생략 시 1시간(종일은 1일) 자동.",
			},
			"from": map[string]any{
				"type":        "string",
				"description": "list 조회 시작 시각 (RFC3339, 예: 2026-06-10T00:00:00+09:00). to와 함께 명시 범위 조회.",
			},
			"hours_ahead": map[string]any{
				"type":        "integer",
				"description": "list에서 from/to 대신 '지금부터 N시간' (기본 48, 최대 336).",
			},
			"id": map[string]any{
				"type":        "string",
				"description": "이벤트 ID (get/update/delete). list 결과의 'id=...' 값을 그대로 사용. 'local:' 접두사면 로컬(수정·삭제 가능), 아니면 구글(읽기 전용).",
			},
			"location": map[string]any{
				"type":        "string",
				"description": "장소 (선택).",
			},
			"start": map[string]any{
				"type":        "string",
				"description": "시작 시각 (RFC3339, create/update 필수, 예: 2026-06-10T15:00:00+09:00). KST는 +09:00 오프셋.",
			},
			"summary": map[string]any{
				"type":        "string",
				"description": "일정 제목 (create/update 필수).",
			},
			"to": map[string]any{
				"type":        "string",
				"description": "list 조회 끝 시각 (RFC3339).",
			},
		},
		"required": []string{"action"},
	}
}

func polarisToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "search: 현재 세션의 과거 메시지에서 키워드 검색 (모든 메시지가 SQLite FTS에 무손실 저장). describe: 압축된 요약 구간 ID 목록 (time_range 필터). expand: 특정 summary_id의 원문 메시지 복원, question 추가 시 LLM이 원문 기반 답변.",
				"enum":        []string{"search", "describe", "expand"},
			},
			"max_results": map[string]any{
				"type":        "integer",
				"description": "최대 결과 수 (search action, default: 10)",
				"default":     10,
				"minimum":     1,
				"maximum":     50,
			},
			"query": map[string]any{
				"type":        "string",
				"description": "검색 키워드 (search action)",
			},
			"question": map[string]any{
				"type":        "string",
				"description": "원본 대화에서 알고 싶은 질문 (expand action, 선택)",
			},
			"summary_id": map[string]any{
				"type":        "integer",
				"description": "요약 노드 ID (expand action, describe 결과에서 획득)",
				"minimum":     1,
			},
			"time_range": map[string]any{
				"type":        "string",
				"description": "시간 범위 (describe action): today, this_week, all",
				"default":     "all",
				"enum":        []string{"today", "this_week", "all"},
			},
		},
		"required": []string{"action"},
	}
}

func knowledgeToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"body": map[string]any{
				"type":        "string",
				"description": "페이지 본문 markdown (op=record). 비어 있으면 새 페이지에 기본 골격 자동 삽입",
			},
			"category": map[string]any{
				"type":        "string",
				"description": "프론트매터 카테고리 (op=record) — 프로젝트·인물·시스템·업무·사용자·기타",
			},
			"importance": map[string]any{
				"type":        "number",
				"description": "Tier1 surfacing 가중치 0.0~1.0 (op=record, 0.85↑은 시스템 프롬프트에 자동 노출)",
				"minimum":     0,
				"maximum":     1,
			},
			"limit": map[string]any{
				"type":        "integer",
				"description": "결과 개수 상한 (op=recall, 기본 10, max 50)",
				"default":     10,
				"minimum":     1,
				"maximum":     50,
			},
			"op": map[string]any{
				"type":        "string",
				"description": "recall: 위키 지식베이스 의미+키워드 검색. read: ref로 단건 fetch — `w:인물/박부장` 같이 prefix가 layer 라우팅. record: wiki에 큐레이션 페이지 작성·갱신.",
				"enum":        []string{"recall", "read", "record"},
			},
			"page": map[string]any{
				"type":        "string",
				"description": "wiki 페이지 상대 경로 (op=record). 카테고리/이름 형식 — 예: `인물/박부장`, `프로젝트/ABC상사-NDA`",
			},
			"query": map[string]any{
				"type":        "string",
				"description": "검색 키워드 (op=recall)",
			},
			"ref": map[string]any{
				"type":        "string",
				"description": "단건 ref (op=read). 형식 `<layer>:<id>` — 예: `w:인물/박부장`, `h:mem-7K9L`",
			},
			"related": map[string]any{
				"type":        "array",
				"description": "관련 페이지 경로들 (op=record)",
				"items": map[string]any{
					"type": "string",
				},
			},
			"summary": map[string]any{
				"type":        "string",
				"description": "인덱스용 한 줄 요약 (op=record, ~80자)",
			},
			"tags": map[string]any{
				"type":        "array",
				"description": "검색 태그 (op=record)",
				"items": map[string]any{
					"type": "string",
				},
			},
			"title": map[string]any{
				"type":        "string",
				"description": "페이지 제목 (op=record, 미지정 시 page의 마지막 segment 사용)",
			},
		},
		"required": []string{"op"},
	}
}

func fetchToolsToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"names": map[string]any{
				"type":        "array",
				"description": "Exact tool names to activate (from the deferred tools list)",
				"minItems":    1,
				"maxItems":    10,
				"items": map[string]any{
					"type": "string",
				},
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Keyword search to find matching deferred tools (alternative to names)",
			},
		},
	}
}

func graphifyToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "query: BFS/DFS traversal of the knowledge graph for a natural-language question. explain: plain-language description of a node and its neighbors. path: shortest path between two nodes",
				"enum":        []string{"query", "path", "explain"},
			},
			"budget": map[string]any{
				"type":        "number",
				"description": "Optional for action=query. Max output tokens (default: 2000)",
				"minimum":     100,
				"maximum":     20000,
			},
			"dfs": map[string]any{
				"type":        "boolean",
				"description": "Optional for action=query. Use depth-first instead of breadth-first traversal (default: false)",
				"default":     false,
			},
			"from": map[string]any{
				"type":        "string",
				"description": "Required for action=path. Source node label",
			},
			"graph": map[string]any{
				"type":        "string",
				"description": "Which graph to query. \"wiki\" (default, ~/.deneb/wiki-graph/graph.json — concept/entity knowledge from the wiki dreamer), \"code\" (workspace/graphify-out/graph.json — call/import graph built by graphify update), or an absolute/relative path to a custom graph.json",
			},
			"node": map[string]any{
				"type":        "string",
				"description": "Required for action=explain. Node label (page id, file path, symbol, or function name) to explain",
			},
			"question": map[string]any{
				"type":        "string",
				"description": "Required for action=query. Natural-language question",
			},
			"to": map[string]any{
				"type":        "string",
				"description": "Required for action=path. Target node label",
			},
		},
		"required": []string{"action"},
	}
}

func heartbeatUpdateToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"content": map[string]any{
				"type":        "string",
				"description": "Full new contents of ~/.deneb/HEARTBEAT.md. Pass empty string to clear the file. The autonomous heartbeat loop reads this file every 30 minutes; remove completed/cancelled items, update progress on ongoing items, and use a '## archive' section for items that have stalled.",
			},
		},
		"required": []string{"content"},
	}
}

func todoToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "list | add | done | delete",
			},
			"done": map[string]any{
				"type":        "boolean",
				"description": "Completion state for the done action (default true)",
			},
			"due": map[string]any{
				"type":        "string",
				"description": "Optional due date, YYYY-MM-DD",
			},
			"id": map[string]any{
				"type":        "string",
				"description": "To-do id for done/delete (run list first to get it)",
			},
			"title": map[string]any{
				"type":        "string",
				"description": "Title of the to-do (required for add)",
			},
		},
		"required": []string{"action"},
	}
}

func watchToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"end": map[string]any{
				"type":        "number",
				"description": "Optional analysis window end in seconds",
			},
			"source": map[string]any{
				"type":        "string",
				"description": "YouTube URL or local video file path to watch (extract frames + subtitles, then analyze with the vision model)",
			},
			"start": map[string]any{
				"type":        "number",
				"description": "Optional analysis window start in seconds",
			},
			"task": map[string]any{
				"type":        "string",
				"description": "What to analyze in the video (e.g. 'analyze the hook in the first 3 seconds', 'where does the UI break?'). Default: general analysis",
			},
		},
		"required": []string{"source"},
	}
}

func observeToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "What to observe about your own runtime: turn | logs | behavior | effort | proactive",
				"enum":        []string{"turn", "logs", "behavior", "effort", "proactive"},
			},
			"contains": map[string]any{
				"type":        "string",
				"description": "Substring filter on the log message for action=logs",
			},
			"days": map[string]any{
				"type":        "number",
				"description": "Window in days for action=behavior and action=effort (omit = all retained history)",
			},
			"level": map[string]any{
				"type":        "string",
				"description": "Min log level for action=logs: debug | info | warn | error (default debug)",
			},
			"limit": map[string]any{
				"type":        "number",
				"description": "Max log lines for action=logs",
			},
			"runId": map[string]any{
				"type":        "string",
				"description": "Run id — required for action=turn; optional filter for action=logs",
			},
			"session": map[string]any{
				"type":        "string",
				"description": "Session key filter for action=logs",
			},
		},
		"required": []string{"action"},
	}
}

func fleetToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "What to do with the SparkFleet GPU control plane: status (nodes + recipes + recent failed jobs at a glance) | recipes (every model recipe with running/health) | jobs (recent background jobs) | launch | stop | restart (a recipe by name) | cancel (a background job by id) | diagnose (crash triage of a running recipe's container)",
				"enum":        []string{"status", "recipes", "jobs", "launch", "stop", "restart", "cancel", "diagnose"},
			},
			"jobId": map[string]any{
				"type":        "string",
				"description": "Background job id — required for cancel",
			},
			"recipe": map[string]any{
				"type":        "string",
				"description": "Recipe name — required for launch / stop / restart / diagnose",
			},
		},
		"required": []string{"action"},
	}
}

func phoneReadToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"what": map[string]any{
				"type":        "string",
				"description": "조회 대상: location(현재 GPS 좌표) | clipboard(방금 복사한 내용) | battery(배터리·충전 상태) | calllog(최근 통화기록 20건) | contacts(폰 주소록)",
				"enum":        []string{"location", "clipboard", "battery", "calllog", "contacts"},
			},
		},
		"required": []string{"what"},
	}
}

func phoneWriteToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"text": map[string]any{
				"type":        "string",
				"description": "보낼/읽을/넣을 텍스트 내용",
			},
			"title": map[string]any{
				"type":        "string",
				"description": "notification 제목 (생략 시 Deneb)",
			},
			"to": map[string]any{
				"type":        "string",
				"description": "작용 대상: notification(알림 띄우기) | tts(음성으로 읽어주기) | clipboard(클립보드에 넣기)",
				"enum":        []string{"notification", "tts", "clipboard"},
			},
		},
		"required": []string{"to", "text"},
	}
}

func goalToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Goal action",
				"enum":        []string{"set", "subgoal", "status", "pause", "resume", "stop"},
			},
			"goal": map[string]any{
				"type":        "string",
				"description": "Objective text (required for action=set). Free-form, e.g. '탑솔라 6월 견적을 정리해 초안까지'.",
			},
			"max_turns": map[string]any{
				"type":        "number",
				"description": "Optional run budget for action=set (default 20). Auto-pauses (resumable) when exhausted.",
			},
			"subgoal": map[string]any{
				"type":        "string",
				"description": "A specific completion criterion to add (required for action=subgoal). The judge requires per-criterion evidence before marking the goal done.",
			},
		},
		"required": []string{"action"},
	}
}

func mailArchiveToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "list(최근/오늘 메일 목록+Locator) | search(키워드 검색+Locator) | read(Locator/ID 또는 query로 원문 열기) | thread(References/In-Reply-To + 제목/참여자 fallback 기반 전체 스레드 복원) | project_history(회사·프로젝트 키워드 시간선+스레드 후보; 로컬 FTS+업무 신호 랭킹)",
				"enum":        []string{"list", "search", "read", "thread", "project_history", "history"},
			},
			"as_json": map[string]any{
				"type":        "boolean",
				"description": "true면 사람이 읽는 텍스트 대신 구조화 JSON을 반환한다. code_action에서는 deneb.mail_archive(..., as_json=True)로 메시지/히스토리, Locator, rank_reasons, related_wiki, related_events를 바로 조인·필터링할 수 있다",
			},
			"days": map[string]any{
				"type":        "number",
				"description": "action=list에서 최근 며칠치를 볼지 (기본 1=오늘). 예: 7=최근 7일",
				"minimum":     1,
			},
			"include_body": map[string]any{
				"type":        "boolean",
				"description": "search/project_history/list 결과에 본문 일부까지 포함할지. 기본 false; 전체 맥락은 read/thread를 선호",
			},
			"limit": map[string]any{
				"type":        "number",
				"description": "최대 반환 건수 (기본 50, 내부 상한 200)",
				"minimum":     1,
			},
			"mailbox": map[string]any{
				"type":        "string",
				"description": "조회할 메일함 selector. all(기본: 설정된 자체 아카이브 전체) | INBOX(자동보관 수신함) | archive/backfill(일반/과거 백필 mailbox; Archive/All Mail/Gmail 후보) | legacy_gmail(구 Gmail 백필 mailbox) | 실제 IMAP mailbox 이름",
			},
			"message_id": map[string]any{
				"type":        "string",
				"description": "read/thread에서 열 기준. mail_archive 결과의 Locator를 그대로 넣는 것이 가장 안정적이며, 일반 Message-ID-derived ID도 가능",
			},
			"query": map[string]any{
				"type":        "string",
				"description": "search/project_history의 검색어. read/thread에서 message_id가 없으면 이 query의 최신 상위 메일을 seed로 사용",
			},
		},
		"required": []string{"action"},
	}
}

// ToolMaxOutputs returns per-tool output character budgets from tool_schemas.json.
// Tools not in this map use agent.DefaultMaxOutput.
func ToolMaxOutputs() map[string]int {
	return map[string]int{
		"calendar": 8000,
		"contacts": 8000,
		"exec":     32000,
		"wiki":     20000,
	}
}
