// Code generated by tool-schema-gen. DO NOT EDIT.
// Source: gateway-go/internal/pipeline/chat/toolreg/tool_schemas.json
// Regenerate: make tool-schemas

package toolreg

func readToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"file_path": map[string]any{
				"type":        "string",
				"description": "The absolute path to the file to read",
			},
			"force": map[string]any{
				"type":        "boolean",
				"description": "Force re-read even if cached (default: false)",
				"default":     false,
			},
			"function": map[string]any{
				"type":        "string",
				"description": "Read only this function/method/type. For .go files uses AST; for others uses regex. Overrides offset/limit",
			},
			"limit": map[string]any{
				"type":        "number",
				"description": "The number of lines to read (default: 2000)",
				"default":     2000,
				"minimum":     1,
			},
			"offset": map[string]any{
				"type":        "number",
				"description": "The line number to start reading from (1-based)",
				"minimum":     1,
			},
		},
		"required": []string{"file_path"},
	}
}

func readSpilloverToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"spill_id": map[string]any{
				"type":        "string",
				"description": "The spillover reference ID (e.g., sp_abc123) from a previous large tool result",
			},
		},
		"required": []string{"spill_id"},
	}
}

func writeToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"content": map[string]any{
				"type":        "string",
				"description": "The content to write to the file",
			},
			"file_path": map[string]any{
				"type":        "string",
				"description": "The absolute path to the file to write",
			},
		},
		"required": []string{"file_path", "content"},
	}
}

func editToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"file_path": map[string]any{
				"type":        "string",
				"description": "The absolute path to the file to modify",
			},
			"line": map[string]any{
				"type":        "number",
				"description": "Replace at a specific line number (1-based). When set, old_string matches only on this line",
				"minimum":     1,
			},
			"new_string": map[string]any{
				"type":        "string",
				"description": "The text to replace it with. When regex=true, supports $1/$2 backreferences",
			},
			"old_string": map[string]any{
				"type":        "string",
				"description": "The text to replace (must be unique unless replace_all is true). When regex=true, treated as a regex pattern",
			},
			"regex": map[string]any{
				"type":        "boolean",
				"description": "Treat old_string as a regex pattern (default: false)",
				"default":     false,
			},
			"replace_all": map[string]any{
				"type":        "boolean",
				"description": "Replace all occurrences instead of requiring a unique match (default: false)",
				"default":     false,
			},
		},
		"required": []string{"file_path", "old_string", "new_string"},
	}
}

func grepToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"after": map[string]any{
				"type":        "number",
				"description": "Lines of context after each match (overrides contextLines for after)",
				"minimum":     0,
				"maximum":     10,
			},
			"before": map[string]any{
				"type":        "number",
				"description": "Lines of context before each match (overrides contextLines for before)",
				"minimum":     0,
				"maximum":     10,
			},
			"contextLines": map[string]any{
				"type":        "number",
				"description": "Lines of context around each match (0-10)",
				"default":     0,
				"minimum":     0,
				"maximum":     10,
			},
			"fileType": map[string]any{
				"type":        "string",
				"description": "File type filter for ripgrep --type (e.g. \"go\", \"py\", \"js\")",
			},
			"ignoreCase": map[string]any{
				"type":        "boolean",
				"description": "Case-insensitive search",
				"default":     false,
			},
			"include": map[string]any{
				"type":        "string",
				"description": "Glob pattern to filter files (e.g. \"*.ts\")",
			},
			"maxResults": map[string]any{
				"type":        "number",
				"description": "Maximum matches to return",
				"default":     100,
				"minimum":     1,
				"maximum":     500,
			},
			"mode": map[string]any{
				"type":        "string",
				"description": "Output mode: content (default, matching lines), files_only (file paths only), count (match counts per file)",
				"enum":        []string{"content", "files_only", "count"},
			},
			"multiline": map[string]any{
				"type":        "boolean",
				"description": "Enable multiline matching (patterns can span lines, . matches newlines)",
				"default":     false,
			},
			"path": map[string]any{
				"type":        "string",
				"description": "File or directory to search in",
			},
			"pattern": map[string]any{
				"type":        "string",
				"description": "Regular expression pattern to search for",
			},
		},
		"required": []string{"pattern"},
	}
}

func gitToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"abort": map[string]any{
				"type":        "boolean",
				"description": "Abort in-progress merge/rebase/cherry-pick",
				"default":     false,
			},
			"action": map[string]any{
				"type":        "string",
				"description": "Git action to perform",
				"enum":        []string{"status", "commit", "log", "branch", "stash", "blame", "tag", "merge", "rebase", "cherry_pick", "reset", "remote", "clean"},
			},
			"all": map[string]any{
				"type":        "boolean",
				"description": "Stage all tracked changes before commit (git commit -a)",
				"default":     false,
			},
			"amend": map[string]any{
				"type":        "boolean",
				"description": "Amend the last commit",
				"default":     false,
			},
			"author": map[string]any{
				"type":        "string",
				"description": "Filter log by author",
			},
			"branch": map[string]any{
				"type":        "string",
				"description": "Branch to merge",
			},
			"continue_op": map[string]any{
				"type":        "boolean",
				"description": "Continue in-progress rebase/cherry-pick",
				"default":     false,
			},
			"count": map[string]any{
				"type":        "number",
				"description": "Number of log entries (default: 10, max: 50)",
				"default":     10,
				"minimum":     1,
				"maximum":     50,
			},
			"create": map[string]any{
				"type":        "boolean",
				"description": "Create a new branch",
				"default":     false,
			},
			"delete": map[string]any{
				"type":        "boolean",
				"description": "Delete the named branch/tag",
				"default":     false,
			},
			"directories": map[string]any{
				"type":        "boolean",
				"description": "Also remove untracked directories (clean -d)",
				"default":     false,
			},
			"dry_run": map[string]any{
				"type":        "boolean",
				"description": "Show what would be removed without actually removing (clean)",
				"default":     true,
			},
			"end_line": map[string]any{
				"type":        "number",
				"description": "End line for blame range",
			},
			"file": map[string]any{
				"type":        "string",
				"description": "File path for blame",
			},
			"files": map[string]any{
				"type":        "array",
				"description": "Files to stage before commit. Empty = commit currently staged files",
				"items": map[string]any{
					"type": "string",
				},
			},
			"force": map[string]any{
				"type":        "boolean",
				"description": "Force clean (-f). Required when dry_run is false",
				"default":     false,
			},
			"from": map[string]any{
				"type":        "string",
				"description": "Base ref for branch creation",
			},
			"grep": map[string]any{
				"type":        "string",
				"description": "Filter log by commit message grep pattern",
			},
			"message": map[string]any{
				"type":        "string",
				"description": "Commit message (commit), stash message (stash push), tag annotation (tag)",
			},
			"mode": map[string]any{
				"type":        "string",
				"description": "Reset mode: soft, mixed (default), hard",
				"enum":        []string{"soft", "mixed", "hard"},
			},
			"name": map[string]any{
				"type":        "string",
				"description": "Branch/tag/remote name",
			},
			"no_ff": map[string]any{
				"type":        "boolean",
				"description": "No fast-forward merge",
				"default":     false,
			},
			"oneline": map[string]any{
				"type":        "boolean",
				"description": "One-line log format",
				"default":     false,
			},
			"onto": map[string]any{
				"type":        "string",
				"description": "Rebase onto target ref",
			},
			"path": map[string]any{
				"type":        "string",
				"description": "File path for log/blame",
			},
			"ref": map[string]any{
				"type":        "string",
				"description": "Git ref for cherry-pick or reset",
			},
			"remote_action": map[string]any{
				"type":        "string",
				"description": "Remote sub-action: list (default), add, remove",
				"enum":        []string{"list", "add", "remove"},
			},
			"short": map[string]any{
				"type":        "boolean",
				"description": "Short status format",
				"default":     false,
			},
			"since": map[string]any{
				"type":        "string",
				"description": "Filter log since date (e.g. '2024-01-01', '1 week ago')",
			},
			"start_line": map[string]any{
				"type":        "number",
				"description": "Start line for blame range",
			},
			"stash_action": map[string]any{
				"type":        "string",
				"description": "Stash sub-action",
				"enum":        []string{"push", "pop", "list", "drop", "apply"},
			},
			"switch_to": map[string]any{
				"type":        "boolean",
				"description": "Switch to the named branch",
				"default":     false,
			},
			"url": map[string]any{
				"type":        "string",
				"description": "Remote URL for add",
			},
		},
		"required": []string{"action"},
	}
}

func execToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"background": map[string]any{
				"type":        "boolean",
				"description": "Run in background immediately, then use process tool to check output",
				"default":     false,
			},
			"command": map[string]any{
				"type":        "string",
				"description": "Shell command to execute",
			},
			"env": map[string]any{
				"type":        "object",
				"description": "Environment variables to set for this command (key-value pairs). Blocked keys (API keys, secrets) are filtered.",
				"additionalProperties": map[string]any{
					"type": "string",
				},
			},
			"structured": map[string]any{
				"type":        "boolean",
				"description": "Return JSON with stdout, stderr, exit_code, runtime_ms instead of plain text",
				"default":     false,
			},
			"timeout": map[string]any{
				"type":        "number",
				"description": "Timeout in seconds (default: 60, max: 600)",
				"default":     60,
				"minimum":     1,
				"maximum":     600,
			},
			"workdir": map[string]any{
				"type":        "string",
				"description": "Working directory (defaults to workspace root)",
			},
		},
		"required": []string{"command"},
	}
}

func processToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Process action",
				"enum":        []string{"list", "poll", "log", "write", "kill"},
			},
			"input": map[string]any{
				"type":        "string",
				"description": "Data to write to process stdin (required for write action)",
			},
			"sessionId": map[string]any{
				"type":        "string",
				"description": "Session ID for actions other than list",
			},
			"timeout": map[string]any{
				"type":        "number",
				"description": "Poll timeout in milliseconds",
			},
		},
		"required": []string{"action"},
	}
}

func webToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"count": map[string]any{
				"type":        "number",
				"description": "Number of search results per query (default: 5)",
			},
			"fetch": map[string]any{
				"type":        "number",
				"description": "Auto-fetch top N results per query (1-3, default: 0)",
			},
			"maxChars": map[string]any{
				"type":        "number",
				"description": "Maximum content characters total (default: 50000)",
			},
			"queries": map[string]any{
				"type":        "array",
				"description": "Multiple parallel search queries (max 5)",
				"items": map[string]any{
					"type": "string",
				},
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Web search query. Serper (Google) > Brave > DuckDuckGo fallback",
			},
			"url": map[string]any{
				"type":        "string",
				"description": "URL to fetch (HTML extraction + bot evasion)",
			},
		},
	}
}

func cronToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Cron action",
				"enum":        []string{"status", "list", "add", "update", "remove", "run", "get", "runs", "wake"},
			},
			"anchorTime": map[string]any{
				"type":        "string",
				"description": "Anchor time for interval schedules (ISO 8601). Intervals count from this time instead of registration time",
			},
			"command": map[string]any{
				"type":        "string",
				"description": "Agent message/command to execute on schedule (required for add)",
			},
			"deliveryMode": map[string]any{
				"type":        "string",
				"description": "How to deliver output: announce (send to Telegram, default) or none (run silently)",
				"enum":        []string{"announce", "none"},
			},
			"enabled": map[string]any{
				"type":        "boolean",
				"description": "Enable or disable a job (for add/update)",
			},
			"job": map[string]any{
				"type":                 "object",
				"description":          "Job definition object (alternative to top-level name/schedule/command)",
				"additionalProperties": true,
			},
			"jobId": map[string]any{
				"type":        "string",
				"description": "Job ID for get/update/remove/run/runs actions",
			},
			"limit": map[string]any{
				"type":        "integer",
				"description": "Max entries to return (for runs action, default 10)",
			},
			"name": map[string]any{
				"type":        "string",
				"description": "Job name (required for add, used as job ID)",
			},
			"retryBackoffMs": map[string]any{
				"type":        "integer",
				"description": "Initial backoff delay between retries in ms (default 5000). Doubles each retry, capped at 60s",
			},
			"retryCount": map[string]any{
				"type":        "integer",
				"description": "Number of retry attempts on failure (0-3, default 0 = no retry)",
			},
			"schedule": map[string]any{
				"type":        "string",
				"description": "Schedule specification. Formats: cron (0 9 * * *), interval (1h, 30m, every 5m), timestamp (2026-04-06T08:00:00), shorthand (@daily, @hourly, @weekly)",
			},
			"staggerMs": map[string]any{
				"type":        "integer",
				"description": "Random delay window in ms to distribute cron jobs (cron kind only, default: auto for top-of-hour)",
			},
			"text": map[string]any{
				"type":        "string",
				"description": "System event text for wake action",
			},
			"tz": map[string]any{
				"type":        "string",
				"description": "Timezone for cron schedules (e.g. Asia/Seoul, UTC). Defaults to system local timezone",
			},
		},
		"required": []string{"action"},
	}
}

func messageToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Message action",
				"enum":        []string{"send", "react", "reply", "thread-reply"},
			},
			"channel": map[string]any{
				"type":        "string",
				"description": "Target channel (e.g., telegram)",
			},
			"emoji": map[string]any{
				"type":        "string",
				"description": "Emoji for react action",
			},
			"message": map[string]any{
				"type":        "string",
				"description": "Text content to send",
			},
			"messageId": map[string]any{
				"type":        "string",
				"description": "Message ID for react/reply actions",
			},
			"replyTo": map[string]any{
				"type":        "string",
				"description": "Message ID to reply to",
			},
			"silent": map[string]any{
				"type":        "boolean",
				"description": "Send without notification sound",
			},
			"to": map[string]any{
				"type":        "string",
				"description": "Recipient (chat ID or user identifier)",
			},
		},
		"required": []string{"action"},
	}
}

func clarifyToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"options": map[string]any{
				"type":        "array",
				"description": "2-5 selection options. Each must be Korean text, 40 characters or less (visible as a Telegram inline-keyboard button label).",
				"minItems":    2,
				"maxItems":    5,
				"items": map[string]any{
					"type": "string",
				},
			},
			"question": map[string]any{
				"type":        "string",
				"description": "Korean question asking the user to resolve an ambiguity. Example: '현재 3개의 config.yaml이 있습니다. 어느 것을 수정할까요?'",
			},
		},
		"required": []string{"question", "options"},
	}
}

func gatewayToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Gateway action. Destructive actions (restart/update/config_set) require approval: the first call returns a needs_approval envelope; after the user confirms, call the .confirmed variant with the same action_token.",
				"enum":        []string{"status", "config_get", "config_set", "config_set.confirmed", "update", "update.confirmed", "restart", "restart.confirmed", "config.get", "config.schema.lookup", "config.apply", "config.patch", "update.run"},
			},
			"action_token": map[string]any{
				"type":        "string",
				"description": "Token returned by a prior approval envelope; required when calling a .confirmed variant.",
			},
			"path": map[string]any{
				"type":        "string",
				"description": "Dotted config path for config_get / config_set (e.g. \"model.main\"). Also used for config.schema.lookup.",
			},
			"raw": map[string]any{
				"type":        "string",
				"description": "Raw config JSON for apply/patch",
			},
			"reason": map[string]any{
				"type":        "string",
				"description": "Reason for restart or update",
			},
			"value": map[string]any{
				"description": "Leaf value to write (config_set only). Must be a scalar, array, or null — object replacement is rejected.",
			},
		},
		"required": []string{"action"},
	}
}

func sessionsToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Session action",
				"enum":        []string{"list", "history", "search", "send"},
			},
			"kinds": map[string]any{
				"type":        "array",
				"description": "Filter by session kind (list action)",
				"items": map[string]any{
					"type": "string",
					"enum": []string{"main", "group", "cron", "hook"},
				},
			},
			"limit": map[string]any{
				"type":        "number",
				"description": "Max sessions (list) or messages (history, default 20) to return",
				"default":     20,
				"minimum":     1,
			},
			"maxResults": map[string]any{
				"type":        "number",
				"description": "Max search results (search action, default 20)",
				"default":     20,
				"minimum":     1,
				"maximum":     100,
			},
			"message": map[string]any{
				"type":        "string",
				"description": "Message to send (send action)",
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Search keyword (search action)",
			},
			"sessionKey": map[string]any{
				"type":        "string",
				"description": "Target session key (history/send actions)",
			},
		},
		"required": []string{"action"},
	}
}

func sessionsSpawnToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"label": map[string]any{
				"type":        "string",
				"description": "Human-readable label",
			},
			"model": map[string]any{
				"type":        "string",
				"description": "Model role to use (default: main)",
				"enum":        []string{"main", "lightweight", "fallback"},
			},
			"task": map[string]any{
				"type":        "string",
				"description": "Task description for the sub-agent",
			},
			"tool_preset": map[string]any{
				"type":        "string",
				"description": "Tool preset restricting which tools the sub-agent can use. researcher=read-only, implementer=read+write+build, verifier=read+test+exec",
				"enum":        []string{"researcher", "implementer", "verifier"},
			},
		},
		"required": []string{"task"},
	}
}

func subagentsToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Sub-agent management action",
				"enum":        []string{"list", "kill", "steer"},
			},
			"message": map[string]any{
				"type":        "string",
				"description": "Steering message for steer action",
			},
			"target": map[string]any{
				"type":        "string",
				"description": "Target sub-agent ID or label",
			},
		},
	}
}

func sendFileToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"caption": map[string]any{
				"type":        "string",
				"description": "Caption text (optional)",
			},
			"file_path": map[string]any{
				"type":        "string",
				"description": "Path to the file to send",
			},
			"silent": map[string]any{
				"type":        "boolean",
				"description": "Send without notification sound",
			},
			"type": map[string]any{
				"type":        "string",
				"description": "Media type. Auto-detected from MIME if omitted",
				"enum":        []string{"photo", "document", "video", "audio", "voice"},
			},
		},
		"required": []string{"file_path"},
	}
}

func gmailToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Gmail action to perform",
				"enum":        []string{"inbox", "search", "read", "send", "reply", "label", "analyze"},
			},
			"bcc": map[string]any{
				"type":        "string",
				"description": "BCC recipient(s), comma-separated",
			},
			"body": map[string]any{
				"type":        "string",
				"description": "Email body text (plain text or HTML if html=true)",
			},
			"cc": map[string]any{
				"type":        "string",
				"description": "CC recipient(s), comma-separated",
			},
			"html": map[string]any{
				"type":        "boolean",
				"description": "Send body as HTML (default: false)",
				"default":     false,
			},
			"label_action": map[string]any{
				"type":        "string",
				"description": "Label sub-action (for label action)",
				"enum":        []string{"list", "add", "remove"},
			},
			"label_name": map[string]any{
				"type":        "string",
				"description": "Label name (for label add/remove)",
			},
			"max": map[string]any{
				"type":        "number",
				"description": "Maximum results (for inbox/search, default: 10, max: 50)",
				"default":     10,
				"minimum":     1,
				"maximum":     50,
			},
			"message_id": map[string]any{
				"type":        "string",
				"description": "Email message or thread ID (for read, reply, label actions)",
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Gmail search query (supports Gmail operators like from:, to:, subject:, newer_than:, is:unread, has:attachment, etc.)",
			},
			"subject": map[string]any{
				"type":        "string",
				"description": "Email subject line",
			},
			"timeout": map[string]any{
				"type":        "number",
				"description": "Timeout in seconds (default: 30, max: 60)",
				"default":     30,
				"minimum":     1,
				"maximum":     60,
			},
			"to": map[string]any{
				"type":        "string",
				"description": "Recipient email or contact alias (auto-resolved from KV store gmail.contacts.<alias>)",
			},
		},
		"required": []string{"action"},
	}
}

func skillsToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Action: list (search/browse skills), create, patch, delete, read, list_files",
				"enum":        []string{"list", "create", "patch", "delete", "read", "list_files"},
			},
			"apply": map[string]any{
				"type":        "boolean",
				"description": "Immediately invalidate the system prompt skills cache so the change is visible in the current session (default: false — changes load on next session to preserve prompt-cache hit rate).",
				"default":     false,
			},
			"category": map[string]any{
				"type":        "string",
				"description": "Filter category for list, or target category for create (coding, productivity, devops, integration)",
			},
			"content": map[string]any{
				"type":        "string",
				"description": "Full SKILL.md content for create, or patch content",
			},
			"file_content": map[string]any{
				"type":        "string",
				"description": "Content for auxiliary file writes",
			},
			"file_path": map[string]any{
				"type":        "string",
				"description": "Relative path within skill dir for auxiliary files",
			},
			"name": map[string]any{
				"type":        "string",
				"description": "Skill name (lowercase, hyphens). Required for create/patch/delete/read/list_files",
			},
			"new_text": map[string]any{
				"type":        "string",
				"description": "Replacement text (patch action)",
			},
			"old_text": map[string]any{
				"type":        "string",
				"description": "Text to find in SKILL.md (patch action). Fuzzy whitespace matching",
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Search filter for list action (matches name, description, category, tag)",
			},
		},
		"required": []string{"action"},
	}
}

func wikiToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Action: search (ripgrep full-text search), read (read wiki page), index (read master/category index), write (create/update page), log (append diary entry), daily (read recent diary), status (wiki stats)",
				"enum":        []string{"search", "read", "index", "write", "log", "daily", "status"},
			},
			"category": map[string]any{
				"type":        "string",
				"description": "Wiki category for write action or index filter",
				"enum":        []string{"사람", "프로젝트", "기술", "업무", "결정", "선호"},
			},
			"confidence": map[string]any{
				"type":        "string",
				"description": "Confidence level (write action): high (verified), medium (reasonable inference), low (uncertain)",
				"enum":        []string{"high", "medium", "low"},
			},
			"content": map[string]any{
				"type":        "string",
				"description": "Page body content in markdown (write action) or diary entry body (log action)",
			},
			"id": map[string]any{
				"type":        "string",
				"description": "Short identifier (kebab-case, e.g. 'dgx-spark')",
			},
			"importance": map[string]any{
				"type":        "number",
				"description": "Page importance 0.0-1.0 (write action, default: 0.5)",
				"minimum":     0,
				"maximum":     1,
			},
			"limit": map[string]any{
				"type":        "integer",
				"description": "Max results (search: default 10)",
				"minimum":     1,
				"maximum":     50,
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Search query (search), page path (read/write), category name (index), or diary entry body (log)",
			},
			"related": map[string]any{
				"type":        "array",
				"description": "Related page topics (write action)",
				"items": map[string]any{
					"type": "string",
				},
			},
			"section": map[string]any{
				"type":        "string",
				"description": "Read a specific section from the page (read action)",
			},
			"summary": map[string]any{
				"type":        "string",
				"description": "한 줄 요약 (~80자)",
			},
			"tags": map[string]any{
				"type":        "array",
				"description": "Tags for the page (write action)",
				"items": map[string]any{
					"type": "string",
				},
			},
			"title": map[string]any{
				"type":        "string",
				"description": "Page title (write action)",
			},
			"type": map[string]any{
				"type":        "string",
				"description": "Page type (write action): concept, entity, source, comparison, log",
				"enum":        []string{"concept", "entity", "source", "comparison", "log"},
			},
		},
		"required": []string{"action"},
	}
}

func polarisToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Action: search (keyword search), describe (summary structure overview), expand (restore original messages from summary node)",
				"enum":        []string{"search", "describe", "expand"},
			},
			"max_results": map[string]any{
				"type":        "integer",
				"description": "최대 결과 수 (search action, default: 10)",
				"default":     10,
				"minimum":     1,
				"maximum":     50,
			},
			"query": map[string]any{
				"type":        "string",
				"description": "검색 키워드 (search action)",
			},
			"question": map[string]any{
				"type":        "string",
				"description": "원본 대화에서 알고 싶은 질문 (expand action, 선택)",
			},
			"summary_id": map[string]any{
				"type":        "integer",
				"description": "요약 노드 ID (expand action, describe 결과에서 획득)",
				"minimum":     1,
			},
			"time_range": map[string]any{
				"type":        "string",
				"description": "시간 범위 (describe action): today, this_week, all",
				"default":     "all",
				"enum":        []string{"today", "this_week", "all"},
			},
		},
		"required": []string{"action"},
	}
}

func fetchToolsToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"names": map[string]any{
				"type":        "array",
				"description": "Exact tool names to activate (from the deferred tools list)",
				"minItems":    1,
				"maxItems":    10,
				"items": map[string]any{
					"type": "string",
				},
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Keyword search to find matching deferred tools (alternative to names)",
			},
		},
	}
}

func graphifyToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "query: BFS/DFS traversal of the knowledge graph for a natural-language question. explain: plain-language description of a node and its neighbors. path: shortest path between two nodes",
				"enum":        []string{"query", "path", "explain"},
			},
			"budget": map[string]any{
				"type":        "number",
				"description": "Optional for action=query. Max output tokens (default: 2000)",
				"minimum":     100,
				"maximum":     20000,
			},
			"dfs": map[string]any{
				"type":        "boolean",
				"description": "Optional for action=query. Use depth-first instead of breadth-first traversal (default: false)",
				"default":     false,
			},
			"from": map[string]any{
				"type":        "string",
				"description": "Required for action=path. Source node label",
			},
			"graph": map[string]any{
				"type":        "string",
				"description": "Which graph to query. \"wiki\" (default, ~/.deneb/wiki-graph/graph.json — concept/entity knowledge from the wiki dreamer), \"code\" (workspace graphify-out/graph.json — code call/import graph from `graphify update .`), or an absolute/relative path to a custom graph.json",
			},
			"node": map[string]any{
				"type":        "string",
				"description": "Required for action=explain. Node label (page id, file path, symbol, or function name) to explain",
			},
			"question": map[string]any{
				"type":        "string",
				"description": "Required for action=query. Natural-language question",
			},
			"to": map[string]any{
				"type":        "string",
				"description": "Required for action=path. Target node label",
			},
		},
		"required": []string{"action"},
	}
}

// ToolMaxOutputs returns per-tool output character budgets from tool_schemas.json.
// Tools not in this map use agent.DefaultMaxOutput.
func ToolMaxOutputs() map[string]int {
	return map[string]int{
		"exec": 32000,
		"wiki": 20000,
	}
}
