export const browserCoreExamples = [
  "deneb browser status",
  "deneb browser start",
  "deneb browser stop",
  "deneb browser tabs",
  "deneb browser open https://example.com",
  "deneb browser focus abcd1234",
  "deneb browser close abcd1234",
  "deneb browser screenshot",
  "deneb browser screenshot --full-page",
  "deneb browser screenshot --ref 12",
  "deneb browser snapshot",
  "deneb browser snapshot --format aria --limit 200",
  "deneb browser snapshot --efficient",
  "deneb browser snapshot --labels",
];

export const browserActionExamples = [
  "deneb browser navigate https://example.com",
  "deneb browser resize 1280 720",
  "deneb browser click 12 --double",
  'deneb browser type 23 "hello" --submit',
  "deneb browser press Enter",
  "deneb browser hover 44",
  "deneb browser drag 10 11",
  "deneb browser select 9 OptionA OptionB",
  "deneb browser upload /tmp/deneb/uploads/file.pdf",
  'deneb browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "deneb browser dialog --accept",
  'deneb browser wait --text "Done"',
  "deneb browser evaluate --fn '(el) => el.textContent' --ref 7",
  "deneb browser console --level error",
  "deneb browser pdf",
];
