// Dependency-free, XSS-safe Markdown → React renderer for Deneb's chat replies,
// mail bodies, and wiki/doc previews. Covers GFM at the level the native client
// renders: ATX headings, bold/italic/strikethrough, inline + fenced code (with a
// language label + copy), links/images/autolinks (http/https/mailto only),
// nested ordered/unordered lists, task-list checkboxes, blockquotes (with block
// content), aligned GFM tables, hard line breaks, backslash escapes, and rules.
//
// The grammar (text → Block AST) lives in markdown/parse.ts; this file is the
// AST → React pass. Output is React elements so every text node is auto-escaped —
// no HTML sanitizer needed, and link/image schemes are whitelisted. The ONE
// exception is KaTeX math: its `renderToString` HTML is injected via
// dangerouslySetInnerHTML. That is safe because the HTML is generated by KaTeX
// from the LaTeX source (not passed-through user HTML), and `trust` defaults to
// false so `\href`/`\url` and other URL-injecting macros are disabled — only
// KaTeX's own span/MathML markup is produced. We render our own GFM rather than
// pulling react-markdown + remark (and its build-script supply-chain gate); KaTeX
// is the single math dependency.
import { type CSSProperties, type ReactNode, useEffect, useMemo, useState } from "react";
import katex from "katex";
import { normalizeMarkdown } from "@/markdown/normalize";
import { type Block, type ListItem, parseBlocks } from "@/markdown/parse";
import { Icon } from "./Icon";

// Only these schemes render as live links/images; anything else stays plain text
// so a `javascript:`/`data:` URL can never become a clickable or fetchable node.
function safeHref(url: string): string | null {
  const u = url.trim();
  return /^(https?:\/\/|mailto:)/i.test(u) ? u : null;
}

// Earliest-match inline tokenizer. At each step the pattern that OPENS first wins
// (ties broken by array order), so escapes and images beat the weaker emphasis
// markers. Each alternative captures its inner text for recursive rendering.
const INLINE: { kind: string; re: RegExp }[] = [
  { kind: "esc", re: /\\([\\`*_{}[\]()#+\-.!~>|"'$])/ },
  // Newline hard-breaks + literal <br>/<br/> (Amaranth/e-approval table cells).
  { kind: "br", re: /\n|<br\s*\/?>/i },
  { kind: "image", re: /!\[([^\]]*)\]\(([^)\s]+)\)/ },
  { kind: "code", re: /`([^`]+)`/ },
  // Inline math: $…$ with currency guards — no space just inside the delimiters
  // and the closer not followed by a digit, so "$5 … $10" / "$100" stay text.
  { kind: "math", re: /\$(?![\s$])((?:\\.|[^$\\\n])+?)(?<!\s)\$(?!\d)/ },
  { kind: "autolinkAngle", re: /<((?:https?:\/\/|mailto:)[^>\s]+)>/ },
  { kind: "link", re: /\[([^\]]+)\]\(([^)\s]+)\)/ },
  { kind: "strike", re: /~~([^~]+)~~/ },
  { kind: "bold", re: /\*\*([^*]+)\*\*|__([^_]+)__/ },
  { kind: "italic", re: /\*([^*\n]+)\*|\b_([^_\n]+)_\b/ },
  { kind: "autolink", re: /(https?:\/\/[^\s<>)\]]+)/ },
];

function renderInline(text: string, key: string): ReactNode[] {
  const out: ReactNode[] = [];
  let rest = text;
  let n = 0;
  while (rest.length > 0) {
    let best: { idx: number; len: number; kind: string; m: RegExpExecArray } | null = null;
    for (const { kind, re } of INLINE) {
      const m = re.exec(rest);
      if (m && (best === null || m.index < best.idx)) best = { idx: m.index, len: m[0].length, kind, m };
    }
    if (!best) {
      out.push(rest);
      break;
    }
    const k = `${key}-${n++}`;
    const { kind, m } = best;
    // Text before the token. For a line break, strip the trailing hard-break
    // marker (2+ spaces or a backslash) so it doesn't render as literal space.
    let before = rest.slice(0, best.idx);
    if (kind === "br") before = before.replace(/[ \t]+$|\\$/, "");
    if (before) out.push(before);

    if (kind === "esc") {
      out.push(m[1]);
    } else if (kind === "br") {
      out.push(<br key={k} />);
    } else if (kind === "image") {
      const src = safeHref(m[2]);
      out.push(src ? <img key={k} className="md-img" src={src} alt={m[1]} loading="lazy" /> : m[1]);
    } else if (kind === "code") {
      out.push(
        <code key={k} className="md-code">
          {m[1]}
        </code>,
      );
    } else if (kind === "math") {
      out.push(
        <span
          key={k}
          className="md-math"
          // KaTeX-generated markup from the LaTeX source (trust:false) — safe; see file header.
          dangerouslySetInnerHTML={{ __html: katex.renderToString(m[1], { throwOnError: false }) }}
        />,
      );
    } else if (kind === "autolinkAngle" || kind === "autolink") {
      let url = m[1];
      let trail = "";
      if (kind === "autolink") {
        const t = /[.,;:!?)\]}'"]+$/.exec(url);
        if (t) {
          trail = t[0];
          url = url.slice(0, -trail.length);
        }
      }
      const href = safeHref(url);
      out.push(
        href ? (
          <a key={k} href={href} target="_blank" rel="noreferrer noopener">
            {url}
          </a>
        ) : (
          url
        ),
      );
      if (trail) out.push(trail);
    } else if (kind === "link") {
      const href = safeHref(m[2]);
      out.push(
        href ? (
          <a key={k} href={href} target="_blank" rel="noreferrer noopener">
            {renderInline(m[1], k)}
          </a>
        ) : (
          renderInline(m[1], k)
        ),
      );
    } else if (kind === "strike") {
      out.push(<del key={k}>{renderInline(m[1], k)}</del>);
    } else if (kind === "bold") {
      out.push(<strong key={k}>{renderInline(m[1] ?? m[2], k)}</strong>);
    } else {
      out.push(<em key={k}>{renderInline(m[1] ?? m[2], k)}</em>);
    }
    rest = rest.slice(best.idx + best.len);
  }
  return out;
}

// A fenced code block: language label + copy affordance over a monospaced pre.
// Exported for DenebUi's <code> node so a card's code carries the same chrome
// as the identical fence in prose.
export function CodeBlock({ lang, text }: { lang: string; text: string }) {
  const [copied, setCopied] = useState(false);
  // Syntax colors: lazy-load highlight.js (common languages) so the base
  // bundle stays lean; only fenced blocks with a KNOWN language get colored —
  // auto-detection on plain text mis-paints too often. hljs escapes its output,
  // so the innerHTML sink is safe.
  // Keyed result instead of a reset-in-effect: stale colors for a previous
  // lang/text pair are simply ignored at render time (no cascading setState).
  const [hl, setHl] = useState<{ key: string; value: string } | null>(null);
  const hlKey = lang + "\u0000" + text;
  useEffect(() => {
    if (!lang) return;
    let cancelled = false;
    void import("highlight.js/lib/common")
      .then(({ default: hljs }) => {
        if (cancelled || !hljs.getLanguage(lang)) return;
        setHl({ key: hlKey, value: hljs.highlight(text, { language: lang, ignoreIllegals: true }).value });
      })
      .catch(() => {});
    return () => {
      cancelled = true;
    };
  }, [hlKey, lang, text]);
  const html = hl && hl.key === hlKey ? hl.value : null;
  async function copy() {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1200);
    } catch {
      /* clipboard blocked — no-op */
    }
  }
  return (
    <div className="md-codeblock">
      <div className="md-codebar">
        {lang ? <span className="md-codelang">{lang}</span> : <span />}
        <button type="button" className="md-copy" onClick={copy} aria-label="코드 복사">
          <Icon name="copy" size={12} />
          {copied ? "복사됨" : "복사"}
        </button>
      </div>
      <pre>
        {html !== null ? (
          <code data-lang={lang || undefined} dangerouslySetInnerHTML={{ __html: html }} />
        ) : (
          <code data-lang={lang || undefined}>{text}</code>
        )}
      </pre>
    </div>
  );
}

function renderItemBody(item: ListItem, key: string): ReactNode {
  // Tight item (single paragraph) renders inline so list rows stay compact;
  // a multi-block item (nested list, multiple paragraphs) renders its blocks.
  if (item.children.length === 1 && item.children[0].type === "para") {
    return renderInline(item.children[0].text, key);
  }
  return item.children.map((b, j) => renderBlock(b, `${key}-${j}`));
}

function renderList(b: Extract<Block, { type: "list" }>, key: string): ReactNode {
  const hasTask = b.items.some((it) => it.task);
  const children = b.items.map((it, j) => {
    const body = renderItemBody(it, `${key}-${j}`);
    return it.task ? (
      <li key={j} className="md-task">
        <input type="checkbox" checked={!!it.checked} disabled readOnly />
        <span>{body}</span>
      </li>
    ) : (
      <li key={j}>{body}</li>
    );
  });
  const cls = hasTask ? "md-tasklist" : undefined;
  return b.ordered ? (
    <ol key={key} className={cls} start={b.start && b.start !== 1 ? b.start : undefined}>
      {children}
    </ol>
  ) : (
    <ul key={key} className={cls}>
      {children}
    </ul>
  );
}

function ChoiceChips({ text, onChoice }: { text: string; onChoice?: (text: string) => void }) {
  const options = text
    .split("\n")
    .map((l) =>
      l
        .trim()
        .replace(/^[-*]\s+/, "")
        .trim(),
    )
    .filter(Boolean)
    .filter((v, i, a) => a.indexOf(v) === i);
  const [customOpen, setCustomOpen] = useState(false);
  const [customText, setCustomText] = useState("");
  if (!options.length) return null;
  const submitCustom = () => {
    const answer = customText.trim();
    if (!answer || !onChoice) return;
    setCustomText("");
    setCustomOpen(false);
    onChoice(answer);
  };
  return (
    <div className="md-choices" role="group" aria-label="선택지">
      {options.map((opt) =>
        onChoice ? (
          <button key={opt} type="button" className="md-choice" onClick={() => onChoice(opt)}>
            {opt}
          </button>
        ) : (
          <span key={opt} className="md-choice md-choice-static">
            {opt}
          </span>
        ),
      )}
      {onChoice ? (
        customOpen ? (
          <span className="md-choice-custom">
            <input
              className="md-choice-input"
              value={customText}
              autoFocus
              placeholder="직접 입력"
              onChange={(e) => setCustomText(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  e.preventDefault();
                  submitCustom();
                }
              }}
            />
            <button type="button" className="md-choice" onClick={submitCustom} disabled={!customText.trim()}>
              전송
            </button>
          </span>
        ) : (
          <button type="button" className="md-choice md-choice-other" onClick={() => setCustomOpen(true)}>
            직접 입력
          </button>
        )
      ) : null}
    </div>
  );
}

function renderBlock(b: Block, key: string, onChoice?: (text: string) => void): ReactNode {
  switch (b.type) {
    case "heading": {
      const Tag = `h${Math.min(b.level + 2, 6)}` as "h3" | "h4" | "h5" | "h6";
      return <Tag key={key}>{renderInline(b.text, key)}</Tag>;
    }
    case "code":
      if (b.lang.trim().toLowerCase() === "choices") {
        return <ChoiceChips key={key} text={b.text} onChoice={onChoice} />;
      }
      return <CodeBlock key={key} lang={b.lang} text={b.text} />;
    case "hr":
      return <hr key={key} />;
    case "quote":
      return <blockquote key={key}>{b.children.map((c, j) => renderBlock(c, `${key}-${j}`, onChoice))}</blockquote>;
    case "list":
      return renderList(b, key);
    case "details":
      return (
        <details key={key} className="md-details" open={b.open || undefined}>
          <summary>{renderInline(b.summary, `${key}-s`)}</summary>
          <div className="md-details-body">{b.children.map((c, j) => renderBlock(c, `${key}-${j}`, onChoice))}</div>
        </details>
      );
    case "mathBlock":
      return (
        <div
          key={key}
          className="md-math-block"
          // KaTeX display-mode markup from the LaTeX source (trust:false) — safe; see file header.
          dangerouslySetInnerHTML={{ __html: katex.renderToString(b.text, { throwOnError: false, displayMode: true }) }}
        />
      );
    case "table":
      return <MdTable key={key} block={b} blockKey={key} />;
    case "para":
      return <p key={key}>{renderInline(b.text, key)}</p>;
  }
}

// Markdown table with auto-numeric columns: models rarely write ':---:'
// alignment markers, so a marker-less column whose every cell starts with a
// digit right-aligns with tabular figures — explicit markers always win
// (native MarkdownTables parity, 2026-07-12 production-corpus lesson).
function MdTable({ block, blockKey }: { block: Extract<Block, { type: "table" }>; blockKey: string }) {
  const numeric = useMemo(
    () =>
      block.header.map((_, j) => {
        if (block.align[j]) return false;
        const cells = block.rows.map((r) => (r[j] ?? "").trim()).filter(Boolean);
        return cells.length > 0 && cells.every((c) => /^[-−]?\d/.test(c.replace(/^[*_~`\s]+/, "")));
      }),
    [block],
  );
  const cellStyle = (j: number): CSSProperties | undefined =>
    block.align[j] ? { textAlign: block.align[j] } : numeric[j] ? { textAlign: "right" } : undefined;
  const cellClass = (j: number): string | undefined => (numeric[j] ? "md-num" : undefined);
  // Dense tables (3+ columns) drop the type one rung so narrow columns fit whole
  // Korean 어절 per line — the native table's dense-mode parity (production lesson).
  // Wide tables (5+ cols, e.g. 발주서) sticky the first column while scrolling.
  const colCount = Math.max(block.header.length, ...block.rows.map((r) => r.length), 0);
  const cls = "md-table" + (colCount >= 3 ? " md-table-dense" : "") + (colCount >= 5 ? " md-table-sticky" : "");
  const colCls = (j: number): string | undefined => {
    const parts = [cellClass(j), j === 0 && colCount >= 5 ? "md-sticky-col" : undefined].filter(Boolean);
    return parts.length ? parts.join(" ") : undefined;
  };
  // Scroll wrapper keeps a real `table` layout so `position: sticky` on the
  // first column works — `display: block` on the table itself breaks sticky.
  return (
    <div className="md-table-scroll">
      <table className={cls}>
        {block.caption ? (
          <caption className="md-table-caption">{renderInline(block.caption, `${blockKey}-cap`)}</caption>
        ) : null}
        <thead>
          <tr>
            {block.header.map((h, j) => (
              <th key={j} className={colCls(j)} style={cellStyle(j)}>
                {renderInline(h, `${blockKey}-h${j}`)}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {block.rows.map((row, r) => (
            <tr key={r}>
              {row.map((c, j) => (
                <td key={j} className={colCls(j)} style={cellStyle(j)}>
                  {renderInline(c, `${blockKey}-${r}-${j}`)}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// Render Markdown text as safe React nodes. Plain text with no Markdown renders
// as a single <p>, so a bare reply stays a clean paragraph. Runs the native-parity
// normalizers (footnotes → HTML blocks → box tables → separator-less pipes) first.
export function Markdown({ text, onChoice }: { text: string; onChoice?: (text: string) => void }) {
  const blocks = useMemo(() => parseBlocks(normalizeMarkdown(text)), [text]);
  return <div className="md">{blocks.map((b, i) => renderBlock(b, `b${i}`, onChoice))}</div>;
}
