// Code generated by scripts/gen-error-codes.sh; DO NOT EDIT.
// Source of truth: proto/gateway.proto
// Regenerate with: make error-codes-gen

package ffi

// FFI return codes — negative i32 values returned by core-rs C ABI functions.
// Positive return values from buffer-writing functions are bytes written, not error codes.
const (
	rcNullPointer    = -1
	rcInvalidUTF8    = -2
	rcOutputTooSmall = -3
	rcInputTooLarge  = -4
	rcJSONError      = -5
	rcOverflow       = -6
	rcValidation     = -7
	rcRustPanic      = -99
)
