// Code generated by data-gen. DO NOT EDIT.
// Source: gateway-go/internal/pipeline/chat/tool_classification.json
// Regenerate: make data-gen

package chat

// dryRunSafeTools are tools whose execution has no side effects on the
// workspace, external systems, or run-visible state beyond their own result,
// so they run for real under tool dry-run (tool_dry_run.go). Default-deny:
// every tool absent from this set is stubbed. Action-multiplexed tools whose
// mutating/read-only split lives in an argument (wiki, calendar, todo, ...)
// stay suppressed entirely.
var dryRunSafeTools = map[string]struct{}{
	"code_search":    {},
	"fetch_tools":    {},
	"grep":           {},
	"read":           {},
	"read_spillover": {},
}

// parallelSafeTools are read-only tools whose same-turn calls may execute
// CONCURRENTLY (executor.go parallel turn path): no workspace/external
// mutation, no cross-call ordering the model could rely on. Default-deny —
// any tool absent here keeps the whole turn sequential, as do calls carrying
// $ref (same-turn result piping). Action-multiplexed tools (wiki, calendar,
// todo, ...) stay out entirely: their mutating/read-only split lives in an
// argument, and fetch_tools stays out because it mutates the run's deferred
// tool activation state. Measured motivation (2026-07-07, 3d of prod
// agent-logs): 23 all-read-only multi-tool turns wasted 124s of wall time on
// serial waits — web+web research turns alone ran 50s+ that parallel
// execution halves.
//
// contacts left this list on 2026-08-29 together with the tool itself: it folded into `people`, which is NOT parallel-safe — its groupware leg enriches and can create 인물 wiki pages, so two same-turn calls could race the same page.
var parallelSafeTools = map[string]struct{}{
	"code_search":    {},
	"grep":           {},
	"mail_archive":   {},
	"polaris":        {},
	"read":           {},
	"read_spillover": {},
	"web":            {},
}

// toolCompressSkipSet contains tools whose output should not be compressed.
// Structured-output tools are already handled by post-processors.
// Internal / already-small tools add no compression value.
var toolCompressSkipSet = map[string]struct{}{
	"blackboard":      {},
	"deal_ledger":     {},
	"grep":            {},
	"notebook":        {},
	"sessions":        {},
	"skill_lifecycle": {},
	"wiki":            {},
}
