// Code generated by data-gen. DO NOT EDIT.
// Source: gateway-go/internal/pipeline/chat/tool_classification.json
// Regenerate: make data-gen

package chat

// channelSilentTools lists tools that suppress chat delivery on specific
// channels. When the agent calls one of these tools, the response is not
// delivered as a chat message — the tool executes normally but the chat
// output is silenced. Only purely internal tools (session management,
// bridge, kv) should be listed here — user-facing tools must respond.
var channelSilentTools = map[string][]string{
	"telegram": []string{"gateway", "message", "sessions_list", "sessions_history", "sessions_search", "sessions_send", "sessions_spawn", "subagents", "kv", "bridge", "skill_manage"},
}

// mutatingTools are tools that change the filesystem or run commands.
// When a run uses these, it likely needs a verification follow-up.
var mutatingTools = map[string]struct{}{
	"edit":          {},
	"exec":          {},
	"git":           {},
	"multi_edit":    {},
	"notebook_edit": {},
	"write":         {},
}

// toolApprovalPolicy classifies tools by their autonomous execution safety.
// "auto": safe for autonomous execution without user confirmation.
// "confirm": requires user confirmation before execution (mutating/external).
// "block": never executed by autonomous agents (dangerous system operations).
// Used by the agent executor to gate tool calls in autonomous contexts
// (cron jobs, subagents, deep work mode).
var toolApprovalPolicy = map[string]string{
	"agent_logs":            "auto",
	"analyze":               "auto",
	"batch_read":            "auto",
	"bridge":                "block",
	"deep_research":         "auto",
	"diff":                  "auto",
	"edit":                  "confirm",
	"exec":                  "confirm",
	"find":                  "auto",
	"gateway_logs":          "auto",
	"git":                   "confirm",
	"grep":                  "auto",
	"health_check":          "auto",
	"image_describe":        "auto",
	"inspect":               "auto",
	"kv":                    "auto",
	"multi_edit":            "confirm",
	"notebook_edit":         "confirm",
	"process":               "auto",
	"projects_get_document": "auto",
	"projects_get_field":    "auto",
	"projects_list":         "auto",
	"projects_search":       "auto",
	"read":                  "auto",
	"read_spillover":        "auto",
	"search_and_read":       "auto",
	"send_file":             "confirm",
	"sessions_list":         "auto",
	"skills_list":           "auto",
	"tree":                  "auto",
	"web_fetch":             "auto",
	"web_search":            "auto",
	"wiki":                  "auto",
	"write":                 "confirm",
}

// toolCompressSkipSet contains tools whose output should not be compressed.
// Structured-output tools are already handled by post-processors.
// Internal / already-small tools add no compression value.
var toolCompressSkipSet = map[string]struct{}{
	"analyze":       {},
	"diff":          {},
	"find":          {},
	"git":           {},
	"grep":          {},
	"kv":            {},
	"sessions_list": {},
	"tree":          {},
	"wiki":          {},
}
