// Code generated by data-gen. DO NOT EDIT.
// Source: gateway-go/internal/pipeline/chat/tool_classification.json
// Regenerate: make data-gen

package chat

// toolCompressSkipSet contains tools whose output should not be compressed.
// Structured-output tools are already handled by post-processors.
// Internal / already-small tools add no compression value.
var toolCompressSkipSet = map[string]struct{}{
	"deal_ledger":     {},
	"grep":            {},
	"notebook":        {},
	"sessions":        {},
	"skill_lifecycle": {},
	"wiki":            {},
}
