// Code generated by model-caps-gen. DO NOT EDIT.
// Source: gateway-go/internal/autoreply/thinking/model_caps.yaml
// Regenerate: make model-caps

package thinking

import "regexp"

// xhighThinkingModelIDs maps normalized provider IDs to model ID lists that
// support xhigh thinking. Matching uses exact equality or prefix.
var xhighThinkingModelIDs = map[string][]string{
	"openai":       {"gpt-5.4", "gpt-5.4-pro", "gpt-5.4-mini", "gpt-5.4-nano", "gpt-5.2"},
	"openai-codex": {"gpt-5.4", "gpt-5.3-codex", "gpt-5.3-codex-spark", "gpt-5.2-codex", "gpt-5.1-codex"},
}

// adaptiveThinkingModelRes maps normalized provider IDs to compiled regexes
// that identify models defaulting to adaptive thinking.
var adaptiveThinkingModelRes = map[string]*regexp.Regexp{
	"amazon-bedrock": regexp.MustCompile(`(?i)claude-(?:opus|sonnet)-4(?:\.|-)6(?:$|[-.])`),
	"anthropic":      regexp.MustCompile(`(?i)^claude-(?:opus|sonnet)-4(?:\.|-)6(?:$|[-.])`),
}
