// Code generated by tool-schema-gen. DO NOT EDIT.
// Source: gateway-go/internal/chat/toolreg/tool_schemas.yaml
// Regenerate: make tool-schemas

package toolreg

func readToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"file_path": map[string]any{
				"type":        "string",
				"description": "The absolute path to the file to read",
			},
			"offset": map[string]any{
				"type":        "number",
				"description": "The line number to start reading from (1-based)",
				"minimum":     1,
			},
			"limit": map[string]any{
				"type":        "number",
				"description": "The number of lines to read (default: 2000)",
				"default":     2000,
				"minimum":     1,
			},
			"function": map[string]any{
				"type":        "string",
				"description": "Read only this function/method/type. For .go files uses AST; for others uses regex. Overrides offset/limit",
			},
			"force": map[string]any{
				"type":        "boolean",
				"description": "Force re-read even if cached (default: false)",
				"default":     false,
			},
		},
		"required": []string{"file_path"},
	}
}

func readSpilloverToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"spill_id": map[string]any{
				"type":        "string",
				"description": "The spillover reference ID (e.g., sp_abc123) from a previous large tool result",
			},
		},
		"required": []string{"spill_id"},
	}
}

func writeToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"file_path": map[string]any{
				"type":        "string",
				"description": "The absolute path to the file to write",
			},
			"content": map[string]any{
				"type":        "string",
				"description": "The content to write to the file",
			},
		},
		"required": []string{"file_path", "content"},
	}
}

func editToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"file_path": map[string]any{
				"type":        "string",
				"description": "The absolute path to the file to modify",
			},
			"old_string": map[string]any{
				"type":        "string",
				"description": "The text to replace (must be unique unless replace_all is true). When regex=true, treated as a regex pattern",
			},
			"new_string": map[string]any{
				"type":        "string",
				"description": "The text to replace it with. When regex=true, supports $1/$2 backreferences",
			},
			"replace_all": map[string]any{
				"type":        "boolean",
				"description": "Replace all occurrences instead of requiring a unique match (default: false)",
				"default":     false,
			},
			"regex": map[string]any{
				"type":        "boolean",
				"description": "Treat old_string as a regex pattern (default: false)",
				"default":     false,
			},
			"line": map[string]any{
				"type":        "number",
				"description": "Replace at a specific line number (1-based). When set, old_string matches only on this line",
				"minimum":     1,
			},
		},
		"required": []string{"file_path", "old_string", "new_string"},
	}
}

func grepToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"pattern": map[string]any{
				"type":        "string",
				"description": "Regular expression pattern to search for",
			},
			"path": map[string]any{
				"type":        "string",
				"description": "File or directory to search in",
			},
			"include": map[string]any{
				"type":        "string",
				"description": "Glob pattern to filter files (e.g. \"*.ts\")",
			},
			"contextLines": map[string]any{
				"type":        "number",
				"description": "Lines of context around each match (0-10)",
				"default":     0,
				"minimum":     0,
				"maximum":     10,
			},
			"before": map[string]any{
				"type":        "number",
				"description": "Lines of context before each match (overrides contextLines for before)",
				"minimum":     0,
				"maximum":     10,
			},
			"after": map[string]any{
				"type":        "number",
				"description": "Lines of context after each match (overrides contextLines for after)",
				"minimum":     0,
				"maximum":     10,
			},
			"ignoreCase": map[string]any{
				"type":        "boolean",
				"description": "Case-insensitive search",
				"default":     false,
			},
			"maxResults": map[string]any{
				"type":        "number",
				"description": "Maximum matches to return",
				"default":     100,
				"minimum":     1,
				"maximum":     500,
			},
			"fileType": map[string]any{
				"type":        "string",
				"description": "File type filter for ripgrep --type (e.g. \"go\", \"py\", \"js\")",
			},
			"multiline": map[string]any{
				"type":        "boolean",
				"description": "Enable multiline matching (patterns can span lines, . matches newlines)",
				"default":     false,
			},
			"mode": map[string]any{
				"type":        "string",
				"description": "Output mode: content (default, matching lines), files_only (file paths only), count (match counts per file)",
				"enum":        []string{"content", "files_only", "count"},
			},
		},
		"required": []string{"pattern"},
	}
}

func findToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"pattern": map[string]any{
				"type":        "string",
				"description": "Glob pattern to match files (supports ** for recursive matching, e.g. \"**/*.go\")",
			},
			"path": map[string]any{
				"type":        "string",
				"description": "Directory to search in",
			},
			"showHidden": map[string]any{
				"type":        "boolean",
				"description": "Include hidden directories (starting with .) in search",
				"default":     false,
			},
		},
		"required": []string{"pattern"},
	}
}

func multiEditToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"edits": map[string]any{
				"type":        "array",
				"description": "List of edits to apply. Each edit targets one file with one search-and-replace",
				"items": map[string]any{
					"type": "object",
					"properties": map[string]any{
						"file_path": map[string]any{
							"type":        "string",
							"description": "Path to the file to edit",
						},
						"old_string": map[string]any{
							"type":        "string",
							"description": "Text to find and replace",
						},
						"new_string": map[string]any{
							"type":        "string",
							"description": "Replacement text",
						},
						"replace_all": map[string]any{
							"type":        "boolean",
							"description": "Replace all occurrences (default: false)",
							"default":     false,
						},
					},
					"required": []string{"file_path", "old_string", "new_string"},
				},
				"minItems": 1,
				"maxItems": 50,
			},
		},
		"required": []string{"edits"},
	}
}

func treeToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"path": map[string]any{
				"type":        "string",
				"description": "Directory to display (defaults to workspace root)",
			},
			"depth": map[string]any{
				"type":        "number",
				"description": "Max directory depth to display (default: 3, max: 6)",
				"default":     3,
				"minimum":     1,
				"maximum":     6,
			},
			"show_hidden": map[string]any{
				"type":        "boolean",
				"description": "Include hidden files/directories (default: false)",
				"default":     false,
			},
			"dirs_only": map[string]any{
				"type":        "boolean",
				"description": "Show only directories, no files (default: false)",
				"default":     false,
			},
			"pattern": map[string]any{
				"type":        "string",
				"description": "Filter: only show entries matching this glob pattern (e.g. \"*.go\")",
			},
		},
	}
}

func diffToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"mode": map[string]any{
				"type":        "string",
				"description": "Diff mode: 'staged' (git diff --cached), 'unstaged' (git diff), 'all' (staged+unstaged vs HEAD), 'commit' (show a commit), 'branch' (compare branches), 'files' (compare two files)",
				"enum":        []string{"staged", "unstaged", "all", "commit", "branch", "files"},
				"default":     "unstaged",
			},
			"path": map[string]any{
				"type":        "string",
				"description": "Limit diff to a specific file or directory path",
			},
			"ref": map[string]any{
				"type":        "string",
				"description": "Git ref for 'commit' mode (e.g. HEAD~1, abc1234), or base ref for 'branch' mode",
			},
			"ref2": map[string]any{
				"type":        "string",
				"description": "Second ref for 'branch' mode (compared against ref). For 'files' mode: second file path",
			},
			"stat_only": map[string]any{
				"type":        "boolean",
				"description": "Show only file-level summary (--stat), not full diff content",
				"default":     false,
			},
			"context_lines": map[string]any{
				"type":        "number",
				"description": "Number of context lines around changes (default: 3)",
				"default":     3,
				"minimum":     0,
				"maximum":     20,
			},
		},
	}
}

func analyzeToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Analysis action",
				"enum":        []string{"outline", "symbols", "references", "imports", "signature"},
			},
			"file": map[string]any{
				"type":        "string",
				"description": "File path for outline/imports/signature analysis",
			},
			"path": map[string]any{
				"type":        "string",
				"description": "Directory path for symbols/references/imports search",
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Symbol name to search for (symbols/references/signature)",
			},
			"kind": map[string]any{
				"type":        "string",
				"description": "Filter symbols by kind",
				"enum":        []string{"func", "type", "method", "const", "var", "interface", "struct"},
			},
			"symbol": map[string]any{
				"type":        "string",
				"description": "Symbol name for references action",
			},
			"reverse": map[string]any{
				"type":        "boolean",
				"description": "For imports: show who imports this package (reverse dependency)",
				"default":     false,
			},
		},
		"required": []string{"action"},
	}
}

func testToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Action to perform",
				"enum":        []string{"run", "build", "check"},
			},
			"framework": map[string]any{
				"type":        "string",
				"description": "Build/test framework",
				"enum":        []string{"go", "cargo", "make"},
				"default":     "go",
			},
			"path": map[string]any{
				"type":        "string",
				"description": "Package path or directory (e.g. './internal/chat/...')",
			},
			"filter": map[string]any{
				"type":        "string",
				"description": "Test name filter (go: -run, cargo: --test)",
			},
			"verbose": map[string]any{
				"type":        "boolean",
				"description": "Verbose output (show all test names)",
				"default":     false,
			},
			"timeout": map[string]any{
				"type":        "number",
				"description": "Timeout in seconds (default: 120, max: 600)",
				"default":     120,
				"minimum":     10,
				"maximum":     600,
			},
			"coverage": map[string]any{
				"type":        "boolean",
				"description": "Enable coverage reporting (go only)",
				"default":     false,
			},
			"target": map[string]any{
				"type":        "string",
				"description": "Build target (make: target name, cargo: --bin/--lib)",
			},
			"release": map[string]any{
				"type":        "boolean",
				"description": "Release build (cargo --release)",
				"default":     false,
			},
		},
		"required": []string{"action"},
	}
}

func gitToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Git action to perform",
				"enum":        []string{"status", "commit", "log", "branch", "stash", "blame", "tag", "merge", "rebase", "cherry_pick", "reset", "remote", "clean"},
			},
			"message": map[string]any{
				"type":        "string",
				"description": "Commit message (commit), stash message (stash push), tag annotation (tag)",
			},
			"files": map[string]any{
				"type": "array",
				"items": map[string]any{
					"type": "string",
				},
				"description": "Files to stage before commit. Empty = commit currently staged files",
			},
			"all": map[string]any{
				"type":        "boolean",
				"description": "Stage all tracked changes before commit (git commit -a)",
				"default":     false,
			},
			"amend": map[string]any{
				"type":        "boolean",
				"description": "Amend the last commit",
				"default":     false,
			},
			"count": map[string]any{
				"type":        "number",
				"description": "Number of log entries (default: 10, max: 50)",
				"default":     10,
				"minimum":     1,
				"maximum":     50,
			},
			"oneline": map[string]any{
				"type":        "boolean",
				"description": "One-line log format",
				"default":     false,
			},
			"author": map[string]any{
				"type":        "string",
				"description": "Filter log by author",
			},
			"since": map[string]any{
				"type":        "string",
				"description": "Filter log since date (e.g. '2024-01-01', '1 week ago')",
			},
			"path": map[string]any{
				"type":        "string",
				"description": "File path for log/blame",
			},
			"grep": map[string]any{
				"type":        "string",
				"description": "Filter log by commit message grep pattern",
			},
			"name": map[string]any{
				"type":        "string",
				"description": "Branch/tag/remote name",
			},
			"delete": map[string]any{
				"type":        "boolean",
				"description": "Delete the named branch/tag",
				"default":     false,
			},
			"switch_to": map[string]any{
				"type":        "boolean",
				"description": "Switch to the named branch",
				"default":     false,
			},
			"create": map[string]any{
				"type":        "boolean",
				"description": "Create a new branch",
				"default":     false,
			},
			"from": map[string]any{
				"type":        "string",
				"description": "Base ref for branch creation",
			},
			"file": map[string]any{
				"type":        "string",
				"description": "File path for blame",
			},
			"start_line": map[string]any{
				"type":        "number",
				"description": "Start line for blame range",
			},
			"end_line": map[string]any{
				"type":        "number",
				"description": "End line for blame range",
			},
			"stash_action": map[string]any{
				"type":        "string",
				"description": "Stash sub-action",
				"enum":        []string{"push", "pop", "list", "drop", "apply"},
			},
			"branch": map[string]any{
				"type":        "string",
				"description": "Branch to merge",
			},
			"no_ff": map[string]any{
				"type":        "boolean",
				"description": "No fast-forward merge",
				"default":     false,
			},
			"abort": map[string]any{
				"type":        "boolean",
				"description": "Abort in-progress merge/rebase/cherry-pick",
				"default":     false,
			},
			"continue_op": map[string]any{
				"type":        "boolean",
				"description": "Continue in-progress rebase/cherry-pick",
				"default":     false,
			},
			"onto": map[string]any{
				"type":        "string",
				"description": "Rebase onto target ref",
			},
			"ref": map[string]any{
				"type":        "string",
				"description": "Git ref for cherry-pick or reset",
			},
			"mode": map[string]any{
				"type":        "string",
				"description": "Reset mode: soft, mixed (default), hard",
				"enum":        []string{"soft", "mixed", "hard"},
			},
			"remote_action": map[string]any{
				"type":        "string",
				"description": "Remote sub-action: list (default), add, remove",
				"enum":        []string{"list", "add", "remove"},
			},
			"url": map[string]any{
				"type":        "string",
				"description": "Remote URL for add",
			},
			"dry_run": map[string]any{
				"type":        "boolean",
				"description": "Show what would be removed without actually removing (clean)",
				"default":     true,
			},
			"directories": map[string]any{
				"type":        "boolean",
				"description": "Also remove untracked directories (clean -d)",
				"default":     false,
			},
			"force": map[string]any{
				"type":        "boolean",
				"description": "Force clean (-f). Required when dry_run is false",
				"default":     false,
			},
			"short": map[string]any{
				"type":        "boolean",
				"description": "Short status format",
				"default":     false,
			},
		},
		"required": []string{"action"},
	}
}

func execToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"command": map[string]any{
				"type":        "string",
				"description": "Shell command to execute",
			},
			"workdir": map[string]any{
				"type":        "string",
				"description": "Working directory (defaults to workspace root)",
			},
			"timeout": map[string]any{
				"type":        "number",
				"description": "Timeout in seconds (default: 60, max: 600)",
				"default":     60,
				"minimum":     1,
				"maximum":     600,
			},
			"background": map[string]any{
				"type":        "boolean",
				"description": "Run in background immediately, then use process tool to check output",
				"default":     false,
			},
			"structured": map[string]any{
				"type":        "boolean",
				"description": "Return JSON with stdout, stderr, exit_code, runtime_ms instead of plain text",
				"default":     false,
			},
			"env": map[string]any{
				"type":        "object",
				"description": "Environment variables to set for this command (key-value pairs). Blocked keys (API keys, secrets) are filtered.",
				"additionalProperties": map[string]any{
					"type": "string",
				},
			},
		},
		"required": []string{"command"},
	}
}

func processToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Process action",
				"enum":        []string{"list", "poll", "log", "write", "kill"},
			},
			"sessionId": map[string]any{
				"type":        "string",
				"description": "Session ID for actions other than list",
			},
			"input": map[string]any{
				"type":        "string",
				"description": "Data to write to process stdin (required for write action)",
			},
			"timeout": map[string]any{
				"type":        "number",
				"description": "Poll timeout in milliseconds",
			},
		},
		"required": []string{"action"},
	}
}

func webToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"url": map[string]any{
				"type":        "string",
				"description": "URL to fetch and extract content from",
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Web search query (uses Brave Search or DuckDuckGo)",
			},
			"fetch": map[string]any{
				"type":        "number",
				"description": "When used with query: auto-fetch top N search results (1-3, default: 0 = search only)",
			},
			"maxChars": map[string]any{
				"type":        "number",
				"description": "Maximum content characters per result (default: 50000)",
			},
			"count": map[string]any{
				"type":        "number",
				"description": "Number of search results (default: 5)",
			},
		},
	}
}

func httpToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"url": map[string]any{
				"type":        "string",
				"description": "HTTP or HTTPS URL",
			},
			"method": map[string]any{
				"type":        "string",
				"description": "HTTP method",
				"enum":        []string{"GET", "POST", "PUT", "PATCH", "DELETE"},
				"default":     "GET",
			},
			"headers": map[string]any{
				"type":                 "object",
				"description":          "Request headers as key-value pairs",
				"additionalProperties": true,
			},
			"body": map[string]any{
				"type":        "string",
				"description": "Request body as string",
			},
			"json": map[string]any{
				"type":                 "object",
				"description":          "JSON body (auto-sets Content-Type: application/json)",
				"additionalProperties": true,
			},
			"timeout": map[string]any{
				"type":        "number",
				"description": "Timeout in seconds",
				"default":     30,
				"minimum":     1,
				"maximum":     120,
			},
			"max_response_chars": map[string]any{
				"type":        "number",
				"description": "Maximum response characters to return",
				"default":     50000,
			},
		},
		"required": []string{"url"},
	}
}

func memoryToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"enum":        []string{"search", "get", "set", "forget", "recall", "status", "browse", "log", "daily"},
				"description": "Action: search (hybrid FTS+vector search), get (fetch fact by ID), set (create fact), forget (deactivate fact), recall (deep recall with entity expansion and relation chains), status (memory stats + top fact previews), browse (list/explore facts by category with pagination and sorting), log (append detailed narrative entry to diary file — memory/diary/diary-YYYY-MM-DD.md), daily (read recent diary entries)",
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Search query (for search), fact content (for set), or diary entry body (for log)",
			},
			"fact_id": map[string]any{
				"type":        "integer",
				"description": "Fact ID (for get/forget actions)",
			},
			"category": map[string]any{
				"type":        "string",
				"enum":        []string{"decision", "preference", "solution", "context", "user_model", "mutual"},
				"description": "Category filter (search/browse) or category assignment (set)",
			},
			"importance": map[string]any{
				"type":        "number",
				"description": "Importance score 0.0-1.0 (for set action, default: 0.5)",
				"minimum":     0,
				"maximum":     1,
			},
			"limit": map[string]any{
				"type":        "integer",
				"description": "Max results to return (search: default 10, browse: default 20)",
				"minimum":     1,
				"maximum":     50,
			},
			"sort": map[string]any{
				"type":        "string",
				"enum":        []string{"importance", "recent", "created"},
				"description": "Sort order for browse action: importance (default), recent (updated_at desc), created (created_at desc)",
			},
			"offset": map[string]any{
				"type":        "integer",
				"description": "Pagination offset for browse action (default: 0)",
				"minimum":     0,
			},
			"title": map[string]any{
				"type":        "string",
				"description": "Short heading for a diary entry (log action). Optional — omit for untitled entries",
			},
			"days": map[string]any{
				"type":        "integer",
				"description": "How many days of diary to read (daily action, default: 2 = today + yesterday, max: 7)",
				"minimum":     1,
				"maximum":     7,
			},
		},
		"required": []string{"action"},
	}
}

func healthCheckToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"component": map[string]any{
				"type":        "string",
				"enum":        []string{"all", "embedding", "reranker", "sglang", "memory"},
				"description": "Component to check (default: all). embedding=Gemini API, reranker=Jina API, sglang=local LLM, memory=aurora-memory DB",
			},
		},
	}
}

func cronToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Cron action",
				"enum":        []string{"status", "list", "add", "update", "remove", "run", "wake"},
			},
			"jobId": map[string]any{
				"type":        "string",
				"description": "Job ID for update/remove/run actions",
			},
			"job": map[string]any{
				"type":                 "object",
				"description":          "Job definition for add/update",
				"additionalProperties": true,
			},
			"text": map[string]any{
				"type":        "string",
				"description": "System event text for wake action",
			},
		},
		"required": []string{"action"},
	}
}

func messageToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Message action",
				"enum":        []string{"send", "react", "reply", "thread-reply"},
			},
			"message": map[string]any{
				"type":        "string",
				"description": "Text content to send",
			},
			"to": map[string]any{
				"type":        "string",
				"description": "Recipient (chat ID or user identifier)",
			},
			"channel": map[string]any{
				"type":        "string",
				"description": "Target channel (e.g., telegram)",
			},
			"replyTo": map[string]any{
				"type":        "string",
				"description": "Message ID to reply to",
			},
			"emoji": map[string]any{
				"type":        "string",
				"description": "Emoji for react action",
			},
			"messageId": map[string]any{
				"type":        "string",
				"description": "Message ID for react/reply actions",
			},
			"silent": map[string]any{
				"type":        "boolean",
				"description": "Send without notification sound",
			},
		},
		"required": []string{"action"},
	}
}

func gatewayToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Gateway action",
				"enum":        []string{"restart", "config.get", "config.schema.lookup", "config.apply", "config.patch", "update.run"},
			},
			"path": map[string]any{
				"type":        "string",
				"description": "Config path for schema.lookup",
			},
			"raw": map[string]any{
				"type":        "string",
				"description": "Raw config JSON for apply/patch",
			},
			"reason": map[string]any{
				"type":        "string",
				"description": "Reason for restart",
			},
		},
		"required": []string{"action"},
	}
}

func githubWebhookToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"enum":        []string{"setup", "list", "delete", "status"},
				"description": "setup: register webhook on a GitHub repo; list: show webhooks; delete: remove by ID; status: show Deneb endpoint config",
			},
			"repo": map[string]any{
				"type":        "string",
				"description": "GitHub repo in owner/name format (e.g. choiceoh/Deneb). Required for setup/list/delete.",
			},
			"events": map[string]any{
				"type": "array",
				"items": map[string]any{
					"type": "string",
				},
				"description": "GitHub event types to subscribe to (setup only). Default: [push, pull_request, issues, issue_comment, pull_request_review, create, delete, workflow_run]",
			},
			"webhook_id": map[string]any{
				"type":        "number",
				"description": "Webhook ID to delete (delete only)",
			},
			"gateway_url": map[string]any{
				"type":        "string",
				"description": "Override the Deneb gateway base URL (setup only). Normally auto-detected.",
			},
		},
		"required": []string{"action"},
	}
}

func sessionsListToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"limit": map[string]any{
				"type":        "number",
				"description": "Maximum sessions to return",
				"default":     50,
				"minimum":     1,
			},
			"kinds": map[string]any{
				"type": "array",
				"items": map[string]any{
					"type": "string",
					"enum": []string{"main", "group", "cron", "hook"},
				},
				"description": "Filter by session kind",
			},
		},
	}
}

func sessionsHistoryToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"sessionKey": map[string]any{
				"type":        "string",
				"description": "Session key to fetch history for",
			},
			"limit": map[string]any{
				"type":        "number",
				"description": "Number of messages to return",
				"default":     20,
				"minimum":     1,
			},
		},
		"required": []string{"sessionKey"},
	}
}

func sessionsSearchToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"query": map[string]any{
				"type":        "string",
				"description": "Search keyword to find in session transcripts",
			},
			"maxResults": map[string]any{
				"type":        "number",
				"description": "Maximum number of matching messages to return (default 20)",
				"default":     20,
				"minimum":     1,
				"maximum":     100,
			},
		},
		"required": []string{"query"},
	}
}

func sessionsSendToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"sessionKey": map[string]any{
				"type":        "string",
				"description": "Target session key",
			},
			"message": map[string]any{
				"type":        "string",
				"description": "Message to send",
			},
		},
		"required": []string{"message"},
	}
}

func sessionsSpawnToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"task": map[string]any{
				"type":        "string",
				"description": "Task description for the sub-agent",
			},
			"label": map[string]any{
				"type":        "string",
				"description": "Human-readable label",
			},
			"model": map[string]any{
				"type":        "string",
				"enum":        []string{"main", "lightweight", "fallback"},
				"description": "Model role to use (default: main)",
			},
			"tool_preset": map[string]any{
				"type":        "string",
				"enum":        []string{"researcher", "implementer", "verifier"},
				"description": "Tool preset restricting which tools the sub-agent can use. researcher=read-only, implementer=read+write+build, verifier=read+test+exec",
			},
		},
		"required": []string{"task"},
	}
}

func subagentsToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Sub-agent management action",
				"enum":        []string{"list", "kill", "steer"},
			},
			"target": map[string]any{
				"type":        "string",
				"description": "Target sub-agent ID or label",
			},
			"message": map[string]any{
				"type":        "string",
				"description": "Steering message for steer action",
			},
		},
	}
}

func imageToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"prompt": map[string]any{
				"type":        "string",
				"description": "What to analyze in the image(s)",
			},
			"image": map[string]any{
				"type":        "string",
				"description": "Single image path or URL",
			},
			"images": map[string]any{
				"type": "array",
				"items": map[string]any{
					"type": "string",
				},
				"description": "Multiple image paths or URLs (up to 20)",
			},
			"model": map[string]any{
				"type":        "string",
				"enum":        []string{"main", "lightweight", "fallback"},
				"description": "Model role to use (default: lightweight)",
			},
		},
	}
}

func youtubeTranscriptToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"url": map[string]any{
				"type":        "string",
				"description": "YouTube video URL (youtube.com/watch?v=... or youtu.be/...)",
			},
		},
		"required": []string{"url"},
	}
}

func sendFileToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"file_path": map[string]any{
				"type":        "string",
				"description": "Path to the file to send",
			},
			"type": map[string]any{
				"type":        "string",
				"description": "Media type. Auto-detected from MIME if omitted",
				"enum":        []string{"photo", "document", "video", "audio", "voice"},
			},
			"caption": map[string]any{
				"type":        "string",
				"description": "Caption text (optional)",
			},
			"silent": map[string]any{
				"type":        "boolean",
				"description": "Send without notification sound",
			},
		},
		"required": []string{"file_path"},
	}
}

func kvToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "KV store action",
				"enum":        []string{"get", "set", "delete", "list"},
			},
			"key": map[string]any{
				"type":        "string",
				"description": "Key name (dot-separated for namespaces, e.g., 'prefs.timezone')",
			},
			"value": map[string]any{
				"type":        "string",
				"description": "Value to store (for set action)",
			},
			"prefix": map[string]any{
				"type":        "string",
				"description": "Key prefix filter (for list action)",
			},
		},
		"required": []string{"action"},
	}
}

func gmailToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"description": "Gmail action to perform",
				"enum":        []string{"inbox", "search", "read", "send", "reply", "label", "analyze"},
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Gmail search query (supports Gmail operators like from:, to:, subject:, newer_than:, is:unread, has:attachment, etc.)",
			},
			"message_id": map[string]any{
				"type":        "string",
				"description": "Email message or thread ID (for read, reply, label actions)",
			},
			"to": map[string]any{
				"type":        "string",
				"description": "Recipient email or contact alias (auto-resolved from KV store gmail.contacts.<alias>)",
			},
			"cc": map[string]any{
				"type":        "string",
				"description": "CC recipient(s), comma-separated",
			},
			"bcc": map[string]any{
				"type":        "string",
				"description": "BCC recipient(s), comma-separated",
			},
			"subject": map[string]any{
				"type":        "string",
				"description": "Email subject line",
			},
			"body": map[string]any{
				"type":        "string",
				"description": "Email body text (plain text or HTML if html=true)",
			},
			"html": map[string]any{
				"type":        "boolean",
				"description": "Send body as HTML (default: false)",
				"default":     false,
			},
			"max": map[string]any{
				"type":        "number",
				"description": "Maximum results (for inbox/search, default: 10, max: 50)",
				"default":     10,
				"minimum":     1,
				"maximum":     50,
			},
			"timeout": map[string]any{
				"type":        "number",
				"description": "Timeout in seconds (default: 30, max: 60)",
				"default":     30,
				"minimum":     1,
				"maximum":     60,
			},
			"label_action": map[string]any{
				"type":        "string",
				"description": "Label sub-action (for label action)",
				"enum":        []string{"list", "add", "remove"},
			},
			"label_name": map[string]any{
				"type":        "string",
				"description": "Label name (for label add/remove)",
			},
		},
		"required": []string{"action"},
	}
}

func agentLogsToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"run_id": map[string]any{
				"type":        "string",
				"description": "특정 런 ID로 필터 (생략 시 전체)",
			},
			"type": map[string]any{
				"type":        "string",
				"description": "로그 타입 필터: run.start, run.prep, turn.llm, turn.tool, run.end, run.error",
				"enum":        []string{"run.start", "run.prep", "turn.llm", "turn.tool", "run.end", "run.error"},
			},
			"limit": map[string]any{
				"type":        "integer",
				"description": "최대 반환 수 (기본 50, 최대 500)",
				"default":     50,
				"minimum":     1,
				"maximum":     500,
			},
		},
	}
}

func gatewayLogsToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"lines": map[string]any{
				"type":        "integer",
				"description": "최근 N줄 반환 (기본 100, 최대 500)",
				"default":     100,
				"minimum":     1,
				"maximum":     500,
			},
			"level": map[string]any{
				"type":        "string",
				"description": "로그 레벨 필터: error, warn, info, debug (해당 레벨 이상만 표시)",
				"enum":        []string{"error", "warn", "info", "debug"},
			},
			"pattern": map[string]any{
				"type":        "string",
				"description": "정규식 패턴 필터 (매칭되는 줄만 표시)",
			},
			"pkg": map[string]any{
				"type":        "string",
				"description": "패키지 필터 (예: server, chat, telegram, rpc)",
			},
		},
	}
}

func batchReadToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"files": map[string]any{
				"type":        "array",
				"description": "List of files to read (up to 20). Each entry supports the same options as the read tool",
				"items": map[string]any{
					"type": "object",
					"properties": map[string]any{
						"file_path": map[string]any{
							"type":        "string",
							"description": "Absolute path to the file",
						},
						"offset": map[string]any{
							"type":        "number",
							"description": "Line number to start from (1-based)",
							"minimum":     1,
						},
						"limit": map[string]any{
							"type":        "number",
							"description": "Number of lines to read (default: 2000)",
							"minimum":     1,
						},
						"function": map[string]any{
							"type":        "string",
							"description": "Read only this function/method/type",
						},
					},
					"required": []string{"file_path"},
				},
				"minItems": 1,
				"maxItems": 40,
			},
		},
		"required": []string{"files"},
	}
}

func searchAndReadToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"pattern": map[string]any{
				"type":        "string",
				"description": "Regex pattern to search for (same as grep)",
			},
			"path": map[string]any{
				"type":        "string",
				"description": "Directory to search in",
			},
			"include": map[string]any{
				"type":        "string",
				"description": "Glob pattern to filter files (e.g. \"*.go\")",
			},
			"fileType": map[string]any{
				"type":        "string",
				"description": "File type filter for ripgrep --type (e.g. \"go\", \"py\")",
			},
			"context_lines": map[string]any{
				"type":        "number",
				"description": "Lines of context around each match in the file read (default: 10)",
				"default":     10,
				"minimum":     0,
				"maximum":     50,
			},
			"max_files": map[string]any{
				"type":        "number",
				"description": "Maximum number of matching files to read (default: 5)",
				"default":     5,
				"minimum":     1,
				"maximum":     20,
			},
		},
		"required": []string{"pattern"},
	}
}

func inspectToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"file": map[string]any{
				"type":        "string",
				"description": "File path to inspect",
			},
			"symbol": map[string]any{
				"type":        "string",
				"description": "Specific symbol to inspect (function, type, method name). Enables symbol-level depth automatically",
			},
			"depth": map[string]any{
				"type":        "string",
				"description": "Inspection depth: shallow (outline+imports), deep (+git log+stats), symbol (+references+blame)",
				"enum":        []string{"shallow", "deep", "symbol"},
				"default":     "shallow",
			},
		},
		"required": []string{"file"},
	}
}

func applyPatchToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"patch": map[string]any{
				"type":        "string",
				"description": "Unified diff content (output of git diff, diff -u, etc.)",
			},
			"strip": map[string]any{
				"type":        "number",
				"description": "Strip leading path components (like git apply -pN, default: 1)",
				"default":     1,
			},
			"dry_run": map[string]any{
				"type":        "boolean",
				"description": "Check if patch applies cleanly without modifying files (default: false)",
				"default":     false,
			},
		},
		"required": []string{"patch"},
	}
}

func pilotToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"task": map[string]any{
				"type":        "string",
				"description": "What to do — free-form instruction",
			},
			"sources": map[string]any{
				"type": "array",
				"items": map[string]any{
					"type": "object",
					"properties": map[string]any{
						"tool": map[string]any{
							"type":        "string",
							"description": "Tool name from the registry (read, exec, grep, find, web_fetch, ls, http, etc.)",
						},
						"input": map[string]any{
							"type":                 "object",
							"description":          "Tool input parameters (same schema as calling the tool directly)",
							"additionalProperties": true,
						},
						"label": map[string]any{
							"type":        "string",
							"description": "Label for this source in the analysis (auto-generated if omitted)",
						},
						"only_if": map[string]any{
							"type":        "string",
							"description": "Only execute if the source with this label succeeded (non-empty, no error)",
						},
						"skip_if": map[string]any{
							"type":        "string",
							"description": "Skip this source if the source with this label succeeded",
						},
					},
					"required": []string{"tool", "input"},
				},
				"description": "Tool calls to execute before analysis. Supports conditional execution via only_if/skip_if",
			},
			"content": map[string]any{
				"type":        "string",
				"description": "Direct text/code input (no tool call needed)",
			},
			"items": map[string]any{
				"type": "array",
				"items": map[string]any{
					"type": "string",
				},
				"description": "Multiple items to process in batch",
			},
			"file": map[string]any{
				"type":        "string",
				"description": "Shortcut: read this file (expands to sources:[{tool:'read', input:{file_path:...}}])",
			},
			"files": map[string]any{
				"type": "array",
				"items": map[string]any{
					"type": "string",
				},
				"description": "Shortcut: read multiple files",
			},
			"exec": map[string]any{
				"type":        "string",
				"description": "Shortcut: run this command (expands to sources:[{tool:'exec', input:{command:...}}])",
			},
			"grep": map[string]any{
				"type":        "string",
				"description": "Shortcut: grep for this pattern (use with 'path')",
			},
			"find": map[string]any{
				"type":        "string",
				"description": "Shortcut: find files matching this pattern (use with 'path')",
			},
			"path": map[string]any{
				"type":        "string",
				"description": "Path for grep/find shortcut",
			},
			"url": map[string]any{
				"type":        "string",
				"description": "Shortcut: fetch this URL (expands to sources:[{tool:'web_fetch', input:{url:...}}])",
			},
			"http": map[string]any{
				"type":        "string",
				"description": "Shortcut: GET this URL via http tool (expands to sources:[{tool:'http', input:{url:..., method:'GET'}}])",
			},
			"diff": map[string]any{
				"type":        "string",
				"description": "Shortcut: review code changes. Values: 'all' (uncommitted), 'staged', 'unstaged', or a commit hash (expands to sources:[{tool:'diff', input:{action:...}}])",
			},
			"test": map[string]any{
				"type":        "string",
				"description": "Shortcut: run tests and analyze results. Value: package path (e.g. 'gateway-go/...', './internal/chat/...') or 'all' (expands to sources:[{tool:'test', input:{action:'run', path:...}}])",
			},
			"tree": map[string]any{
				"type":        "string",
				"description": "Shortcut: show directory tree structure. Value: directory path (expands to sources:[{tool:'tree', input:{path:..., depth:3}}])",
			},
			"git_log": map[string]any{
				"type":        "string",
				"description": "Shortcut: show recent commit history. Values: 'recent' (last 20), a number (e.g. '10'), or 'oneline' (compact format) (expands to sources:[{tool:'git', input:{action:'log', ...}}])",
			},
			"health": map[string]any{
				"type":        "boolean",
				"description": "Shortcut: run infrastructure health check (expands to sources:[{tool:'health_check', input:{}}])",
			},
			"kv_key": map[string]any{
				"type":        "string",
				"description": "Shortcut: get this key from KV store (expands to sources:[{tool:'kv', input:{action:'get', key:...}}])",
			},
			"memory": map[string]any{
				"type":        "string",
				"description": "Shortcut: search memory for this query (expands to sources:[{tool:'memory', input:{action:'search', query:...}}])",
			},
			"gmail": map[string]any{
				"type":        "string",
				"description": "Shortcut: search Gmail for this query (expands to sources:[{tool:'gmail', input:{action:'search', query:...}}])",
			},
			"youtube": map[string]any{
				"type":        "string",
				"description": "Shortcut: get YouTube transcript (expands to sources:[{tool:'youtube_transcript', input:{url:...}}])",
			},
			"image": map[string]any{
				"type":        "string",
				"description": "Shortcut: analyze image file or URL (expands to sources:[{tool:'image', input:{paths:[...]}}])",
			},
			"agent_logs": map[string]any{
				"type":        "string",
				"description": "Shortcut: query agent run logs for diagnostics (expands to sources:[{tool:'agent_logs', input:{...}}]). Value: 'all' for recent logs, 'tools' for tool calls only, 'errors' for errors only, or a specific run_id",
			},
			"gateway_logs": map[string]any{
				"type":        "string",
				"description": "Shortcut: query gateway process logs (expands to sources:[{tool:'gateway_logs', input:{...}}]). Value: 'all' for recent 100 lines, 'errors' for ERR only, 'warnings' for WRN+ERR, or a package name (e.g. 'chat', 'server', 'telegram') to filter by package",
			},
			"post_process": map[string]any{
				"type": "array",
				"items": map[string]any{
					"type": "object",
					"properties": map[string]any{
						"action": map[string]any{
							"type":        "string",
							"description": "Post-processing action to apply to gathered source data before LLM analysis",
							"enum":        []string{"filter_lines", "head", "tail", "unique", "sort"},
						},
						"param": map[string]any{
							"type":        "string",
							"description": "Action parameter: regex for filter_lines, line count for head/tail",
						},
					},
					"required": []string{"action"},
				},
				"description": "Post-processing steps applied to gathered data before LLM analysis",
			},
			"output_format": map[string]any{
				"type":        "string",
				"enum":        []string{"text", "json", "list"},
				"description": "Desired output format (default: text)",
			},
			"max_length": map[string]any{
				"type":        "string",
				"enum":        []string{"brief", "normal", "detailed"},
				"description": "Output length hint: brief (~500 chars, fits Telegram), normal (default), detailed (thorough analysis)",
			},
			"chain": map[string]any{
				"type":        "boolean",
				"description": "If true, pilot may request one follow-up round of tool calls based on initial analysis (e.g., read files found by grep)",
			},
		},
		"required": []string{"task"},
	}
}

func morningLetterToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
	}
}

func autoresearchToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"action": map[string]any{
				"type":        "string",
				"enum":        []string{"init", "start", "stop", "status", "results", "apply_overrides"},
				"description": "init: configure experiment, start: begin autonomous loop, stop: halt loop, status: check progress, results: get log, apply_overrides: bake best-found constant overrides into source files",
			},
			"workdir": map[string]any{
				"type":        "string",
				"description": "Experiment workspace directory (absolute path)",
			},
			"target_files": map[string]any{
				"type": "array",
				"items": map[string]any{
					"type": "string",
				},
				"description": "Files the agent may edit, relative to workdir (init only)",
			},
			"metric_cmd": map[string]any{
				"type":        "string",
				"description": "Shell command to run experiment and print metric value on last line (init only)",
			},
			"metric_name": map[string]any{
				"type":        "string",
				"description": "Human-readable metric name, e.g. val_bpb, test_pass_rate (init only)",
			},
			"metric_direction": map[string]any{
				"type":        "string",
				"enum":        []string{"minimize", "maximize"},
				"description": "Whether to minimize or maximize the metric (init only)",
			},
			"time_budget_sec": map[string]any{
				"type":        "number",
				"description": "Fixed time budget per experiment in seconds (init only, default: 300)",
				"default":     300,
				"minimum":     10,
			},
			"branch_tag": map[string]any{
				"type":        "string",
				"description": "Tag for the experiment branch autoresearch/<tag> (init only)",
			},
			"model": map[string]any{
				"type":        "string",
				"description": "LLM model for hypothesis generation (init only, default: claude-sonnet-4-20250514)",
			},
			"metric_pattern": map[string]any{
				"type":        "string",
				"description": "Regex with one capture group to extract the metric value from experiment output (init only). Example: 'val_bpb:\\s*([\\d.]+)' extracts 1.087 from 'val_bpb: 1.087'. If omitted, uses default heuristic (last number on last stdout line).",
			},
			"max_iterations": map[string]any{
				"type":        "number",
				"description": "Max iterations before auto-stop and sending completion report (init only, default: 30). Set -1 for unlimited.",
				"default":     30,
				"minimum":     -1,
			},
			"cache_enabled": map[string]any{
				"type":        "boolean",
				"description": "Enable persistent cache directory for experiment commands (init only). When true, sets AUTORESEARCH_CACHE_DIR env var so expensive operations (LLM inference, embeddings) can cache results across iterations.",
				"default":     false,
			},
			"format": map[string]any{
				"type":        "string",
				"enum":        []string{"tsv", "summary", "chart"},
				"description": "Output format for results action. chart generates a PNG graph of metric progression (default: summary)",
				"default":     "summary",
			},
			"constants": map[string]any{
				"type":        "array",
				"description": "Constants to optimize in override mode (init only). When set, the agent proposes override values instead of rewriting files.",
				"items": map[string]any{
					"type": "object",
					"properties": map[string]any{
						"name": map[string]any{
							"type":        "string",
							"description": "Constant identifier (e.g. LEARNING_RATE)",
						},
						"file": map[string]any{
							"type":        "string",
							"description": "File containing the constant (relative to workdir)",
						},
						"pattern": map[string]any{
							"type":        "string",
							"description": "Regex with one capture group for the value (e.g. 'lr\\s*=\\s*([\\d.]+)')",
						},
						"type": map[string]any{
							"type":        "string",
							"enum":        []string{"float", "int", "string"},
							"description": "Value type",
						},
						"min": map[string]any{
							"type":        "number",
							"description": "Optional lower bound (float/int only)",
						},
						"max": map[string]any{
							"type":        "number",
							"description": "Optional upper bound (float/int only)",
						},
					},
					"required": []string{"name", "file", "pattern", "type"},
				},
			},
		},
		"required": []string{"action", "workdir"},
	}
}

func continueRunToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"reason": map[string]any{
				"type":        "string",
				"description": "Brief description of remaining work for the next continuation run",
			},
			"progress_summary": map[string]any{
				"type":        "string",
				"description": "Summary of what was accomplished in this run (sent to user as progress report)",
			},
		},
		"required": []string{"reason", "progress_summary"},
	}
}

func fetchToolsToolSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"names": map[string]any{
				"type":        "array",
				"description": "Exact tool names to activate (from the deferred tools list)",
				"items": map[string]any{
					"type": "string",
				},
				"minItems": 1,
				"maxItems": 10,
			},
			"query": map[string]any{
				"type":        "string",
				"description": "Keyword search to find matching deferred tools (alternative to names)",
			},
		},
	}
}
