// Code generated by data-gen. DO NOT EDIT.
// Source: gateway-go/internal/process/env_blocklist.yaml
// Regenerate: make data-gen

package process

// blockedEnvKeys lists environment variable names that must be stripped
// from subprocess environments.
var blockedEnvKeys = map[string]bool{
	"LD_PRELOAD":           true,
	"LD_LIBRARY_PATH":      true,
	"BASH_ENV":             true,
	"ENV":                  true,
	"ZDOTDIR":              true,
	"MAVEN_OPTS":           true,
	"SBT_OPTS":             true,
	"GRADLE_OPTS":          true,
	"_JAVA_OPTIONS":        true,
	"JAVA_TOOL_OPTIONS":    true,
	"PYTHONSTARTUP":        true,
	"PERL5OPT":             true,
	"RUBYOPT":              true,
	"DOTNET_STARTUP_HOOKS": true,
	"DOTNET_ROOT":          true,
	"GLIBC_TUNABLES":       true,
}

// blockedEnvPrefixes lists environment variable prefixes that should be blocked.
var blockedEnvPrefixes = []string{
	"DYLD_",
	"LD_AUDIT",
}
