// dreamer_guards.go — apply-stage structural guards for dream-cycle updates.
//
// The synthesis prompt states the project layout rules, but a model can (and
// does) violate them; prompts are advisory, the apply pass is enforcement.
// Both guards below were minted from the first successful post-dsv4 dream
// cycle (2026-07-03): the model appended a "## 진행 로그" section to a 대표페이지
// (로그.md's slot) and created a date-titled daily mail digest page that would
// re-spawn every day.
package wiki

import (
	"path/filepath"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"
)

// progressLogHeadingRe matches a 진행 로그 section heading (H2–H4) on its own
// line, tolerating spacing variants the model emits. The captured # run
// determines which later heading closes the section.
var progressLogHeadingRe = regexp.MustCompile(`(?m)^(#{2,4})\s*진행\s*로그\s*$`)

// nextHeadingRe finds candidate headings that may end a captured section.
var nextHeadingRe = regexp.MustCompile(`(?m)^(#{1,4})\s`)

// splitProgressLogSection cuts a "진행 로그" section out of content proposed
// for a 대표페이지, returning the remaining body and the section's lines
// (without its heading). ("", content unchanged) when no such section exists.
// The section ends at the next heading of the SAME OR SHALLOWER level — a
// deeper heading (### 2026-07-03 under ## 진행 로그) is the section's own
// content, a common shape that used to terminate the capture early and leave
// the log on the 대표페이지. Progress events belong in the project's 로그.md
// slot (wiki-layout 불변식); the caller reroutes the extracted lines there.
func splitProgressLogSection(content string) (body, logLines string) {
	m := progressLogHeadingRe.FindStringSubmatchIndex(content)
	if m == nil {
		return content, ""
	}
	level := m[3] - m[2] // length of the heading's # run
	rest := content[m[1]:]
	for _, h := range nextHeadingRe.FindAllStringSubmatchIndex(rest, -1) {
		if h[3]-h[2] <= level {
			return strings.TrimSpace(content[:m[0]] + rest[h[0]:]), strings.TrimSpace(rest[:h[0]])
		}
	}
	return strings.TrimSpace(content[:m[0]]), strings.TrimSpace(rest)
}

// appendProjectLog appends a dated H2 section to the project's 로그.md,
// creating the page on first use. H2 is the unit RotateProjectLog rotates on,
// so rerouted entries age out with the rest of the log. Returns whether the
// entry was persisted — on failure the caller must keep the section in its
// original page (dropping it there too would silently lose the events).
func (wd *WikiDreamer) appendProjectLog(project, entry string) bool {
	if strings.TrimSpace(entry) == "" {
		return false
	}
	today := time.Now().Format("2006-01-02")
	section := "## " + today + " (dream)\n" + strings.TrimSpace(entry) + "\n"
	err := wd.store.UpdatePage(LogPagePath(project), func(cur *Page) (*Page, error) {
		if cur == nil {
			p := NewPage(project+" 진행 로그", "프로젝트", nil)
			p.Meta.Type = "log"
			p.Meta.Summary = project + " 진행 로그"
			p.Body = section
			return p, nil
		}
		cur.Body = strings.TrimRight(cur.Body, "\n") + "\n\n" + section
		cur.Meta.Updated = today // the store does not auto-stamp writes
		return cur, nil
	})
	if err != nil {
		if wd.logger != nil {
			wd.logger.Warn("wiki-dream: project log reroute failed", "project", project, "error", err)
		}
		return false
	}
	return true
}

// digestDateRe matches the date stamps daily-digest titles carry.
var digestDateRe = regexp.MustCompile(`\d{4}[-./]\d{1,2}[-./]\d{1,2}|\d{1,2}\s*/\s*\d{1,2}`)

// isDailyMailDigestPage reports whether a proposed page is a date-titled daily
// mail digest ("daily mail analysis", "2026-07-02 일일 메일 분석", …). These
// re-spawn every day, duplicate facts the same batch already distributes onto
// per-project pages, and mail-analysis pages are system-generated by contract
// — the dreamer must neither create nor grow them. The path check uses only
// the file base, so legitimate system pages under 메일분석/ directories (whose
// base is a message ID) never match.
func isDailyMailDigestPage(title, path string) bool {
	t := strings.ToLower(title + " " + strings.TrimSuffix(filepath.Base(path), ".md"))
	if strings.Contains(t, "daily mail") {
		return true
	}
	compact := strings.ReplaceAll(t, " ", "")
	if strings.Contains(compact, "일일메일") {
		return true
	}
	return strings.Contains(compact, "메일분석") && digestDateRe.MatchString(t)
}

// trailingBoilerplateRe matches the boilerplate section the create template
// puts at a page's tail (관련 문서). Dream update content belongs before it —
// the blind Body-append used to land new facts after the link list
// (2026-07-03 observed on 당진 대표.md).
var trailingBoilerplateRe = regexp.MustCompile(`(?m)^##\s*관련\s*문서\s*$`)

// mergeUpdateContent merges dream update content into an existing page body
// with two structural corrections over a blind append:
//
//   - lines the body already contains verbatim are dropped (the model
//     routinely re-states the page's own summary sentence alongside the one
//     new fact — the 2026-07-03 duplicate), and
//   - what remains is inserted BEFORE the trailing 관련 문서 boilerplate
//     instead of after it.
//
// Returns body unchanged when nothing new remains.
func mergeUpdateContent(body, content string) string {
	rest, replacements := liftReplaceableSections(content)
	out := body
	for _, sec := range replacements {
		out = upsertSection(out, sec.heading, sec.content)
	}
	fresh := dropDuplicateLines(rest, out)
	if strings.TrimSpace(fresh) == "" {
		if len(replacements) == 0 {
			return body
		}
		return out
	}
	if loc := trailingBoilerplateRe.FindStringIndex(out); loc != nil {
		return strings.TrimRight(out[:loc[0]], "\n") + "\n\n" + fresh + "\n\n" + out[loc[0]:]
	}
	return out + "\n\n" + fresh
}

// replaceableDreamHeadings are snapshot sections: the incoming draft is the
// current truth, so append would stack yesterday's "현재 상태" under today's.
var replaceableDreamHeadings = []string{"현재 상태", "핵심 숫자"}

type liftedSection struct {
	heading string
	content string
}

// liftReplaceableSections pulls ## 현재 상태 / ## 핵심 숫자 out of the
// proposed content so mergeUpdateContent can upsert them instead of appending.
func liftReplaceableSections(content string) (rest string, sections []liftedSection) {
	if !strings.Contains(content, "## ") {
		return content, nil
	}
	preamble, h2 := (&Page{Body: content}).SplitByH2()
	if len(h2) == 0 {
		return content, nil
	}
	replace := make(map[string]string, len(replaceableDreamHeadings))
	for _, name := range replaceableDreamHeadings {
		replace[name] = name
	}
	var kept strings.Builder
	if strings.TrimSpace(preamble) != "" {
		kept.WriteString(strings.TrimRight(preamble, "\n"))
		kept.WriteString("\n\n")
	}
	for _, sec := range h2 {
		heading := strings.TrimSpace(sec.Heading)
		if _, ok := replace[heading]; ok {
			sections = append(sections, liftedSection{heading: heading, content: strings.TrimSpace(sec.Content)})
			continue
		}
		kept.WriteString("## " + sec.Heading + "\n\n")
		kept.WriteString(strings.TrimRight(sec.Content, "\n"))
		kept.WriteString("\n\n")
	}
	return strings.TrimSpace(kept.String()), sections
}

// dropDuplicateLines removes content lines that already appear verbatim as a
// LINE of body. Matching is per-line, not substring — a content line that
// merely occurs inside a longer body sentence or link text is new context in
// its own right and must survive (a substring check over-dropped those). A
// leading list marker is normalized away so a body sentence re-stated as a
// bullet (or vice versa) still dedups. Only substantial lines (≥16 runes
// trimmed) are candidates: dropping a repeated short bullet or heading risks
// mangling structure for little gain.
func dropDuplicateLines(content, body string) string {
	bodyLines := make(map[string]struct{})
	for _, ln := range strings.Split(body, "\n") {
		if t := normalizeDedupLine(ln); t != "" {
			bodyLines[t] = struct{}{}
		}
	}
	lines := strings.Split(content, "\n")
	kept := make([]string, 0, len(lines))
	for _, ln := range lines {
		t := normalizeDedupLine(ln)
		if utf8.RuneCountInString(t) >= 16 {
			if _, dup := bodyLines[t]; dup {
				continue
			}
		}
		kept = append(kept, ln)
	}
	return strings.TrimSpace(strings.Join(kept, "\n"))
}

// normalizeDedupLine trims a line and strips one leading markdown list marker
// for duplicate comparison.
func normalizeDedupLine(ln string) string {
	t := strings.TrimSpace(ln)
	for _, m := range []string{"- ", "* ", "> "} {
		if strings.HasPrefix(t, m) {
			return strings.TrimSpace(t[len(m):])
		}
	}
	return t
}
