// dreamer_guards.go — apply-stage structural guards for dream-cycle updates.
//
// The synthesis prompt states the project layout rules, but a model can (and
// does) violate them; prompts are advisory, the apply pass is enforcement.
// Both guards below were minted from the first successful post-dsv4 dream
// cycle (2026-07-03): the model appended a "## 진행 로그" section to a 대표페이지
// (로그.md's slot) and created a date-titled daily mail digest page that would
// re-spawn every day.
package wiki

import (
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

// progressLogHeadingRe matches a 진행 로그 section heading (H2–H4) on its own
// line, tolerating spacing variants the model emits.
var progressLogHeadingRe = regexp.MustCompile(`(?m)^#{2,4}\s*진행\s*로그\s*$`)

// nextHeadingRe finds the heading that ends a captured section.
var nextHeadingRe = regexp.MustCompile(`(?m)^#{1,4}\s`)

// splitProgressLogSection cuts a "진행 로그" section out of content proposed
// for a 대표페이지, returning the remaining body and the section's lines
// (without its heading). ("", content unchanged) when no such section exists.
// Progress events belong in the project's 로그.md slot (wiki-layout 불변식);
// the caller reroutes the extracted lines there.
func splitProgressLogSection(content string) (body, logLines string) {
	loc := progressLogHeadingRe.FindStringIndex(content)
	if loc == nil {
		return content, ""
	}
	rest := content[loc[1]:]
	if end := nextHeadingRe.FindStringIndex(rest); end != nil {
		return strings.TrimSpace(content[:loc[0]] + rest[end[0]:]), strings.TrimSpace(rest[:end[0]])
	}
	return strings.TrimSpace(content[:loc[0]]), strings.TrimSpace(rest)
}

// appendProjectLog appends a dated H2 section to the project's 로그.md,
// creating the page on first use. H2 is the unit RotateProjectLog rotates on,
// so rerouted entries age out with the rest of the log.
func (wd *WikiDreamer) appendProjectLog(project, entry string) {
	if strings.TrimSpace(entry) == "" {
		return
	}
	section := "## " + time.Now().Format("2006-01-02") + " (dream)\n" + strings.TrimSpace(entry) + "\n"
	err := wd.store.UpdatePage(LogPagePath(project), func(cur *Page) (*Page, error) {
		if cur == nil {
			p := NewPage(project+" 진행 로그", "프로젝트", nil)
			p.Meta.Type = "log"
			p.Meta.Summary = project + " 진행 로그"
			p.Body = section
			return p, nil
		}
		cur.Body = strings.TrimRight(cur.Body, "\n") + "\n\n" + section
		return cur, nil
	})
	if err != nil && wd.logger != nil {
		wd.logger.Warn("wiki-dream: project log reroute failed", "project", project, "error", err)
	}
}

// digestDateRe matches the date stamps daily-digest titles carry.
var digestDateRe = regexp.MustCompile(`\d{4}[-./]\d{1,2}[-./]\d{1,2}|\d{1,2}\s*/\s*\d{1,2}`)

// isDailyMailDigestPage reports whether a proposed page is a date-titled daily
// mail digest ("daily mail analysis", "2026-07-02 일일 메일 분석", …). These
// re-spawn every day, duplicate facts the same batch already distributes onto
// per-project pages, and mail-analysis pages are system-generated by contract
// — the dreamer must neither create nor grow them. The path check uses only
// the file base, so legitimate system pages under 메일분석/ directories (whose
// base is a message ID) never match.
func isDailyMailDigestPage(title, path string) bool {
	t := strings.ToLower(title + " " + strings.TrimSuffix(filepath.Base(path), ".md"))
	if strings.Contains(t, "daily mail") {
		return true
	}
	compact := strings.ReplaceAll(t, " ", "")
	if strings.Contains(compact, "일일메일") {
		return true
	}
	return strings.Contains(compact, "메일분석") && digestDateRe.MatchString(t)
}
