// Code generated by data-gen. DO NOT EDIT.
// Source: gateway-go/internal/auth/role_permissions.yaml
// Regenerate: make data-gen

package auth

// rolePermissions defines the default scopes for each role.
var rolePermissions = map[Role][]Scope{
	RoleOperator: []Scope{ScopeAdmin, ScopeRead, ScopeWrite, ScopeApprovals, ScopePairing},
	RoleViewer:   []Scope{ScopeRead},
	RoleAgent:    []Scope{ScopeRead, ScopeWrite},
	RoleProbe:    []Scope{ScopeRead},
}
