//! Stop word lists for query keyword extraction.
//!
//! Each language is a `const` slice so callers can build `HashSets` or iterate
//! without allocating at compile time.  The Korean trailing-particle list is
//! also kept here because it is purely language data.

// ---------------------------------------------------------------------------
// English
// ---------------------------------------------------------------------------

pub const EN: &[&str] = &[
    // Articles and determiners
    "a",
    "an",
    "the",
    "this",
    "that",
    "these",
    "those",
    // Pronouns
    "i",
    "me",
    "my",
    "we",
    "our",
    "you",
    "your",
    "he",
    "she",
    "it",
    "they",
    "them",
    // Common verbs
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "could",
    "should",
    "can",
    "may",
    "might",
    // Prepositions
    "in",
    "on",
    "at",
    "to",
    "for",
    "of",
    "with",
    "by",
    "from",
    "about",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "between",
    "under",
    "over",
    // Conjunctions
    "and",
    "or",
    "but",
    "if",
    "then",
    "because",
    "as",
    "while",
    "when",
    "where",
    "what",
    "which",
    "who",
    "how",
    "why",
    // Time references
    "yesterday",
    "today",
    "tomorrow",
    "earlier",
    "later",
    "recently",
    "ago",
    "just",
    "now",
    // Vague references
    "thing",
    "things",
    "stuff",
    "something",
    "anything",
    "everything",
    "nothing",
    // Request/action words
    "please",
    "help",
    "find",
    "show",
    "get",
    "tell",
    "give",
];

// ---------------------------------------------------------------------------
// Korean
// ---------------------------------------------------------------------------

pub const KO: &[&str] = &[
    // Particles
    "은",
    "는",
    "이",
    "가",
    "을",
    "를",
    "의",
    "에",
    "에서",
    "로",
    "으로",
    "와",
    "과",
    "도",
    "만",
    "까지",
    "부터",
    "한테",
    "에게",
    "께",
    "처럼",
    "같이",
    "보다",
    "마다",
    "밖에",
    "대로",
    // Pronouns
    "나",
    "나는",
    "내가",
    "나를",
    "너",
    "우리",
    "저",
    "저희",
    "그",
    "그녀",
    "그들",
    "이것",
    "저것",
    "그것",
    "여기",
    "저기",
    "거기",
    // Common verbs
    "있다",
    "없다",
    "하다",
    "되다",
    "이다",
    "아니다",
    "보다",
    "주다",
    "오다",
    "가다",
    // Vague nouns
    "것",
    "거",
    "등",
    "수",
    "때",
    "곳",
    "중",
    "분",
    // Adverbs
    "잘",
    "더",
    "또",
    "매우",
    "정말",
    "아주",
    "많이",
    "너무",
    "좀",
    // Conjunctions
    "그리고",
    "하지만",
    "그래서",
    "그런데",
    "그러나",
    "또는",
    "그러면",
    // Question words
    "왜",
    "어떻게",
    "뭐",
    "언제",
    "어디",
    "누구",
    "무엇",
    "어떤",
    // Time
    "어제",
    "오늘",
    "내일",
    "최근",
    "지금",
    "아까",
    "나중",
    "전에",
    // Request
    "제발",
    "부탁",
];

/// Korean trailing particles, sorted longest-first for greedy strip matching.
pub const KO_TRAILING_PARTICLES: &[&str] = &[
    "에서", "으로", "에게", "한테", "처럼", "같이", "보다", "까지", "부터", "마다", "밖에", "대로",
    "은", "는", "이", "가", "을", "를", "의", "에", "로", "와", "과", "도", "만",
];
