// Code generated by data-gen. DO NOT EDIT.
// Source: gateway-go/internal/events/event_scope_guards.yaml
// Regenerate: make data-gen

package events

// eventScopeGuards maps event names to required scopes.
// Events not listed here are delivered to all authenticated subscribers.
var eventScopeGuards = map[string][]string{
	"exec.approval.requested": []string{"approvals", "admin"},
	"exec.approval.resolved":  []string{"approvals", "admin"},
	"device.pair.requested":   []string{"approvals", "admin"},
	"device.pair.resolved":    []string{"approvals", "admin"},
	"node.pair.requested":     []string{"approvals", "admin"},
	"node.pair.resolved":      []string{"approvals", "admin"},
	"sessions.changed":        []string{"read"},
	"session.message":         []string{"read"},
	"session.tool":            []string{"read"},
	"agent":                   []string{"read"},
	"agent.event":             []string{"read"},
	"telegram.changed":        []string{"read"},
	"config.changed":          []string{"admin"},
	"process.completed":       []string{"write", "admin"},
	"heartbeat":               []string{"read"},
	"dreaming.cycle":          []string{"read"},
	"shadow.event":            []string{"read"},
	"bridge.message":          []string{"read"},
}
