#!/usr/bin/env bash
# gen-ffi-errors.sh — Generate Go FFI error constants from core-rs/core/src/ffi_utils.rs.
#
# Rust (ffi_utils.rs) is the single source of truth for FFI error codes.
# This script generates gateway-go/internal/ffi/ffi_error_codes_gen.go so
# Go never needs to be manually kept in sync.
#
# Usage:
#   ./scripts/gen-ffi-errors.sh           # write ffi_error_codes_gen.go
#   ./scripts/gen-ffi-errors.sh --check   # exit 1 if generated file is stale
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

RUST_SRC="core-rs/core/src/ffi_utils.rs"
GO_OUT="gateway-go/internal/ffi/ffi_error_codes_gen.go"
CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

# ---------------------------------------------------------------------------
# Name conversion: SCREAMING_SNAKE suffix → Go camelCase with rc prefix.
# Known acronyms are kept uppercase; other words are title-cased.
# Example: NULL_POINTER → rcNullPointer, JSON_ERROR → rcJSONError
# ---------------------------------------------------------------------------
go_name() {
  local suffix="$1"
  local result=""
  IFS='_' read -ra parts <<< "$suffix"
  for part in "${parts[@]}"; do
    case "$part" in
      UTF8|UTF|JSON|HTML|URL|HTTP|API|ID|UUID)
        result+="$part" ;;
      *)
        local lo="${part,,}"
        result+="${lo^}" ;;
    esac
  done
  echo "rc${result}"
}

# ---------------------------------------------------------------------------
# Parse Rust source: extract constant suffix and value from each FFI_ERR_* line.
# ---------------------------------------------------------------------------
declare -a names=()
declare -a values=()
while IFS= read -r line; do
  if [[ "$line" =~ pub\(crate\)[[:space:]]+const[[:space:]]+FFI_ERR_([A-Z_0-9]+):[[:space:]]*i32[[:space:]]*=[[:space:]]*(-?[0-9]+) ]]; then
    names+=("${BASH_REMATCH[1]}")
    values+=("${BASH_REMATCH[2]}")
  fi
done < "$RUST_SRC"

[[ ${#names[@]} -gt 0 ]] || { echo "ERROR: no FFI_ERR_* constants found in $RUST_SRC" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Emit the generated Go file.
# ---------------------------------------------------------------------------
generate() {
  printf '// Code generated by scripts/gen-ffi-errors.sh; DO NOT EDIT.\n'
  printf '// Source of truth: %s\n' "$RUST_SRC"
  printf '// Regenerate with: make ffi-gen\n'
  printf '\n'
  printf 'package ffi\n'
  printf '\n'
  printf '// FFI return codes — negative i32 values returned by core-rs C ABI functions.\n'
  printf '// Positive return values from buffer-writing functions are bytes written, not error codes.\n'
  printf 'const (\n'
  local i
  for i in "${!names[@]}"; do
    local go_const
    go_const=$(go_name "${names[$i]}")
    printf '\t%s = %s\n' "$go_const" "${values[$i]}"
  done
  printf ')\n'
}

if [[ "$CHECK" -eq 1 ]]; then
  tmp=$(mktemp --suffix=.go)
  trap "rm -f '$tmp'" EXIT
  generate | gofmt > "$tmp"
  if ! diff -q "$tmp" "$GO_OUT" > /dev/null 2>&1; then
    echo "FAIL: $GO_OUT is out of sync with $RUST_SRC" >&2
    echo "Run 'make ffi-gen' to regenerate." >&2
    diff "$tmp" "$GO_OUT" >&2 || true
    exit 1
  fi
  echo "ffi-gen-check: OK ($GO_OUT is up to date)"
else
  generate | gofmt > "$GO_OUT"
  echo "ffi-gen: wrote $GO_OUT"
fi
