#!/usr/bin/env bash
# gen-error-codes.sh — Generate Go error code files from proto/gateway.proto.
#
# proto/gateway.proto is the single source of truth for BOTH:
#   - ErrorCode      (protocol-level, positive values)
#   - FfiErrorCode   (C ABI transport, positive in proto, negated in output)
#
# Outputs:
#   1. gateway-go/pkg/protocol/errors_gen.go       (Go Err* string constants)
#   2. gateway-go/internal/ffi/ffi_error_codes_gen.go (Go rc* int constants)
#
# Usage:
#   ./scripts/gen-error-codes.sh           # write all output files
#   ./scripts/gen-error-codes.sh --check   # exit 1 if any output is stale
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

PROTO_FILE="proto/gateway.proto"
GO_PROTO_OUT="gateway-go/pkg/protocol/errors_gen.go"
GO_FFI_OUT="gateway-go/internal/ffi/ffi_error_codes_gen.go"
CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

# ---------------------------------------------------------------------------
# Name conversions
# ---------------------------------------------------------------------------

# SCREAMING_SNAKE suffix → Go camelCase with Err prefix.
# e.g. NOT_FOUND → ErrNotFound, AGENT_TIMEOUT → ErrAgentTimeout
to_go_err() {
  local name="$1"
  local result=""
  IFS='_' read -ra parts <<< "$name"
  for part in "${parts[@]}"; do
    local lo="${part,,}"
    result+="${lo^}"
  done
  echo "Err${result}"
}

# SCREAMING_SNAKE suffix → Go camelCase with rc prefix.
# Known acronyms kept uppercase.
# e.g. NULL_POINTER → rcNullPointer, JSON_ERROR → rcJSONError
to_go_rc() {
  local suffix="$1"
  local result=""
  IFS='_' read -ra parts <<< "$suffix"
  for part in "${parts[@]}"; do
    case "$part" in
      UTF8|UTF|JSON|HTML|URL|HTTP|API|ID|UUID)
        result+="$part" ;;
      *)
        local lo="${part,,}"
        result+="${lo^}" ;;
    esac
  done
  echo "rc${result}"
}

# ---------------------------------------------------------------------------
# Parse ErrorCode enum from proto file.
# ---------------------------------------------------------------------------
declare -a EC_NAMES=()
declare -a EC_VALUES=()

parse_error_code() {
  local in_enum=0

  while IFS= read -r line; do
    if [[ "$line" =~ ^enum[[:space:]]+ErrorCode[[:space:]]*\{ ]]; then
      in_enum=1; continue
    fi
    if [[ "$in_enum" -eq 1 && "$line" =~ ^\} ]]; then break; fi
    [[ "$in_enum" -eq 0 ]] && continue

    local re='ERROR_CODE_([A-Z_]+)[[:space:]]*=[[:space:]]*([0-9]+)[[:space:]]*;(.*)'
    if [[ "$line" =~ $re ]]; then
      local name="${BASH_REMATCH[1]}"
      local value="${BASH_REMATCH[2]}"
      [[ "$name" == "UNSPECIFIED" ]] && continue

      EC_NAMES+=("$name")
      EC_VALUES+=("$value")
    fi
  done < "$PROTO_FILE"
}

# ---------------------------------------------------------------------------
# Parse FfiErrorCode enum from proto file.
# ---------------------------------------------------------------------------
declare -a FFI_NAMES=()
declare -a FFI_VALUES=()

parse_ffi_error_code() {
  local in_enum=0

  while IFS= read -r line; do
    if [[ "$line" =~ ^enum[[:space:]]+FfiErrorCode[[:space:]]*\{ ]]; then
      in_enum=1; continue
    fi
    if [[ "$in_enum" -eq 1 && "$line" =~ ^\} ]]; then break; fi
    [[ "$in_enum" -eq 0 ]] && continue

    local re='FFI_ERROR_CODE_([A-Z_0-9]+)[[:space:]]*=[[:space:]]*([0-9]+)[[:space:]]*;'
    if [[ "$line" =~ $re ]]; then
      local name="${BASH_REMATCH[1]}"
      local value="${BASH_REMATCH[2]}"
      [[ "$name" == "UNSPECIFIED" ]] && continue
      FFI_NAMES+=("$name")
      FFI_VALUES+=("$value")
    fi
  done < "$PROTO_FILE"
}

# ---------------------------------------------------------------------------
# Parse both enums
# ---------------------------------------------------------------------------
parse_error_code
parse_ffi_error_code

[[ ${#EC_NAMES[@]} -gt 0 ]] || { echo "ERROR: no ErrorCode variants found in $PROTO_FILE" >&2; exit 1; }
[[ ${#FFI_NAMES[@]} -gt 0 ]] || { echo "ERROR: no FfiErrorCode variants found in $PROTO_FILE" >&2; exit 1; }

# ===========================================================================
# Output 1: Go errors_gen.go (protocol error string constants)
# ===========================================================================
generate_go_proto() {
  printf '// Code generated by scripts/gen-error-codes.sh; DO NOT EDIT.\n'
  printf '// Source of truth: proto/gateway.proto\n'
  printf '// Regenerate with: make error-codes-gen\n'
  printf '\n'
  printf 'package protocol\n'
  printf '\n'
  printf '// Error code constants — protocol-level error codes from ErrorCode enum.\n'
  printf 'const (\n'
  for i in "${!EC_NAMES[@]}"; do
    local go_name
    go_name=$(to_go_err "${EC_NAMES[$i]}")
    printf '\t%s = "%s"\n' "$go_name" "${EC_NAMES[$i]}"
  done
  printf ')\n'
}

# ===========================================================================
# Output 2: Go ffi_error_codes_gen.go (FFI return code int constants)
# ===========================================================================
generate_go_ffi() {
  printf '// Code generated by scripts/gen-error-codes.sh; DO NOT EDIT.\n'
  printf '// Source of truth: proto/gateway.proto\n'
  printf '// Regenerate with: make error-codes-gen\n'
  printf '\n'
  printf 'package ffi\n'
  printf '\n'
  printf '// FFI return codes — negative i32 values (legacy from Rust C ABI, kept for compatibility).\n'
  printf 'const (\n'
  for i in "${!FFI_NAMES[@]}"; do
    local go_const
    go_const=$(to_go_rc "${FFI_NAMES[$i]}")
    printf '\t%s = -%s\n' "$go_const" "${FFI_VALUES[$i]}"
  done
  printf ')\n'
}

# ===========================================================================
# Check or write
# ===========================================================================
if [[ "$CHECK" -eq 1 ]]; then
  tmp_go_proto=$(mktemp --suffix=.go)
  tmp_go_ffi=$(mktemp --suffix=.go)
  trap "rm -f '$tmp_go_proto' '$tmp_go_ffi'" EXIT

  generate_go_proto | gofmt > "$tmp_go_proto"
  generate_go_ffi | gofmt > "$tmp_go_ffi"

  failed=0
  for pair in "$tmp_go_proto:$GO_PROTO_OUT" "$tmp_go_ffi:$GO_FFI_OUT"; do
    tmp="${pair%%:*}"
    out="${pair##*:}"
    if ! diff -q "$tmp" "$out" > /dev/null 2>&1; then
      echo "FAIL: $out is out of sync with $PROTO_FILE" >&2
      diff "$tmp" "$out" >&2 || true
      failed=1
    fi
  done

  if [[ "$failed" -eq 1 ]]; then
    echo "Run 'make error-codes-gen' to regenerate." >&2
    exit 1
  fi
  echo "error-codes-gen-check: OK (all outputs up to date)"
else
  generate_go_proto | gofmt > "$GO_PROTO_OUT"
  generate_go_ffi | gofmt > "$GO_FFI_OUT"
  echo "error-codes-gen: wrote $GO_PROTO_OUT"
  echo "error-codes-gen: wrote $GO_FFI_OUT"
fi
