#!/usr/bin/env bash
# gen-proto-error-codes.sh — Generate Rust ErrorCode from proto/gateway.proto.
#
# proto/gateway.proto is the single source of truth for the ErrorCode enum.
# Generates: core-rs/core/src/protocol/error_codes.rs
#
# Retryability is annotated directly in the proto file with trailing comments:
#   ERROR_CODE_AGENT_TIMEOUT = 3;    // retryable
#
# Usage:
#   ./scripts/gen-proto-error-codes.sh           # write error_codes.rs
#   ./scripts/gen-proto-error-codes.sh --check   # exit 1 if generated file is stale
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

PROTO_FILE="proto/gateway.proto"
RUST_OUT="core-rs/core/src/protocol/error_codes.rs"
CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

# ---------------------------------------------------------------------------
# Name conversion: SCREAMING_SNAKE → PascalCase
# ---------------------------------------------------------------------------
to_pascal() {
  local name="$1"
  local result=""
  IFS='_' read -ra parts <<< "$name"
  for part in "${parts[@]}"; do
    local lo="${part,,}"
    result+="${lo^}"
  done
  echo "$result"
}

# ---------------------------------------------------------------------------
# Parse the ErrorCode enum from the proto file.
# Extracts: name (no ERROR_CODE_ prefix), discriminant, retryable flag,
# and the preceding section comment (e.g. "Legacy codes (backward compatible)").
# ---------------------------------------------------------------------------
declare -a NAMES=()
declare -a VALUES=()
declare -a RETRYABLE=()
declare -a SECTION=()

in_enum=0
pending_section=""

while IFS= read -r line; do
  # Detect "enum ErrorCode {" start
  if [[ "$line" =~ ^enum[[:space:]]+ErrorCode[[:space:]]*\{ ]]; then
    in_enum=1
    continue
  fi
  # Detect enum end
  if [[ "$in_enum" -eq 1 && "$line" =~ ^\} ]]; then
    break
  fi
  [[ "$in_enum" -eq 0 ]] && continue

  # Section comment line inside enum (not a retryable annotation)
  if [[ "$line" =~ ^[[:space:]]*//(.*) ]]; then
    comment="${BASH_REMATCH[1]# }"
    if [[ "$comment" != *retryable* ]] && [[ -n "$comment" ]]; then
      pending_section="$comment"
    fi
    continue
  fi

  # Parse: ERROR_CODE_NAME = VALUE; [// retryable]
  # Store regex in variable to prevent bash from misinterpreting ';' as a command separator.
  local_re='ERROR_CODE_([A-Z_]+)[[:space:]]*=[[:space:]]*([0-9]+)[[:space:]]*;(.*)'
  if [[ "$line" =~ $local_re ]]; then
    local_name="${BASH_REMATCH[1]}"
    local_value="${BASH_REMATCH[2]}"
    local_rest="${BASH_REMATCH[3]}"

    # Skip the zero sentinel
    [[ "$local_name" == "UNSPECIFIED" ]] && { pending_section=""; continue; }

    local_retryable=0
    [[ "$local_rest" == *retryable* ]] && local_retryable=1

    NAMES+=("$local_name")
    VALUES+=("$local_value")
    RETRYABLE+=("$local_retryable")
    SECTION+=("$pending_section")
    pending_section=""
  fi
done < "$PROTO_FILE"

[[ ${#NAMES[@]} -gt 0 ]] || { echo "ERROR: no ErrorCode variants found in $PROTO_FILE" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Emit the generated Rust source file.
# ---------------------------------------------------------------------------
generate() {
  printf '// Code generated by scripts/gen-proto-error-codes.sh; DO NOT EDIT.\n'
  printf '// Source of truth: proto/gateway.proto\n'
  printf '// Regenerate with: make proto-error-codes-gen\n'
  printf '\n'
  printf '//! Gateway error codes — auto-generated from `proto/gateway.proto`.\n'
  printf '\n'
  printf '/// Gateway RPC error codes.\n'
  printf '///\n'
  printf '/// Each variant maps to a stable string code used on the wire.\n'
  printf '/// The i32 discriminant provides a compact representation for FFI.\n'
  printf '#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n'
  printf '#[repr(i32)]\n'
  printf 'pub enum ErrorCode {\n'

  local prev_section=""
  local i
  for i in "${!NAMES[@]}"; do
    local section="${SECTION[$i]}"
    local pascal
    pascal=$(to_pascal "${NAMES[$i]}")

    if [[ -n "$section" && "$section" != "$prev_section" ]]; then
      printf '    // %s\n' "$section"
      prev_section="$section"
    fi
    printf '    %s = %s,\n' "$pascal" "${VALUES[$i]}"
  done

  printf '}\n'
  printf '\n'
  printf 'impl ErrorCode {\n'
  printf "    /// Wire-format string code used on the wire.\n"
  printf "    pub fn as_str(&self) -> &'static str {\n"
  printf '        match self {\n'

  for i in "${!NAMES[@]}"; do
    local pascal
    pascal=$(to_pascal "${NAMES[$i]}")
    printf '            Self::%s => "%s",\n' "$pascal" "${NAMES[$i]}"
  done

  printf '        }\n'
  printf '    }\n'
  printf '\n'
  printf '    /// Parse a wire-format string into an `ErrorCode`.\n'
  printf '    pub fn parse(s: &str) -> Option<Self> {\n'
  printf '        match s {\n'

  for i in "${!NAMES[@]}"; do
    local pascal
    pascal=$(to_pascal "${NAMES[$i]}")
    printf '            "%s" => Some(Self::%s),\n' "${NAMES[$i]}" "$pascal"
  done

  printf '            _ => None,\n'
  printf '        }\n'
  printf '    }\n'
  printf '\n'
  printf '    /// Whether this code is retryable by default.\n'
  printf '    pub fn is_retryable(&self) -> bool {\n'

  # Collect retryable variants
  local -a retryable_variants=()
  for i in "${!NAMES[@]}"; do
    if [[ "${RETRYABLE[$i]}" == "1" ]]; then
      retryable_variants+=("$(to_pascal "${NAMES[$i]}")")
    fi
  done

  if [[ ${#retryable_variants[@]} -eq 0 ]]; then
    printf '        false\n'
  else
    printf '        matches!(\n'
    printf '            self,\n'
    local j
    for j in "${!retryable_variants[@]}"; do
      if [[ "$j" -eq 0 ]]; then
        printf '            Self::%s' "${retryable_variants[$j]}"
      else
        printf '\n                | Self::%s' "${retryable_variants[$j]}"
      fi
    done
    printf '\n'
    printf '        )\n'
  fi

  printf '    }\n'
  printf '}\n'
  printf '\n'
  printf 'impl std::fmt::Display for ErrorCode {\n'
  printf "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n"
  printf '        f.write_str(self.as_str())\n'
  printf '    }\n'
  printf '}\n'
  printf '\n'
  printf '/// All known error codes in declaration order.\n'
  printf 'pub const ALL_ERROR_CODES: &[ErrorCode] = &[\n'

  for i in "${!NAMES[@]}"; do
    local pascal
    pascal=$(to_pascal "${NAMES[$i]}")
    printf '    ErrorCode::%s,\n' "$pascal"
  done

  printf '];\n'
  printf '\n'
  printf '/// Validate that an error code string is a known code.\n'
  printf 'pub fn is_valid_error_code(code: &str) -> bool {\n'
  printf '    ErrorCode::parse(code).is_some()\n'
  printf '}\n'
  printf '\n'
  printf '#[cfg(test)]\n'
  printf '#[allow(clippy::expect_used)]\n'
  printf 'mod tests {\n'
  printf '    use super::*;\n'
  printf '\n'
  printf '    #[test]\n'
  printf '    fn test_roundtrip() {\n'
  printf '        for code in ALL_ERROR_CODES {\n'
  printf '            let s = code.as_str();\n'
  printf '            let parsed = ErrorCode::parse(s).expect("known code should round-trip through parse");\n'
  printf '            assert_eq!(*code, parsed);\n'
  printf '        }\n'
  printf '    }\n'
  printf '\n'
  printf '    #[test]\n'
  printf '    fn test_unknown_code() {\n'
  printf '        assert!(ErrorCode::parse("UNKNOWN_CODE").is_none());\n'
  printf '        assert!(!is_valid_error_code("BOGUS"));\n'
  printf '    }\n'
  printf '\n'
  printf '    #[test]\n'
  printf '    fn test_retryable() {\n'

  for i in "${!NAMES[@]}"; do
    local pascal
    pascal=$(to_pascal "${NAMES[$i]}")
    if [[ "${RETRYABLE[$i]}" == "1" ]]; then
      printf '        assert!(ErrorCode::%s.is_retryable());\n' "$pascal"
    else
      printf '        assert!(!ErrorCode::%s.is_retryable());\n' "$pascal"
    fi
  done

  printf '    }\n'
  printf '\n'
  printf '    #[test]\n'
  printf '    fn test_discriminants_unique() {\n'
  printf '        let mut seen = std::collections::HashSet::new();\n'
  printf '        for code in ALL_ERROR_CODES {\n'
  printf '            assert!(\n'
  printf '                seen.insert(*code as i32),\n'
  printf '                "duplicate discriminant for {code}"\n'
  printf '            );\n'
  printf '        }\n'
  printf '    }\n'
  printf '\n'
  printf '    #[test]\n'
  printf '    fn test_display() {\n'
  printf '        assert_eq!(format!("{}", ErrorCode::NotFound), "NOT_FOUND");\n'
  printf '    }\n'
  printf '}\n'
}

if [[ "$CHECK" -eq 1 ]]; then
  tmp=$(mktemp --suffix=.rs)
  trap "rm -f '$tmp'" EXIT
  generate > "$tmp"
  if ! diff -q "$tmp" "$RUST_OUT" > /dev/null 2>&1; then
    echo "FAIL: $RUST_OUT is out of sync with $PROTO_FILE" >&2
    echo "Run 'make proto-error-codes-gen' to regenerate." >&2
    diff "$tmp" "$RUST_OUT" >&2 || true
    exit 1
  fi
  echo "proto-error-codes-gen-check: OK ($RUST_OUT is up to date)"
else
  generate > "$RUST_OUT"
  echo "proto-error-codes-gen: wrote $RUST_OUT"
fi
