// Auto-generated by scripts/generate-bundled-provider-auth-env-vars.mjs. Do not edit directly.

export const BUNDLED_PROVIDER_AUTH_ENV_VAR_CANDIDATES = {} as const satisfies Record<
  string,
  readonly string[]
>;
