#!/usr/bin/env python3
"""data-gen: generate Go variable declarations from YAML data files.

Universal code generator for data-driven Go code. Reads a YAML file
containing variable definitions with type metadata and generates
corresponding Go source code.

Usage (from gateway-go/):
    python3 cmd/data-gen/gen.py \
        -yaml internal/rpc/method_scopes.yaml \
        -out  internal/rpc/method_scopes_gen.go

Or via Makefile:
    make data-gen

YAML format:
    _gen:
      package: <go-package-name>
      imports: [<import-path>, ...]   # optional
      build_tags: <tags>              # optional, e.g. "no_ffi || !cgo"

    <varName>:
      _type: <go-type>               # map[K]V, []T, etc.
      _doc: <comment>                # optional doc comment
      _value_map:                    # optional shorthand -> Go expression
        short: GoExpr
      _values:                       # data entries (dict for maps, list for slices)
        key: value
"""

import argparse
import os
import re
import subprocess
import sys

import yaml


# ---------------------------------------------------------------------------
# Go literal helpers
# ---------------------------------------------------------------------------

def go_str(s: str) -> str:
    """Produce a Go double-quoted string literal."""
    s = str(s).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")
    return f'"{s}"'


def parse_map_type(t: str):
    """Parse 'map[K]V' -> (K, V). Returns (None, t) for non-maps."""
    m = re.match(r"^map\[([^\]]+)\](.+)$", t)
    return (m.group(1), m.group(2)) if m else (None, t)


def parse_slice_type(t: str):
    """If t is '[]X', return X; else None."""
    return t[2:] if t.startswith("[]") else None


def is_string_type(t: str) -> bool:
    return t == "string"


# ---------------------------------------------------------------------------
# Value rendering
# ---------------------------------------------------------------------------

def render_value(val, go_type: str, value_map: dict | None) -> str:
    """Render a Python/YAML value as a Go expression."""
    if value_map and isinstance(val, str) and val in value_map:
        return str(value_map[val])

    elem = parse_slice_type(go_type)
    if elem is not None:
        if not isinstance(val, list):
            val = [val]
        items = ", ".join(render_value(v, elem, value_map) for v in val)
        return f"{go_type}{{{items}}}"

    if is_string_type(go_type):
        return go_str(val)
    if go_type == "bool":
        return "true" if val else "false"
    if go_type == "float64":
        if isinstance(val, int):
            return f"{float(val)}"
        return str(val)
    if go_type == "int":
        return str(int(val))

    # Custom type (e.g. auth.Scope) — use as-is.
    return str(val)


def render_key(key, key_type: str) -> str:
    """Render a map key as a Go expression."""
    if is_string_type(key_type):
        return go_str(key)
    return str(key)


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

def generate(data: dict, source_path: str) -> str:
    gen = data.get("_gen", {})
    pkg = gen.get("package", "main")
    imports = gen.get("imports", [])
    build_tags = gen.get("build_tags", "")

    lines: list[str] = []

    if build_tags:
        lines.append(f"//go:build {build_tags}")
        lines.append("")

    lines.append("// Code generated by data-gen. DO NOT EDIT.")
    lines.append(f"// Source: {source_path}")
    lines.append("// Regenerate: make data-gen")
    lines.append("")
    lines.append(f"package {pkg}")
    lines.append("")

    if imports:
        if len(imports) == 1:
            lines.append(f'import "{imports[0]}"')
        else:
            lines.append("import (")
            for imp in imports:
                lines.append(f'\t"{imp}"')
            lines.append(")")
        lines.append("")

    for var_name, var_def in data.items():
        if var_name.startswith("_") or not isinstance(var_def, dict):
            continue

        type_str = var_def.get("_type", "map[string]string")
        doc = var_def.get("_doc", "").strip()
        value_map = var_def.get("_value_map")
        values = var_def.get("_values", {})

        if doc:
            for dline in doc.split("\n"):
                lines.append(f"// {dline}")

        key_type, val_type = parse_map_type(type_str)

        if key_type is not None:
            lines.append(f"var {var_name} = {type_str}{{")
            if isinstance(values, dict):
                for k, v in values.items():
                    lines.append(f"\t{render_key(k, key_type)}: {render_value(v, val_type, value_map)},")
            lines.append("}")
        else:
            elem = parse_slice_type(type_str)
            if elem is not None and isinstance(values, list):
                lines.append(f"var {var_name} = {type_str}{{")
                for item in values:
                    lines.append(f"\t{render_value(item, elem, value_map)},")
                lines.append("}")

        lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    p = argparse.ArgumentParser(description="Generate Go vars from YAML data")
    p.add_argument("-yaml", required=True, dest="yaml_file", metavar="FILE")
    p.add_argument("-out", required=True, dest="out_file", metavar="FILE")
    args = p.parse_args()

    with open(args.yaml_file, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    if not isinstance(data, dict):
        print("error: YAML root must be a mapping", file=sys.stderr)
        sys.exit(1)

    # Derive source path for the header comment.
    source = args.yaml_file
    abs_path = os.path.abspath(args.yaml_file)
    idx = abs_path.find("/gateway-go/")
    if idx >= 0:
        source = abs_path[idx + 1:]  # "gateway-go/internal/..."

    src = generate(data, source)

    result = subprocess.run(["gofmt"], input=src, capture_output=True, text=True)
    if result.returncode == 0:
        src = result.stdout
    else:
        print(f"gofmt warning: {result.stderr}", file=sys.stderr)

    with open(args.out_file, "w", encoding="utf-8") as f:
        f.write(src)

    n_vars = sum(1 for k in data if not k.startswith("_"))
    n_entries = 0
    for k, v in data.items():
        if k.startswith("_") or not isinstance(v, dict):
            continue
        vals = v.get("_values", {})
        n_entries += len(vals) if isinstance(vals, (dict, list)) else 0
    print(f"wrote {args.out_file} ({n_vars} vars, {n_entries} entries)")


if __name__ == "__main__":
    main()
