// data-gen generates Go variable declarations from YAML data files.
//
// Universal code generator for data-driven Go code. Reads a YAML file
// containing variable definitions with type metadata and generates
// corresponding Go source code.
//
// Usage (from gateway-go/):
//
//	go run cmd/data-gen/main.go \
//	    -yaml internal/chat/tool_classification.yaml \
//	    -out  internal/chat/tool_classification_gen.go
//
// Or via Makefile: make data-gen
//
// YAML format:
//
//	_gen:
//	  package: <go-package-name>
//	  imports: [<import-path>, ...]   # optional
//	  build_tags: <tags>              # optional
//
//	<varName>:
//	  _type: <go-type>               # map[K]V, []T, etc.
//	  _doc: <comment>                # optional doc comment
//	  _value_map:                    # optional shorthand → Go expression
//	    short: GoExpr
//	  _values:                       # data entries (dict for maps, list for slices)
//	    key: value
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	yamlFile := flag.String("yaml", "", "YAML source file")
	outFile := flag.String("out", "", "Output Go file")
	flag.Parse()

	if *yamlFile == "" || *outFile == "" {
		fmt.Fprintln(os.Stderr, "usage: data-gen -yaml FILE -out FILE")
		os.Exit(1)
	}

	data, err := os.ReadFile(*yamlFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	var root yaml.Node
	if err := yaml.Unmarshal(data, &root); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	if root.Kind != yaml.DocumentNode || len(root.Content) == 0 ||
		root.Content[0].Kind != yaml.MappingNode {
		fmt.Fprintln(os.Stderr, "error: YAML root must be a mapping")
		os.Exit(1)
	}

	doc := root.Content[0]

	// Derive source path for the header comment.
	sourcePath := *yamlFile
	if abs, err := filepath.Abs(*yamlFile); err == nil {
		if idx := strings.Index(abs, "/gateway-go/"); idx >= 0 {
			sourcePath = abs[idx+1:]
		}
	}

	src := generate(doc, sourcePath)

	formatted, err := format.Source([]byte(src))
	if err != nil {
		fmt.Fprintf(os.Stderr, "gofmt warning: %v\n", err)
		formatted = []byte(src)
	}

	if err := os.WriteFile(*outFile, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	nVars, nEntries := 0, 0
	for i := 0; i < len(doc.Content); i += 2 {
		key := doc.Content[i].Value
		if strings.HasPrefix(key, "_") {
			continue
		}
		val := doc.Content[i+1]
		if val.Kind != yaml.MappingNode {
			continue
		}
		nVars++
		if values := nodeGet(val, "_values"); values != nil {
			switch values.Kind {
			case yaml.MappingNode:
				nEntries += len(values.Content) / 2
			case yaml.SequenceNode:
				nEntries += len(values.Content)
			}
		}
	}
	fmt.Printf("wrote %s (%d vars, %d entries)\n", *outFile, nVars, nEntries)
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

func generate(doc *yaml.Node, sourcePath string) string {
	gen := nodeGet(doc, "_gen")
	pkg := "main"
	var imports []string
	buildTags := ""

	if gen != nil {
		if v := nodeGet(gen, "package"); v != nil {
			pkg = v.Value
		}
		if v := nodeGet(gen, "imports"); v != nil {
			for _, item := range v.Content {
				imports = append(imports, item.Value)
			}
		}
		if v := nodeGet(gen, "build_tags"); v != nil {
			buildTags = v.Value
		}
	}

	var b strings.Builder

	if buildTags != "" {
		fmt.Fprintf(&b, "//go:build %s\n\n", buildTags)
	}

	b.WriteString("// Code generated by data-gen. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: %s\n", sourcePath)
	b.WriteString("// Regenerate: make data-gen\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	if len(imports) > 0 {
		if len(imports) == 1 {
			fmt.Fprintf(&b, "import %s\n\n", goStr(imports[0]))
		} else {
			b.WriteString("import (\n")
			for _, imp := range imports {
				fmt.Fprintf(&b, "\t%s\n", goStr(imp))
			}
			b.WriteString(")\n\n")
		}
	}

	// Emit each variable definition (preserving YAML order).
	for i := 0; i < len(doc.Content); i += 2 {
		varName := doc.Content[i].Value
		if strings.HasPrefix(varName, "_") {
			continue
		}
		varDef := doc.Content[i+1]
		if varDef.Kind != yaml.MappingNode {
			continue
		}

		typeStr := "map[string]string"
		if v := nodeGet(varDef, "_type"); v != nil {
			typeStr = v.Value
		}

		if docNode := nodeGet(varDef, "_doc"); docNode != nil {
			for _, line := range strings.Split(docNode.Value, "\n") {
				fmt.Fprintf(&b, "// %s\n", line)
			}
		}

		var valueMap map[string]string
		if vm := nodeGet(varDef, "_value_map"); vm != nil {
			valueMap = make(map[string]string)
			for j := 0; j < len(vm.Content); j += 2 {
				valueMap[vm.Content[j].Value] = vm.Content[j+1].Value
			}
		}

		values := nodeGet(varDef, "_values")

		keyType, valType := parseMapType(typeStr)
		if keyType != "" {
			// Map type.
			fmt.Fprintf(&b, "var %s = %s{\n", varName, typeStr)
			if values != nil && values.Kind == yaml.MappingNode {
				for j := 0; j < len(values.Content); j += 2 {
					k := values.Content[j].Value
					v := values.Content[j+1]
					fmt.Fprintf(&b, "\t%s: %s,\n", renderKey(k, keyType), renderValue(v, valType, valueMap))
				}
			}
			b.WriteString("}\n\n")
		} else if elemType := parseSliceType(typeStr); elemType != "" {
			// Slice type.
			if values != nil && values.Kind == yaml.SequenceNode {
				fmt.Fprintf(&b, "var %s = %s{\n", varName, typeStr)
				for _, item := range values.Content {
					fmt.Fprintf(&b, "\t%s,\n", renderValue(item, elemType, valueMap))
				}
				b.WriteString("}\n\n")
			}
		}
	}

	return b.String()
}

// ---------------------------------------------------------------------------
// Value rendering
// ---------------------------------------------------------------------------

func renderKey(key, keyType string) string {
	if keyType == "string" {
		return goStr(key)
	}
	return key
}

func renderValue(node *yaml.Node, goType string, valueMap map[string]string) string {
	// Check value_map shorthand first.
	if len(valueMap) > 0 && node.Kind == yaml.ScalarNode {
		if replacement, ok := valueMap[node.Value]; ok {
			return replacement
		}
	}

	// Slice type → recurse into elements.
	if elemType := parseSliceType(goType); elemType != "" {
		if node.Kind == yaml.SequenceNode {
			items := make([]string, len(node.Content))
			for i, item := range node.Content {
				items[i] = renderValue(item, elemType, valueMap)
			}
			return goType + "{" + strings.Join(items, ", ") + "}"
		}
		// Single scalar → wrap in slice.
		return goType + "{" + renderValue(node, elemType, valueMap) + "}"
	}

	// Scalar types.
	switch goType {
	case "string":
		return goStr(node.Value)
	case "bool":
		if node.Value == "true" {
			return "true"
		}
		return "false"
	case "float64":
		if node.Tag == "!!int" {
			return node.Value + ".0"
		}
		return node.Value
	case "int":
		return node.Value
	default:
		// Custom type (e.g. auth.Scope) — use as-is.
		return node.Value
	}
}

// ---------------------------------------------------------------------------
// Type parsing
// ---------------------------------------------------------------------------

var mapTypeRe = regexp.MustCompile(`^map\[([^\]]+)\](.+)$`)

func parseMapType(t string) (keyType, valType string) {
	m := mapTypeRe.FindStringSubmatch(t)
	if m == nil {
		return "", t
	}
	return m[1], m[2]
}

func parseSliceType(t string) string {
	if strings.HasPrefix(t, "[]") {
		return t[2:]
	}
	return ""
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func nodeGet(mapping *yaml.Node, key string) *yaml.Node {
	for i := 0; i < len(mapping.Content); i += 2 {
		if mapping.Content[i].Value == key {
			return mapping.Content[i+1]
		}
	}
	return nil
}

func goStr(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	s = strings.ReplaceAll(s, "\t", `\t`)
	return `"` + s + `"`
}
