// data-gen generates Go variable declarations from JSON data files.
//
// Universal code generator for data-driven Go code. Reads a JSON file
// containing variable definitions with type metadata and generates
// corresponding Go source code.
//
// Usage (from gateway-go/):
//
//	go run cmd/data-gen/main.go \
//	    -json internal/pipeline/chat/tool_classification.json \
//	    -out  internal/pipeline/chat/tool_classification_gen.go
//
// Or via Makefile: make data-gen
//
// JSON format:
//
//	{
//	  "_gen": {
//	    "package": "<go-package-name>",
//	    "imports": ["<import-path>", ...],
//	    "build_tags": "<tags>"
//	  },
//	  "<varName>": {
//	    "_type": "<go-type>",
//	    "_doc": "<comment>",
//	    "_value_map": { "short": "GoExpr" },
//	    "_values": { ... }
//	  }
//	}
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

func main() {
	jsonFile := flag.String("json", "", "JSON source file")
	outFile := flag.String("out", "", "Output Go file")
	flag.Parse()

	if *jsonFile == "" || *outFile == "" {
		fmt.Fprintln(os.Stderr, "usage: data-gen -json FILE -out FILE")
		os.Exit(1)
	}

	data, err := os.ReadFile(*jsonFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	var doc map[string]any
	if err := json.Unmarshal(data, &doc); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	// Derive source path for the header comment.
	sourcePath := *jsonFile
	if abs, err := filepath.Abs(*jsonFile); err == nil {
		if idx := strings.Index(abs, "/gateway-go/"); idx >= 0 {
			sourcePath = abs[idx+1:]
		}
	}

	src := generate(doc, sourcePath)

	formatted, err := format.Source([]byte(src))
	if err != nil {
		fmt.Fprintf(os.Stderr, "gofmt warning: %v\n", err)
		formatted = []byte(src)
	}

	if err := os.WriteFile(*outFile, formatted, 0o600); err != nil { //nolint:gosec // G306 — generated source file, needs read access
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	nVars, nEntries := 0, 0
	for k, v := range doc {
		if strings.HasPrefix(k, "_") {
			continue
		}
		varDef, ok := v.(map[string]any)
		if !ok {
			continue
		}
		nVars++
		if values := varDef["_values"]; values != nil {
			switch vals := values.(type) {
			case map[string]any:
				nEntries += len(vals)
			case []any:
				nEntries += len(vals)
			}
		}
	}
	fmt.Printf("wrote %s (%d vars, %d entries)\n", *outFile, nVars, nEntries)
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

func generate(doc map[string]any, sourcePath string) string {
	gen, _ := doc["_gen"].(map[string]any)
	pkg := "main"
	var imports []string
	buildTags := ""

	if gen != nil {
		if v, ok := gen["package"].(string); ok {
			pkg = v
		}
		if v, ok := gen["imports"].([]any); ok {
			for _, item := range v {
				s, _ := item.(string)
				imports = append(imports, s)
			}
		}
		if v, ok := gen["build_tags"].(string); ok {
			buildTags = v
		}
	}

	var b strings.Builder

	if buildTags != "" {
		fmt.Fprintf(&b, "//go:build %s\n\n", buildTags)
	}

	b.WriteString("// Code generated by data-gen. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: %s\n", sourcePath)
	b.WriteString("// Regenerate: make data-gen\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	if len(imports) > 0 {
		if len(imports) == 1 {
			fmt.Fprintf(&b, "import %s\n\n", goStr(imports[0]))
		} else {
			b.WriteString("import (\n")
			for _, imp := range imports {
				fmt.Fprintf(&b, "\t%s\n", goStr(imp))
			}
			b.WriteString(")\n\n")
		}
	}

	// Collect and sort variable names for deterministic output.
	varNames := make([]string, 0)
	for k := range doc {
		if !strings.HasPrefix(k, "_") {
			if _, ok := doc[k].(map[string]any); ok {
				varNames = append(varNames, k)
			}
		}
	}
	sort.Strings(varNames)

	// Emit each variable definition.
	for _, varName := range varNames {
		varDef := doc[varName].(map[string]any)

		typeStr := "map[string]string"
		if v, ok := varDef["_type"].(string); ok {
			typeStr = v
		}

		if docStr, ok := varDef["_doc"].(string); ok {
			for _, line := range strings.Split(docStr, "\n") {
				fmt.Fprintf(&b, "// %s\n", line)
			}
		}

		var valueMap map[string]string
		if vm, ok := varDef["_value_map"].(map[string]any); ok {
			valueMap = make(map[string]string)
			for k, v := range vm {
				s, _ := v.(string)
				valueMap[k] = s
			}
		}

		values := varDef["_values"]

		keyType, valType := parseMapType(typeStr)
		if keyType != "" {
			// Map type.
			fmt.Fprintf(&b, "var %s = %s{\n", varName, typeStr)
			if valMap, ok := values.(map[string]any); ok {
				keys := sortedKeys(valMap)
				for _, k := range keys {
					v := valMap[k]
					fmt.Fprintf(&b, "\t%s: %s,\n", renderKey(k, keyType), renderValue(v, valType, valueMap))
				}
			}
			b.WriteString("}\n\n")
		} else if elemType := parseSliceType(typeStr); elemType != "" {
			// Slice type.
			if arr, ok := values.([]any); ok {
				fmt.Fprintf(&b, "var %s = %s{\n", varName, typeStr)
				for _, item := range arr {
					fmt.Fprintf(&b, "\t%s,\n", renderValue(item, elemType, valueMap))
				}
				b.WriteString("}\n\n")
			}
		}
	}

	return b.String()
}

// ---------------------------------------------------------------------------
// Value rendering
// ---------------------------------------------------------------------------

func renderKey(key, keyType string) string {
	if keyType == "string" {
		return goStr(key)
	}
	return key
}

func renderValue(val any, goType string, valueMap map[string]string) string {
	// Check value_map shorthand first.
	if len(valueMap) > 0 {
		if s, ok := val.(string); ok {
			if replacement, ok := valueMap[s]; ok {
				return replacement
			}
		}
	}

	// Slice type -> recurse into elements.
	if elemType := parseSliceType(goType); elemType != "" {
		if arr, ok := val.([]any); ok {
			items := make([]string, len(arr))
			for i, item := range arr {
				items[i] = renderValue(item, elemType, valueMap)
			}
			return goType + "{" + strings.Join(items, ", ") + "}"
		}
		// Single value -> wrap in slice.
		return goType + "{" + renderValue(val, elemType, valueMap) + "}"
	}

	// Scalar types.
	switch goType {
	case "string":
		s, _ := val.(string)
		return goStr(s)
	case "bool":
		if b, ok := val.(bool); ok && b {
			return "true"
		}
		return "false"
	case "float64":
		if f, ok := val.(float64); ok {
			if f == float64(int64(f)) {
				return fmt.Sprintf("%d.0", int64(f))
			}
			return fmt.Sprintf("%v", f)
		}
		return fmt.Sprintf("%v", val)
	case "int":
		if f, ok := val.(float64); ok {
			return fmt.Sprintf("%d", int64(f))
		}
		return fmt.Sprintf("%v", val)
	case "struct{}":
		return "{}"
	default:
		// Custom type (e.g. auth.Scope) — use as-is.
		return fmt.Sprintf("%v", val)
	}
}

// ---------------------------------------------------------------------------
// Type parsing
// ---------------------------------------------------------------------------

var mapTypeRe = regexp.MustCompile(`^map\[([^\]]+)\](.+)$`)

func parseMapType(t string) (keyType, valType string) {
	m := mapTypeRe.FindStringSubmatch(t)
	if m == nil {
		return "", t
	}
	return m[1], m[2]
}

func parseSliceType(t string) string {
	if strings.HasPrefix(t, "[]") {
		return t[2:]
	}
	return ""
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func goStr(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	s = strings.ReplaceAll(s, "\t", `\t`)
	return `"` + s + `"`
}
