#!/usr/bin/env python3
"""model-caps-gen: generate model capability vars from model_caps.yaml.

Usage (from gateway-go/):
    python3 cmd/model-caps-gen/gen.py \
        -yaml internal/autoreply/thinking/model_caps.yaml \
        -out  internal/autoreply/thinking/model_caps_gen.go

Or via Makefile:
    make model-caps
"""

import argparse
import subprocess
import sys
import yaml


def go_str(s: str) -> str:
    """Produce a Go double-quoted string literal."""
    s = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")
    return f'"{s}"'


def generate(data: dict) -> str:
    lines = [
        "// Code generated by model-caps-gen. DO NOT EDIT.",
        "// Source: gateway-go/internal/autoreply/thinking/model_caps.yaml",
        "// Regenerate: make model-caps",
        "",
        "package thinking",
        "",
        'import "regexp"',
        "",
    ]

    # xhigh_thinking: map[string][]string
    xhigh = data.get("xhigh_thinking", {})
    lines.append("// xhighThinkingModelIDs maps normalized provider IDs to model ID lists that")
    lines.append("// support xhigh thinking. Matching uses exact equality or prefix.")
    lines.append("var xhighThinkingModelIDs = map[string][]string{")
    for provider, models in sorted(xhigh.items()):
        items = ", ".join(go_str(m) for m in models)
        lines.append(f"\t{go_str(provider)}: {{{items}}},")
    lines.append("}")
    lines.append("")

    # adaptive_thinking_patterns: map[string]*regexp.Regexp
    patterns = data.get("adaptive_thinking_patterns", {})
    lines.append("// adaptiveThinkingModelRes maps normalized provider IDs to compiled regexes")
    lines.append("// that identify models defaulting to adaptive thinking.")
    lines.append("var adaptiveThinkingModelRes = map[string]*regexp.Regexp{")
    for provider, pattern in sorted(patterns.items()):
        # Use raw Go backtick string for regexes to avoid double-escaping.
        lines.append(f"\t{go_str(provider)}: regexp.MustCompile(`{pattern}`),")
    lines.append("}")
    lines.append("")

    return "\n".join(lines) + "\n"


def main() -> None:
    p = argparse.ArgumentParser(description="Generate model capability vars from YAML")
    p.add_argument("-yaml", required=True, dest="yaml_file", metavar="FILE")
    p.add_argument("-out", required=True, dest="out_file", metavar="FILE")
    args = p.parse_args()

    with open(args.yaml_file, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    if not isinstance(data, dict):
        print("error: YAML root must be a mapping", file=sys.stderr)
        sys.exit(1)

    src = generate(data)

    # Run gofmt for canonical formatting.
    result = subprocess.run(["gofmt"], input=src, capture_output=True, text=True)
    if result.returncode == 0:
        src = result.stdout
    else:
        print(f"gofmt warning: {result.stderr}", file=sys.stderr)

    with open(args.out_file, "w", encoding="utf-8") as f:
        f.write(src)

    n_xhigh = sum(len(v) for v in data.get("xhigh_thinking", {}).values())
    n_pat = len(data.get("adaptive_thinking_patterns", {}))
    print(f"wrote {args.out_file} ({n_xhigh} xhigh model IDs, {n_pat} adaptive patterns)")


if __name__ == "__main__":
    main()
