// model-caps-gen generates model capability vars from model_caps.json.
//
// Usage (from gateway-go/):
//
//	go run cmd/model-caps-gen/main.go \
//	    -json internal/pipeline/autoreply/thinking/model_caps.json \
//	    -out  internal/pipeline/autoreply/thinking/model_caps_gen.go
//
// Or via Makefile: make model-caps
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

func main() {
	jsonFile := flag.String("json", "", "JSON source file")
	outFile := flag.String("out", "", "Output Go file")
	flag.Parse()

	if *jsonFile == "" || *outFile == "" {
		fmt.Fprintln(os.Stderr, "usage: model-caps-gen -json FILE -out FILE")
		os.Exit(1)
	}

	data, err := os.ReadFile(*jsonFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	var doc map[string]any
	if err := json.Unmarshal(data, &doc); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	src := generate(doc)

	formatted, err := format.Source([]byte(src))
	if err != nil {
		fmt.Fprintf(os.Stderr, "gofmt warning: %v\n", err)
		formatted = []byte(src)
	}

	if err := os.WriteFile(*outFile, formatted, 0o600); err != nil { //nolint:gosec // G306 — generated source file, needs read access
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	nXhigh, nPat := 0, 0
	if xh, ok := doc["xhigh_thinking"].(map[string]any); ok {
		for _, v := range xh {
			if arr, ok := v.([]any); ok {
				nXhigh += len(arr)
			}
		}
	}
	if ap, ok := doc["adaptive_thinking_patterns"].(map[string]any); ok {
		nPat = len(ap)
	}
	fmt.Printf("wrote %s (%d xhigh model IDs, %d adaptive patterns)\n", *outFile, nXhigh, nPat)
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

func generate(doc map[string]any) string {
	var b strings.Builder

	b.WriteString("// Code generated by model-caps-gen. DO NOT EDIT.\n")
	b.WriteString("// Source: gateway-go/internal/pipeline/autoreply/thinking/model_caps.json\n")
	b.WriteString("// Regenerate: make model-caps\n\n")
	b.WriteString("package thinking\n\n")
	b.WriteString("import \"regexp\"\n\n")

	// xhigh_thinking: map[string][]string (sorted by provider).
	if xhigh, ok := doc["xhigh_thinking"].(map[string]any); ok {
		providers := sortedKeys(xhigh)

		b.WriteString("// xhighThinkingModelIDs maps normalized provider IDs to model ID lists that\n")
		b.WriteString("// support xhigh thinking. Matching uses exact equality or prefix.\n")
		b.WriteString("var xhighThinkingModelIDs = map[string][]string{\n")
		for _, provider := range providers {
			models, ok := xhigh[provider].([]any)
			if !ok {
				continue
			}
			strs := make([]string, len(models))
			for i, m := range models {
				s, _ := m.(string)
				strs[i] = goStr(s)
			}
			fmt.Fprintf(&b, "\t%s: {%s},\n", goStr(provider), strings.Join(strs, ", "))
		}
		b.WriteString("}\n\n")
	}

	// adaptive_thinking_patterns: map[string]*regexp.Regexp (sorted by provider).
	if patterns, ok := doc["adaptive_thinking_patterns"].(map[string]any); ok {
		providers := sortedKeys(patterns)

		b.WriteString("// adaptiveThinkingModelRes maps normalized provider IDs to compiled regexes\n")
		b.WriteString("// that identify models defaulting to adaptive thinking.\n")
		b.WriteString("var adaptiveThinkingModelRes = map[string]*regexp.Regexp{\n")
		for _, provider := range providers {
			pattern, _ := patterns[provider].(string)
			fmt.Fprintf(&b, "\t%s: regexp.MustCompile(`%s`),\n", goStr(provider), pattern)
		}
		b.WriteString("}\n")
	}

	return b.String()
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func goStr(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	s = strings.ReplaceAll(s, "\t", `\t`)
	return `"` + s + `"`
}
