// model-caps-gen generates model capability vars from model_caps.yaml.
//
// Usage (from gateway-go/):
//
//	go run cmd/model-caps-gen/main.go \
//	    -yaml internal/pipeline/autoreply/thinking/model_caps.yaml \
//	    -out  internal/pipeline/autoreply/thinking/model_caps_gen.go
//
// Or via Makefile: make model-caps
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	yamlFile := flag.String("yaml", "", "YAML source file")
	outFile := flag.String("out", "", "Output Go file")
	flag.Parse()

	if *yamlFile == "" || *outFile == "" {
		fmt.Fprintln(os.Stderr, "usage: model-caps-gen -yaml FILE -out FILE")
		os.Exit(1)
	}

	data, err := os.ReadFile(*yamlFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	var root yaml.Node
	if err := yaml.Unmarshal(data, &root); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	if root.Kind != yaml.DocumentNode || len(root.Content) == 0 ||
		root.Content[0].Kind != yaml.MappingNode {
		fmt.Fprintln(os.Stderr, "error: YAML root must be a mapping")
		os.Exit(1)
	}

	doc := root.Content[0]
	src := generate(doc)

	formatted, err := format.Source([]byte(src))
	if err != nil {
		fmt.Fprintf(os.Stderr, "gofmt warning: %v\n", err)
		formatted = []byte(src)
	}

	if err := os.WriteFile(*outFile, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	nXhigh := 0
	if xh := nodeGet(doc, "xhigh_thinking"); xh != nil {
		for i := 1; i < len(xh.Content); i += 2 {
			nXhigh += len(xh.Content[i].Content)
		}
	}
	nPat := 0
	if ap := nodeGet(doc, "adaptive_thinking_patterns"); ap != nil {
		nPat = len(ap.Content) / 2
	}
	fmt.Printf("wrote %s (%d xhigh model IDs, %d adaptive patterns)\n", *outFile, nXhigh, nPat)
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

func generate(doc *yaml.Node) string {
	var b strings.Builder

	b.WriteString("// Code generated by model-caps-gen. DO NOT EDIT.\n")
	b.WriteString("// Source: gateway-go/internal/pipeline/autoreply/thinking/model_caps.yaml\n")
	b.WriteString("// Regenerate: make model-caps\n\n")
	b.WriteString("package thinking\n\n")
	b.WriteString("import \"regexp\"\n\n")

	// xhigh_thinking: map[string][]string (sorted by provider).
	if xhigh := nodeGet(doc, "xhigh_thinking"); xhigh != nil {
		type entry struct {
			provider string
			models   *yaml.Node
		}
		var entries []entry
		for i := 0; i < len(xhigh.Content); i += 2 {
			entries = append(entries, entry{xhigh.Content[i].Value, xhigh.Content[i+1]})
		}
		sort.Slice(entries, func(i, j int) bool { return entries[i].provider < entries[j].provider })

		b.WriteString("// xhighThinkingModelIDs maps normalized provider IDs to model ID lists that\n")
		b.WriteString("// support xhigh thinking. Matching uses exact equality or prefix.\n")
		b.WriteString("var xhighThinkingModelIDs = map[string][]string{\n")
		for _, e := range entries {
			models := make([]string, len(e.models.Content))
			for i, m := range e.models.Content {
				models[i] = goStr(m.Value)
			}
			fmt.Fprintf(&b, "\t%s: {%s},\n", goStr(e.provider), strings.Join(models, ", "))
		}
		b.WriteString("}\n\n")
	}

	// adaptive_thinking_patterns: map[string]*regexp.Regexp (sorted by provider).
	if patterns := nodeGet(doc, "adaptive_thinking_patterns"); patterns != nil {
		type entry struct {
			provider string
			pattern  string
		}
		var entries []entry
		for i := 0; i < len(patterns.Content); i += 2 {
			entries = append(entries, entry{patterns.Content[i].Value, patterns.Content[i+1].Value})
		}
		sort.Slice(entries, func(i, j int) bool { return entries[i].provider < entries[j].provider })

		b.WriteString("// adaptiveThinkingModelRes maps normalized provider IDs to compiled regexes\n")
		b.WriteString("// that identify models defaulting to adaptive thinking.\n")
		b.WriteString("var adaptiveThinkingModelRes = map[string]*regexp.Regexp{\n")
		for _, e := range entries {
			fmt.Fprintf(&b, "\t%s: regexp.MustCompile(`%s`),\n", goStr(e.provider), e.pattern)
		}
		b.WriteString("}\n")
	}

	return b.String()
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func nodeGet(mapping *yaml.Node, key string) *yaml.Node {
	for i := 0; i < len(mapping.Content); i += 2 {
		if mapping.Content[i].Value == key {
			return mapping.Content[i+1]
		}
	}
	return nil
}

func goStr(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	s = strings.ReplaceAll(s, "\t", `\t`)
	return `"` + s + `"`
}
