#!/usr/bin/env python3
"""Decision miner: harvest change rationale out of git history into memory.

The session-memory hooks already capture a deterministic *skeleton* of each
coding session (branch, commits, files) and reserve ``card.md`` for the
semantic layer -- decisions, lessons, self-corrections. That semantic half has
never been written: it depends on an agent voluntarily updating a file, and the
observed hit rate across every session on record is zero.

The rationale is not actually missing, though. It is sitting in commit bodies:
of the last 400 first-parent commits, 128 (32%) carry six or more lines of
prose once the mechanical noise is stripped, median 12 and up to 247 --
squash-merge preserves the whole PR narrative ("this was a deliberate call, not
a cleanup that fell out of something else"). Nobody reads it because nothing
surfaces it.

So this miner takes the artifact that already exists instead of asking an agent
to produce a new one. It walks first-parent history, keeps the commits whose
body carries real prose, strips the mechanical noise squash-merge adds, and
files each as a decision record keyed by the paths it touched -- so a later
session editing those paths can be shown why they look the way they do.

Deterministic: pure local git, no network, no LLM. Incremental: a cursor marks
the newest commit already mined, so a run costs only the new commits.

Write path: ``~/.claude/deneb-session-memory/decisions.jsonl``, the same
operator-owned memory dir the session-memory hooks own. This is NOT an audit
script -- ``scripts/audit`` Python must not write ledgers.
"""

from __future__ import annotations

import argparse
import contextlib
import json
import os
import re
import subprocess
import sys
import time

MEM_DIR = os.path.expanduser("~/.claude/deneb-session-memory")
DECISIONS = os.path.join(MEM_DIR, "decisions.jsonl")
CURSOR = os.path.join(MEM_DIR, "decisions.cursor")

# Bodies shorter than this are a subject with a stray trailer, not reasoning.
# Calibrated on Deneb's own history: measured AFTER clean_body, six lines keeps
# 128 of the last 400 first-parent commits (32%, median 12). The threshold is
# applied to cleaned prose on purpose -- a squash body is padded with subject
# echoes and generated footers, so raw line count would pass commits that say
# nothing.
MIN_BODY_LINES = 6

# A first run should not walk 6k commits; later runs stop at the cursor anyway.
DEFAULT_LIMIT = 400
MAX_FILES = 12
MAX_BODY_CHARS = 2000
MAX_RECORDS = 2000

# How old a lock must be before its owner counts as gone. Well above the
# slowest legitimate hold (a cold 400-commit mine is ~0.4s) so a live holder is
# never mistaken for a dead one.
STALE_LOCK_SECONDS = 120.0

# Trailers and generated footers. These are mechanically appended, carry no
# rationale, and would otherwise dominate the short bodies.
_NOISE_PREFIXES = (
    "co-authored-by:",
    "claude-session:",
    "signed-off-by:",
    "generated with",
    "🤖 generated with",
    "_generated by",
    "reviewed by",
)

# Squash-merge repeats each squashed commit's subject as a "* subject" bullet
# before the prose. Only those echoes are dropped: matching every asterisk
# bullet also deleted ordinary Markdown lists, and a body that argued its case
# in six bullet points was cleaned down to nothing and never mined.
_SQUASH_ECHO = re.compile(r"^\s*\*\s+(?P<text>\S.*)$")

# Real PR numbers are a handful of digits; anything near CPython's conversion
# limit is a crafted subject, not a number.
MAX_PR_DIGITS = 12

# Bot review blocks (Cursor Bugbot's "> [!NOTE]" summary) ride into some PR
# bodies. They describe the diff back to us -- not the author's reasoning.
_BLOCKQUOTE = re.compile(r"^\s*>")

# Comment spans are removed by scanning, not by a regex. A line-anchored
# pattern only ever sees one line, so a comment that spans several lines slips
# through whole -- every one of its markup lines then counts toward
# MIN_BODY_LINES, which is the inflation this filter exists to stop.
_COMMENT_OPEN, _COMMENT_CLOSE = "<!--", "-->"

_CONVENTIONAL = re.compile(r"^(?P<type>[a-z]+)(?:\((?P<scope>[^)]*)\))?(?P<bang>!?):\s")
_PR_NUMBER = re.compile(r"\(#(\d+)\)\s*$")

# Records are split on a control byte, and nothing stops a commit message from
# containing that byte: a crafted body can forge a record boundary and put its
# own text where the object name belongs. That name is then handed to `git
# show`, where a value like `--output=<path>` is not a revision but an option
# that WRITES the file it names. So an object name is accepted only if it looks
# exactly like one -- 40 hex digits can never be an option.
# Records are delimited by NUL, the one byte a commit message cannot carry:
# git takes messages through argv or a file and rejects an embedded NUL, so no
# crafted body can forge a field or record boundary. Earlier revisions used
# control characters a message CAN contain and defended with shape checks --
# which held the line one field at a time and lost it whenever a field was
# added. The shape checks stay as a second layer, but the delimiter is what
# makes the forgery impossible rather than merely detected.
# The format string itself travels through argv, so it cannot hold a literal
# NUL either; `%x00` is git's escape for emitting one.
_NUL = "\x00"
_FIELD_COUNT = 5
_FIELDS = "%x00".join(["%H", "%h", "%aI", "%s", "%b"]) + "%x00"

_OBJECT_NAME = re.compile(r"^[0-9a-f]{40}$")

# The same forgery reaches the OTHER git-supplied fields, and those flow
# straight into the injected SessionStart block. Validating only the name that
# goes to `git show` guarded the command and left the output unguarded: a
# forged record could carry the closing fence tag in `short` and end the
# untrusted span early. git decides both of these shapes, so anything that does
# not match them is not a git record.
_SHORT_NAME = re.compile(r"^[0-9a-f]{4,40}$")
_ISO_DATE = re.compile(r"^\d{4}-\d{2}-\d{2}")


class ScanFailed(Exception):
    """The history scan did not run, as distinct from finding nothing."""


def git_run(*args, cwd=None):
    """Run git, returning (stdout stripped, ok). `ok` is False on any failure."""
    try:
        out = subprocess.run(
            ["git", *(["-C", cwd] if cwd else []), *args],
            capture_output=True,
            text=True,
            timeout=30,
        )
        return (out.stdout.strip(), True) if out.returncode == 0 else ("", False)
    except Exception:
        return "", False


def git(*args, cwd=None):
    """Run git, returning stdout stripped, or '' on any failure.

    Collapses failure into the empty string, so only use it where an empty
    result and a failed command call for the same handling. Where they do not
    -- the history scan, whose empty result advances the cursor -- use
    `git_run` and act on `ok`.
    """
    return git_run(*args, cwd=cwd)[0]


@contextlib.contextmanager
def memory_lock(name="memory", timeout=5.0, stale_after=STALE_LOCK_SECONDS, mem_dir=None):
    """Serialize a whole read-modify-write against the shared memory dir.

    Atomic replacement alone is not enough here. Two SessionEnd processes can
    each read the same snapshot and then replace it in turn: the later write
    simply omits the earlier one's work, and since nothing raises, no fallback
    triggers. The memory dir is shared across every worktree on purpose, so
    simultaneous ends are a real case, not a theoretical one.

    O_CREAT|O_EXCL because it is the one primitive that behaves the same on
    POSIX and Windows without a dependency.

    Waiting and reclaiming are separate questions, and conflating them is a bug:
    a slow-but-live holder (a cold mine catching up) is not an abandoned one, so
    a lock is only stolen once it is `stale_after` old, never merely because we
    waited. Running out of patience yields False instead -- and callers must
    honour that, because proceeding unlocked is exactly the overwrite the lock
    exists to prevent.

    Release checks the token it wrote. Without that, a holder that timed out
    against a stolen lock would delete whichever lock file exists at the end --
    which by then can belong to someone else, cascading the theft.
    """
    directory = mem_dir or MEM_DIR
    path = os.path.join(directory, f".{name}.lock")
    token = f"{os.getpid()}:{time.monotonic_ns()}"
    acquired = False
    try:
        os.makedirs(directory, exist_ok=True)
        deadline = time.monotonic() + timeout
        while True:
            try:
                fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
                try:
                    os.write(fd, token.encode())
                finally:
                    os.close(fd)
                acquired = True
                break
            except FileExistsError:
                if _lock_is_stale(path, stale_after):
                    # The owner is gone: nothing will ever release this.
                    try:
                        os.unlink(path)
                    except OSError:
                        pass
                    continue
                if time.monotonic() >= deadline:
                    break
                time.sleep(0.05)
    except Exception:
        pass
    try:
        yield acquired
    finally:
        if acquired and _lock_token(path) == token:
            try:
                os.unlink(path)
            except OSError:
                pass


def _lock_token(path):
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            return f.read().strip()
    except OSError:
        return None


def _lock_is_stale(path, stale_after):
    """True when the lock is old enough that its owner cannot still be running."""
    try:
        return (time.time() - os.path.getmtime(path)) > stale_after
    except OSError:
        # Gone between the failed create and this check -- retry, do not steal.
        return False


def is_ancestor(older: str, newer: str, cwd=None) -> bool:
    """True when `older` is reachable from `newer`. Exit-status only."""
    try:
        return subprocess.run(
            ["git", *(["-C", cwd] if cwd else []), "merge-base", "--is-ancestor", older, newer],
            capture_output=True,
            text=True,
            timeout=30,
        ).returncode == 0
    except Exception:
        return False


def strip_comment_spans(raw: str) -> str:
    """Remove `<!-- ... -->` spans, however many lines they cover.

    Scanned rather than matched: comments are not a line-shaped construct, and
    a per-line pattern lets a multi-line one through intact. An unterminated
    opener drops everything after it -- a comment nobody closed has no readable
    end, and guessing one would put markup back in the rationale.
    """
    out, i = [], 0
    text = raw or ""
    while True:
        start = text.find(_COMMENT_OPEN, i)
        if start < 0:
            out.append(text[i:])
            return "".join(out)
        out.append(text[i:start])
        end = text.find(_COMMENT_CLOSE, start + len(_COMMENT_OPEN))
        if end < 0:
            return "".join(out)
        i = end + len(_COMMENT_CLOSE)


def clean_body(raw: str) -> list[str]:
    """Strip squash echoes, trailers, and bot blocks; keep the prose.

    Returns the surviving lines with blank runs collapsed, so line counts mean
    "lines of reasoning" rather than "lines of whitespace and boilerplate".
    """
    kept: list[str] = []
    seen_prose = False
    for line in strip_comment_spans(raw).splitlines():
        stripped = line.strip()
        low = stripped.lower()
        if not stripped:
            # Collapse blank runs; never lead with one.
            if kept and kept[-1] != "":
                kept.append("")
            continue
        if any(low.startswith(p) for p in _NOISE_PREFIXES):
            continue
        if _BLOCKQUOTE.match(line):
            continue
        # A bare rule is only ever a separator before a generated footer.
        if set(stripped) <= {"-", "*", "_"} and len(stripped) >= 3:
            continue
        echo = _SQUASH_ECHO.match(line)
        if echo:
            # Squash echoes are the squashed subjects and always sit in the
            # preamble, so only subject-shaped bullets there are dropped -- a
            # bullet after real prose is the author writing a list, and
            # dropping every bullet cleaned a body that argued its case in six
            # points down to nothing.
            #
            # A bullet never opens the gate, whatever its shape. Letting one
            # do so meant a single odd squashed subject (`* WIP`, `* typo`)
            # admitted every conventional echo behind it, so a body that was
            # nothing but a commit list cleared MIN_BODY_LINES with no
            # rationale at all.
            if not seen_prose and _CONVENTIONAL.match(echo.group("text")):
                continue
            kept.append(stripped)
            continue
        seen_prose = True
        kept.append(stripped)
    while kept and kept[-1] == "":
        kept.pop()
    return kept


def parse_subject(subject: str):
    """Split a conventional-commit subject into type, scope, and PR number."""
    ctype = scope = None
    breaking = False
    m = _CONVENTIONAL.match(subject or "")
    if m:
        ctype = m.group("type")
        scope = m.group("scope") or None
        breaking = bool(m.group("bang"))
    # A subject is contributor-controlled and git caps neither its length nor
    # this suffix, so the digits are bounded before int(): CPython raises on a
    # conversion past 4300 digits, and that exception would abort the whole
    # generator -- leaving the cursor stuck on that commit run after run.
    pr = None
    p = _PR_NUMBER.search(subject or "")
    if p and len(p.group(1)) <= MAX_PR_DIGITS:
        pr = int(p.group(1))
    return ctype, scope, breaking, pr


def touched_areas(files: list[str]) -> list[str]:
    """Coarse areas a decision applies to, for cheap relevance matching later.

    Two levels: the module root (``gateway-go``) and the package directory
    (``gateway-go/internal/runtime/mcpapi``). Matching on the directory rather
    than the file is deliberate -- a decision about a package still explains a
    sibling file that did not happen to change in that commit.
    """
    areas: list[str] = []
    for f in files:
        parts = f.split("/")
        if len(parts) >= 1 and parts[0]:
            areas.append(parts[0])
        if len(parts) >= 2:
            areas.append(os.path.dirname(f))
    seen, out = set(), []
    for a in areas:
        if a and a not in seen:
            seen.add(a)
            out.append(a)
    return out


def commit_records(ref: str, limit: int, since: str | None, cwd=None):
    """Yield decision records for first-parent commits carrying rationale.

    `limit` caps the COLD scan only. Applying it to a cursor range silently
    drops history: the walk returns the newest `limit` commits, mine() then
    advances the cursor to head, and everything older in that range is never
    looked at again. A cursor range is already bounded by real activity, so it
    needs no cap -- catching up after a long gap is a one-time cost, and
    correctness is worth more here than a bounded worst case.
    """
    rng = f"{since}..{ref}" if since else ref
    args = ["log", "--first-parent"]
    if not since:
        args += ["-n", str(limit)]
    raw, ok = git_run(
        *args,
        f"--format={_FIELDS}",
        rng,
        cwd=cwd,
    )
    # A failed scan and a scan that found nothing both come back empty, and the
    # caller advances the cursor on an empty result -- so collapsing them means
    # one transient git failure permanently skips that whole range.
    if not ok:
        raise ScanFailed(f"git log failed for {rng}")
    if not raw:
        return

    # Fixed-width records over a delimiter no message can contain, so the field
    # and record boundaries are decided by git alone. The trailing separator
    # leaves one empty tail element; drop it before grouping.
    fields = raw.split(_NUL)
    if fields and not fields[-1].strip():
        fields.pop()
    for i in range(0, len(fields) - _FIELD_COUNT + 1, _FIELD_COUNT):
        full, short, when, subject, body_raw = (
            fields[i].strip(), fields[i + 1].strip(), fields[i + 2].strip(),
            fields[i + 3], fields[i + 4],
        )
        # Belt and braces on top of the delimiter: still the shapes git emits.
        if not (
            _OBJECT_NAME.match(full)
            and _SHORT_NAME.match(short)
            and _ISO_DATE.match(when)
        ):
            continue
        body = clean_body(body_raw)
        prose = [ln for ln in body if ln]
        if len(prose) < MIN_BODY_LINES:
            continue
        # This scan feeds `areas`, which is the whole matching signal. Treating
        # a failed `git show` as "no files" would store a decision that can
        # never match anything, and the cursor would move past it for good.
        shown, shown_ok = git_run("show", "--name-only", "--format=", full, "--", cwd=cwd)
        if not shown_ok:
            raise ScanFailed(f"git show failed for {full}")
        files = [ln for ln in shown.splitlines() if ln]
        ctype, scope, breaking, pr = parse_subject(subject)
        yield {
            "commit": short,
            "sha": full,
            "date": when[:10],
            "subject": subject,
            "type": ctype,
            "scope": scope,
            "breaking": breaking,
            "pr": pr,
            "rationale": "\n".join(body)[:MAX_BODY_CHARS],
            "rationale_lines": len(prose),
            "files": files[:MAX_FILES],
            "files_total": len(files),
            "areas": touched_areas(files),
        }


def load_existing(path=DECISIONS):
    """Read the ledger, skipping only the rows that fail to parse.

    Per line, not as one comprehension. A single truncated row used to raise
    and hand back an empty list, and since mine() rewrites the file from that
    result -- usually with no fresh records, because the cursor is already
    current -- one bad byte erased the whole decision history.

    Returns (rows, readable). `readable` distinguishes "the file is not there"
    from "the file is there and empty", which decides whether the cursor can
    still be trusted.
    """
    rows = []
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            for line in f:
                if not line.strip():
                    continue
                try:
                    row = json.loads(line)
                except Exception:
                    continue
                # `null` and `[]` parse but have no keys, and every consumer
                # asks these rows for one. Keeping such a row froze mining for
                # good: `r.get("sha")` raised, the hook swallowed it, and the
                # bad row stayed to raise again on the next run.
                if isinstance(row, dict):
                    rows.append(row)
        return rows, True
    except FileNotFoundError:
        return [], False
    except Exception:
        return rows, False


def write_records(records, path=DECISIONS):
    """Newest-last, one JSON object per line, replaced atomically."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    # Unique per process: the shared memory dir means two writers can
    # otherwise collide on one temp path.
    tmp = f"{path}.{os.getpid()}.tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        for r in records:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    os.replace(tmp, path)


def read_cursor(path=CURSOR):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read().strip() or None
    except Exception:
        return None


def write_cursor(sha, path=CURSOR):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = f"{path}.{os.getpid()}.tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(sha + "\n")
    os.replace(tmp, path)


def mine(ref="origin/main", limit=DEFAULT_LIMIT, full=False, cwd=None,
         decisions_path=DECISIONS, cursor_path=CURSOR):
    """Mine new commits into the decision log. Returns (added, total)."""
    head = git("rev-parse", ref, cwd=cwd)
    if not head:
        # A checkout without origin/main (fresh clone, detached CI) still has
        # local history worth mining; fall back rather than produce nothing.
        ref = "HEAD"
        head = git("rev-parse", ref, cwd=cwd)
        if not head:
            return 0, 0

    since = None if full else read_cursor(cursor_path)
    # A cursor left by a rewritten or unfetched history points at a commit that
    # is no longer an ancestor, and `since..head` would then silently resolve to
    # nothing. Exit status is the only signal here -- `--is-ancestor` prints
    # nothing either way -- so this cannot go through git().
    if since and not is_ancestor(since, head, cwd=cwd):
        since = None

    # The snapshot and its cursor are one transaction: a run that wrote records
    # but lost the cursor race would leave a newer cursor over an older
    # snapshot, and those commits would count as processed forever.
    with memory_lock("decisions", mem_dir=os.path.dirname(decisions_path)) as held:
        if not held:
            # Someone else is mining right now. Writing anyway would clobber
            # their snapshot; skipping costs nothing, because the cursor stays
            # put and the next run picks the same commits up.
            return 0, 0
        if full:
            existing, readable = [], True
        else:
            existing, readable = load_existing(decisions_path)
        # A cursor is only meaningful next to the ledger it was written for. If
        # the ledger is gone or unreadable, honouring the cursor would mine
        # nothing and then write that nothing back as the new history.
        if not readable or (not existing and since):
            since = None
        known = {r.get("sha") for r in existing}
        try:
            fresh = [
                r for r in commit_records(ref, limit, since, cwd=cwd)
                if r.get("sha") not in known
            ]
        except ScanFailed:
            # Leave the cursor where it is so the next run retries this range.
            return 0, len(existing)

        # git log is newest-first; store oldest-first so the file reads as a
        # timeline.
        merged = existing + list(reversed(fresh))
        if len(merged) > MAX_RECORDS:
            merged = merged[-MAX_RECORDS:]
        write_records(merged, decisions_path)
        write_cursor(head, cursor_path)
        return len(fresh), len(merged)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Mine decision rationale from git history")
    ap.add_argument("--ref", default="origin/main", help="ref to walk (default origin/main)")
    ap.add_argument("--limit", type=int, default=DEFAULT_LIMIT, help="max commits to inspect")
    ap.add_argument("--full", action="store_true", help="ignore the cursor and rebuild")
    ap.add_argument("--quiet", action="store_true", help="suppress the summary line")
    args = ap.parse_args(argv)

    added, total = mine(ref=args.ref, limit=args.limit, full=args.full)
    if not args.quiet:
        print(f"decision-mine: +{added} new, {total} total -> {DECISIONS}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SystemExit:
        raise
    except Exception:
        # Same contract as the memory hooks: never disrupt a session.
        sys.exit(0)
