#!/usr/bin/env python3
"""Decision miner: harvest change rationale out of git history into memory.

The session-memory hooks already capture a deterministic *skeleton* of each
coding session (branch, commits, files) and reserve ``card.md`` for the
semantic layer -- decisions, lessons, self-corrections. That semantic half has
never been written: it depends on an agent voluntarily updating a file, and the
observed hit rate across every session on record is zero.

The rationale is not actually missing, though. It is sitting in commit bodies:
of the last 400 first-parent commits, 128 (32%) carry six or more lines of
prose once the mechanical noise is stripped, median 12 and up to 247 --
squash-merge preserves the whole PR narrative ("this was a deliberate call, not
a cleanup that fell out of something else"). Nobody reads it because nothing
surfaces it.

So this miner takes the artifact that already exists instead of asking an agent
to produce a new one. It walks first-parent history, keeps the commits whose
body carries real prose, strips the mechanical noise squash-merge adds, and
files each as a decision record keyed by the paths it touched -- so a later
session editing those paths can be shown why they look the way they do.

Deterministic: pure local git, no network, no LLM. Incremental: a cursor marks
the newest commit already mined, so a run costs only the new commits.

Write path: ``~/.claude/deneb-session-memory/decisions.jsonl``, the same
operator-owned memory dir the session-memory hooks own. This is NOT an audit
script -- ``scripts/audit`` Python must not write ledgers.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys

MEM_DIR = os.path.expanduser("~/.claude/deneb-session-memory")
DECISIONS = os.path.join(MEM_DIR, "decisions.jsonl")
CURSOR = os.path.join(MEM_DIR, "decisions.cursor")

# Bodies shorter than this are a subject with a stray trailer, not reasoning.
# Calibrated on Deneb's own history: measured AFTER clean_body, six lines keeps
# 128 of the last 400 first-parent commits (32%, median 12). The threshold is
# applied to cleaned prose on purpose -- a squash body is padded with subject
# echoes and generated footers, so raw line count would pass commits that say
# nothing.
MIN_BODY_LINES = 6

# A first run should not walk 6k commits; later runs stop at the cursor anyway.
DEFAULT_LIMIT = 400
MAX_FILES = 12
MAX_BODY_CHARS = 2000
MAX_RECORDS = 2000

# Trailers and generated footers. These are mechanically appended, carry no
# rationale, and would otherwise dominate the short bodies.
_NOISE_PREFIXES = (
    "co-authored-by:",
    "claude-session:",
    "signed-off-by:",
    "generated with",
    "🤖 generated with",
    "_generated by",
    "reviewed by",
)

# Squash-merge repeats each squashed commit's subject as a "* subject" bullet
# before the prose. Keeping them would make the body look like a changelog.
_SQUASH_ECHO = re.compile(r"^\s*\*\s+\S")

# Bot review blocks (Cursor Bugbot's "> [!NOTE]" summary) ride into some PR
# bodies. They describe the diff back to us -- not the author's reasoning.
_BLOCKQUOTE = re.compile(r"^\s*>")

_CONVENTIONAL = re.compile(r"^(?P<type>[a-z]+)(?:\((?P<scope>[^)]*)\))?(?P<bang>!?):\s")
_PR_NUMBER = re.compile(r"\(#(\d+)\)\s*$")


def git(*args, cwd=None):
    """Run git, returning stdout stripped, or '' on any failure."""
    try:
        out = subprocess.run(
            ["git", *(["-C", cwd] if cwd else []), *args],
            capture_output=True,
            text=True,
            timeout=30,
        )
        return out.stdout.strip() if out.returncode == 0 else ""
    except Exception:
        return ""


def is_ancestor(older: str, newer: str, cwd=None) -> bool:
    """True when `older` is reachable from `newer`. Exit-status only."""
    try:
        return subprocess.run(
            ["git", *(["-C", cwd] if cwd else []), "merge-base", "--is-ancestor", older, newer],
            capture_output=True,
            text=True,
            timeout=30,
        ).returncode == 0
    except Exception:
        return False


def clean_body(raw: str) -> list[str]:
    """Strip squash echoes, trailers, and bot blocks; keep the prose.

    Returns the surviving lines with blank runs collapsed, so line counts mean
    "lines of reasoning" rather than "lines of whitespace and boilerplate".
    """
    kept: list[str] = []
    for line in (raw or "").splitlines():
        stripped = line.strip()
        low = stripped.lower()
        if not stripped:
            # Collapse blank runs; never lead with one.
            if kept and kept[-1] != "":
                kept.append("")
            continue
        if any(low.startswith(p) for p in _NOISE_PREFIXES):
            continue
        if _SQUASH_ECHO.match(line) or _BLOCKQUOTE.match(line):
            continue
        # A bare rule is only ever a separator before a generated footer.
        if set(stripped) <= {"-", "*", "_"} and len(stripped) >= 3:
            continue
        kept.append(stripped)
    while kept and kept[-1] == "":
        kept.pop()
    return kept


def parse_subject(subject: str):
    """Split a conventional-commit subject into type, scope, and PR number."""
    ctype = scope = None
    breaking = False
    m = _CONVENTIONAL.match(subject or "")
    if m:
        ctype = m.group("type")
        scope = m.group("scope") or None
        breaking = bool(m.group("bang"))
    pr = None
    p = _PR_NUMBER.search(subject or "")
    if p:
        pr = int(p.group(1))
    return ctype, scope, breaking, pr


def touched_areas(files: list[str]) -> list[str]:
    """Coarse areas a decision applies to, for cheap relevance matching later.

    Two levels: the module root (``gateway-go``) and the package directory
    (``gateway-go/internal/runtime/mcpapi``). Matching on the directory rather
    than the file is deliberate -- a decision about a package still explains a
    sibling file that did not happen to change in that commit.
    """
    areas: list[str] = []
    for f in files:
        parts = f.split("/")
        if len(parts) >= 1 and parts[0]:
            areas.append(parts[0])
        if len(parts) >= 2:
            areas.append(os.path.dirname(f))
    seen, out = set(), []
    for a in areas:
        if a and a not in seen:
            seen.add(a)
            out.append(a)
    return out


def commit_records(ref: str, limit: int, since: str | None, cwd=None):
    """Yield decision records for first-parent commits carrying rationale."""
    sep_f, sep_r = "\x01", "\x02"
    rng = f"{since}..{ref}" if since else ref
    raw = git(
        "log",
        "--first-parent",
        "-n",
        str(limit),
        f"--format=%H{sep_f}%h{sep_f}%aI{sep_f}%s{sep_f}%b{sep_r}",
        rng,
        cwd=cwd,
    )
    if not raw:
        return
    for chunk in raw.split(sep_r):
        chunk = chunk.strip("\n")
        if not chunk.strip():
            continue
        parts = chunk.split(sep_f)
        if len(parts) < 4:
            continue
        full, short, when, subject = parts[0].strip(), parts[1], parts[2], parts[3]
        body_raw = parts[4] if len(parts) > 4 else ""
        body = clean_body(body_raw)
        prose = [ln for ln in body if ln]
        if len(prose) < MIN_BODY_LINES:
            continue
        files = [ln for ln in git("show", "--name-only", "--format=", full, cwd=cwd).splitlines() if ln]
        ctype, scope, breaking, pr = parse_subject(subject)
        yield {
            "commit": short,
            "sha": full,
            "date": when[:10],
            "subject": subject,
            "type": ctype,
            "scope": scope,
            "breaking": breaking,
            "pr": pr,
            "rationale": "\n".join(body)[:MAX_BODY_CHARS],
            "rationale_lines": len(prose),
            "files": files[:MAX_FILES],
            "files_total": len(files),
            "areas": touched_areas(files),
        }


def load_existing(path=DECISIONS):
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            return [json.loads(ln) for ln in f if ln.strip()]
    except Exception:
        return []


def write_records(records, path=DECISIONS):
    """Newest-last, one JSON object per line, replaced atomically."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        for r in records:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    os.replace(tmp, path)


def read_cursor(path=CURSOR):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read().strip() or None
    except Exception:
        return None


def write_cursor(sha, path=CURSOR):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(sha + "\n")
    os.replace(tmp, path)


def mine(ref="origin/main", limit=DEFAULT_LIMIT, full=False, cwd=None,
         decisions_path=DECISIONS, cursor_path=CURSOR):
    """Mine new commits into the decision log. Returns (added, total)."""
    head = git("rev-parse", ref, cwd=cwd)
    if not head:
        # A checkout without origin/main (fresh clone, detached CI) still has
        # local history worth mining; fall back rather than produce nothing.
        ref = "HEAD"
        head = git("rev-parse", ref, cwd=cwd)
        if not head:
            return 0, 0

    since = None if full else read_cursor(cursor_path)
    # A cursor left by a rewritten or unfetched history points at a commit that
    # is no longer an ancestor, and `since..head` would then silently resolve to
    # nothing. Exit status is the only signal here -- `--is-ancestor` prints
    # nothing either way -- so this cannot go through git().
    if since and not is_ancestor(since, head, cwd=cwd):
        since = None

    existing = [] if full else load_existing(decisions_path)
    known = {r.get("sha") for r in existing}
    fresh = [r for r in commit_records(ref, limit, since, cwd=cwd) if r.get("sha") not in known]

    # git log is newest-first; store oldest-first so the file reads as a timeline.
    merged = existing + list(reversed(fresh))
    if len(merged) > MAX_RECORDS:
        merged = merged[-MAX_RECORDS:]
    write_records(merged, decisions_path)
    write_cursor(head, cursor_path)
    return len(fresh), len(merged)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Mine decision rationale from git history")
    ap.add_argument("--ref", default="origin/main", help="ref to walk (default origin/main)")
    ap.add_argument("--limit", type=int, default=DEFAULT_LIMIT, help="max commits to inspect")
    ap.add_argument("--full", action="store_true", help="ignore the cursor and rebuild")
    ap.add_argument("--quiet", action="store_true", help="suppress the summary line")
    args = ap.parse_args(argv)

    added, total = mine(ref=args.ref, limit=args.limit, full=args.full)
    if not args.quiet:
        print(f"decision-mine: +{added} new, {total} total -> {DECISIONS}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SystemExit:
        raise
    except Exception:
        # Same contract as the memory hooks: never disrupt a session.
        sys.exit(0)
