#!/usr/bin/env python3
"""tool-schema-gen: generate *ToolSchema() Go functions from tool_schemas.yaml.

Usage (from gateway-go/):
    python3 cmd/tool-schema-gen/gen.py \
        -yaml internal/chat/tool_schemas.yaml \
        -out  internal/chat/tool_schemas_gen.go

Or via Makefile:
    make tool-schemas
"""

import argparse
import subprocess
import sys
import yaml


# ---------------------------------------------------------------------------
# String helpers
# ---------------------------------------------------------------------------

def camel_case(name: str) -> str:
    """snake_case → camelCase: 'sessions_list' → 'sessionsList'."""
    parts = name.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def go_str(s: str) -> str:
    """Produce a Go double-quoted string literal."""
    s = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")
    return f'"{s}"'


# ---------------------------------------------------------------------------
# Value emitters
# ---------------------------------------------------------------------------

def emit_scalar(val) -> str:
    """Emit a Go literal for a plain scalar value."""
    if isinstance(val, bool):
        return "true" if val else "false"
    if isinstance(val, int):
        return str(val)
    if isinstance(val, float):
        return str(int(val)) if val == int(val) else str(val)
    return go_str(str(val))


def emit_string_slice(items: list) -> str:
    """Emit []string{"a", "b"}."""
    inner = ", ".join(go_str(s) for s in items)
    return f"[]string{{{inner}}}"


def emit_prop_def(prop: dict, depth: int) -> str:
    """Emit map[string]any{...} for a single property definition."""
    indent = "\t" * depth
    lines = ["map[string]any{"]
    for key, val in prop.items():
        field_val = emit_field_value(key, val, depth + 1)
        lines.append(f"{indent}\t{go_str(key)}: {field_val},")
    lines.append(f"{indent}}}")
    return "\n".join(lines)


def emit_props_map(props: dict, depth: int) -> str:
    """Emit map[string]any{ "propName": map[string]any{...}, ... }."""
    indent = "\t" * depth
    lines = ["map[string]any{"]
    for prop_name, prop_def in props.items():
        prop_str = emit_prop_def(prop_def, depth + 1)
        lines.append(f"{indent}\t{go_str(prop_name)}: {prop_str},")
    lines.append(f"{indent}}}")
    return "\n".join(lines)


def emit_field_value(key: str, val, depth: int) -> str:
    """Dispatch on key to produce the correct Go value."""
    if key in ("type", "description"):
        return go_str(str(val))
    if key in ("default", "minimum", "maximum", "minItems", "maxItems"):
        return emit_scalar(val)
    if key == "enum":
        return emit_string_slice(val)
    if key == "required":
        return emit_string_slice(val)
    if key == "properties":
        return emit_props_map(val, depth)
    if key == "items":
        # items is always a property-def style dict
        return emit_prop_def(val, depth)
    # Unknown keys: safe string fallback
    return go_str(str(val))


# ---------------------------------------------------------------------------
# Top-level generator
# ---------------------------------------------------------------------------

def generate(tools: list) -> str:
    lines = [
        "// Code generated by tool-schema-gen. DO NOT EDIT.",
        "// Source: gateway-go/internal/chat/tool_schemas.yaml",
        "// Regenerate: make tool-schemas",
        "",
        "package chat",
        "",
    ]

    for tool in tools:
        name = tool["name"]
        fn = camel_case(name) + "ToolSchema"

        lines.append(f"func {fn}() map[string]any {{")
        lines.append("\treturn map[string]any{")
        lines.append('\t\t"type": "object",')

        if props := tool.get("properties"):
            props_str = emit_props_map(props, 2)
            lines.append(f'\t\t"properties": {props_str},')

        if req := tool.get("required"):
            lines.append(f'\t\t"required": {emit_string_slice(req)},')

        lines.append("\t}")
        lines.append("}")
        lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    p = argparse.ArgumentParser(description="Generate *ToolSchema() functions from YAML")
    p.add_argument("-yaml", required=True, dest="yaml_file", metavar="FILE")
    p.add_argument("-out", required=True, dest="out_file", metavar="FILE")
    args = p.parse_args()

    with open(args.yaml_file, encoding="utf-8") as f:
        tools = yaml.safe_load(f)

    if not isinstance(tools, list):
        print("error: YAML root must be a sequence of tool definitions", file=sys.stderr)
        sys.exit(1)

    src = generate(tools)

    # Run gofmt for canonical formatting.
    result = subprocess.run(["gofmt"], input=src, capture_output=True, text=True)
    if result.returncode == 0:
        src = result.stdout
    else:
        print(f"gofmt warning: {result.stderr}", file=sys.stderr)

    with open(args.out_file, "w", encoding="utf-8") as f:
        f.write(src)

    print(f"wrote {args.out_file} ({len(tools)} tools)")


if __name__ == "__main__":
    main()
