// tool-schema-gen generates *ToolSchema() Go functions from tool_schemas.yaml.
//
// Usage (from gateway-go/):
//
//	go run cmd/tool-schema-gen/main.go \
//	    -yaml internal/chat/toolreg/tool_schemas.yaml \
//	    -out  internal/chat/toolreg/tool_schemas_gen.go \
//	    -pkg  toolreg
//
// Or via Makefile: make tool-schemas
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	yamlFile := flag.String("yaml", "", "YAML source file")
	outFile := flag.String("out", "", "Output Go file")
	pkg := flag.String("pkg", "toolreg", "Go package name")
	flag.Parse()

	if *yamlFile == "" || *outFile == "" {
		fmt.Fprintln(os.Stderr, "usage: tool-schema-gen -yaml FILE -out FILE [-pkg PKG]")
		os.Exit(1)
	}

	data, err := os.ReadFile(*yamlFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	var root yaml.Node
	if err := yaml.Unmarshal(data, &root); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	if root.Kind != yaml.DocumentNode || len(root.Content) == 0 ||
		root.Content[0].Kind != yaml.SequenceNode {
		fmt.Fprintln(os.Stderr, "error: YAML root must be a sequence of tool definitions")
		os.Exit(1)
	}

	seq := root.Content[0]

	sourcePath := *yamlFile
	if !strings.HasPrefix(sourcePath, "gateway-go/") {
		sourcePath = "gateway-go/" + sourcePath
	}

	src := generate(seq, *pkg, sourcePath)

	formatted, err := format.Source([]byte(src))
	if err != nil {
		fmt.Fprintf(os.Stderr, "gofmt warning: %v\n", err)
		formatted = []byte(src)
	}

	if err := os.WriteFile(*outFile, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("wrote %s (%d tools)\n", *outFile, len(seq.Content))
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

func generate(seq *yaml.Node, pkg, source string) string {
	var b strings.Builder

	fmt.Fprintf(&b, "// Code generated by tool-schema-gen. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: %s\n", source)
	fmt.Fprintf(&b, "// Regenerate: make tool-schemas\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	type maxOutputEntry struct {
		name string
		val  int
	}
	var maxOutputs []maxOutputEntry

	for _, toolNode := range seq.Content {
		if toolNode.Kind != yaml.MappingNode {
			continue
		}

		name := scalarField(toolNode, "name")
		fn := camelCase(name) + "ToolSchema"

		fmt.Fprintf(&b, "func %s() map[string]any {\n", fn)
		fmt.Fprintf(&b, "\treturn map[string]any{\n")
		fmt.Fprintf(&b, "\t\t\"type\": \"object\",\n")

		if props := nodeGet(toolNode, "properties"); props != nil && len(props.Content) > 0 {
			fmt.Fprintf(&b, "\t\t\"properties\": %s,\n", emitPropsMap(props, 2))
		}

		if req := nodeGet(toolNode, "required"); req != nil && len(req.Content) > 0 {
			fmt.Fprintf(&b, "\t\t\"required\": %s,\n", emitStringSlice(req))
		}

		fmt.Fprintf(&b, "\t}\n}\n\n")

		if mo := nodeGet(toolNode, "max_output"); mo != nil {
			val := 0
			fmt.Sscanf(mo.Value, "%d", &val)
			maxOutputs = append(maxOutputs, maxOutputEntry{name, val})
		}
	}

	if len(maxOutputs) > 0 {
		sort.Slice(maxOutputs, func(i, j int) bool {
			return maxOutputs[i].name < maxOutputs[j].name
		})

		fmt.Fprintf(&b, "// ToolMaxOutputs returns per-tool output character budgets from tool_schemas.yaml.\n")
		fmt.Fprintf(&b, "// Tools not in this map use agent.DefaultMaxOutput.\n")
		fmt.Fprintf(&b, "func ToolMaxOutputs() map[string]int {\n")
		fmt.Fprintf(&b, "\treturn map[string]int{\n")
		for _, entry := range maxOutputs {
			fmt.Fprintf(&b, "\t\t%s: %d,\n", goStr(entry.name), entry.val)
		}
		fmt.Fprintf(&b, "\t}\n}\n\n")
	}

	return b.String()
}

// ---------------------------------------------------------------------------
// Emitters
// ---------------------------------------------------------------------------

func emitPropsMap(node *yaml.Node, depth int) string {
	indent := strings.Repeat("\t", depth)
	var b strings.Builder
	b.WriteString("map[string]any{\n")
	for i := 0; i < len(node.Content); i += 2 {
		propName := node.Content[i].Value
		propDef := node.Content[i+1]
		fmt.Fprintf(&b, "%s\t%s: %s,\n", indent, goStr(propName), emitPropDef(propDef, depth+1))
	}
	fmt.Fprintf(&b, "%s}", indent)
	return b.String()
}

func emitPropDef(node *yaml.Node, depth int) string {
	indent := strings.Repeat("\t", depth)
	var b strings.Builder
	b.WriteString("map[string]any{\n")
	for i := 0; i < len(node.Content); i += 2 {
		key := node.Content[i].Value
		val := node.Content[i+1]
		fmt.Fprintf(&b, "%s\t%s: %s,\n", indent, goStr(key), emitFieldValue(key, val, depth+1))
	}
	fmt.Fprintf(&b, "%s}", indent)
	return b.String()
}

func emitFieldValue(key string, val *yaml.Node, depth int) string {
	switch key {
	case "type", "description":
		return goStr(val.Value)
	case "default", "minimum", "maximum", "minItems", "maxItems":
		return emitScalar(val)
	case "enum", "required":
		return emitStringSlice(val)
	case "properties":
		return emitPropsMap(val, depth)
	case "items":
		return emitPropDef(val, depth)
	case "additionalProperties":
		if val.Kind == yaml.ScalarNode {
			if val.Value == "true" || val.Value == "false" {
				return val.Value
			}
		}
		return emitPropDef(val, depth)
	default:
		return goStr(val.Value)
	}
}

func emitScalar(node *yaml.Node) string {
	switch node.Tag {
	case "!!bool":
		if node.Value == "true" {
			return "true"
		}
		return "false"
	case "!!int":
		return node.Value
	case "!!float":
		// Whole-number floats → emit as int.
		f := 0.0
		if _, err := fmt.Sscanf(node.Value, "%f", &f); err == nil && f == float64(int64(f)) {
			return fmt.Sprintf("%d", int64(f))
		}
		return node.Value
	default:
		return goStr(node.Value)
	}
}

func emitStringSlice(node *yaml.Node) string {
	items := make([]string, len(node.Content))
	for i, item := range node.Content {
		items[i] = goStr(item.Value)
	}
	return "[]string{" + strings.Join(items, ", ") + "}"
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func nodeGet(mapping *yaml.Node, key string) *yaml.Node {
	for i := 0; i < len(mapping.Content); i += 2 {
		if mapping.Content[i].Value == key {
			return mapping.Content[i+1]
		}
	}
	return nil
}

func scalarField(mapping *yaml.Node, key string) string {
	if n := nodeGet(mapping, key); n != nil {
		return n.Value
	}
	return ""
}

func camelCase(name string) string {
	parts := strings.Split(name, "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func goStr(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	s = strings.ReplaceAll(s, "\t", `\t`)
	return `"` + s + `"`
}
