// tool-schema-gen generates *ToolSchema() Go functions from tool_schemas.json.
//
// Usage (from gateway-go/):
//
//	go run cmd/tool-schema-gen/main.go \
//	    -json internal/pipeline/chat/toolreg/tool_schemas.json \
//	    -out  internal/pipeline/chat/toolreg/tool_schemas_gen.go \
//	    -pkg  toolreg
//
// Or via Makefile: make tool-schemas
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

func main() {
	jsonFile := flag.String("json", "", "JSON source file")
	outFile := flag.String("out", "", "Output Go file")
	pkg := flag.String("pkg", "toolreg", "Go package name")
	flag.Parse()

	if *jsonFile == "" || *outFile == "" {
		fmt.Fprintln(os.Stderr, "usage: tool-schema-gen -json FILE -out FILE [-pkg PKG]")
		os.Exit(1)
	}

	data, err := os.ReadFile(*jsonFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	var tools []map[string]any
	if err := json.Unmarshal(data, &tools); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	sourcePath := *jsonFile
	if !strings.HasPrefix(sourcePath, "gateway-go/") {
		sourcePath = "gateway-go/" + sourcePath
	}

	src := generate(tools, *pkg, sourcePath)

	formatted, err := format.Source([]byte(src))
	if err != nil {
		fmt.Fprintf(os.Stderr, "gofmt warning: %v\n", err)
		formatted = []byte(src)
	}

	if err := os.WriteFile(*outFile, formatted, 0o600); err != nil { //nolint:gosec // G306 — generated source file, needs read access
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("wrote %s (%d tools)\n", *outFile, len(tools))
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

func generate(tools []map[string]any, pkg, source string) string {
	var b strings.Builder

	fmt.Fprintf(&b, "// Code generated by tool-schema-gen. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: %s\n", source)
	fmt.Fprintf(&b, "// Regenerate: make tool-schemas\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	type maxOutputEntry struct {
		name string
		val  int
	}
	var maxOutputs []maxOutputEntry

	for _, tool := range tools {
		name, _ := tool["name"].(string)
		fn := camelCase(name) + "ToolSchema"

		fmt.Fprintf(&b, "func %s() map[string]any {\n", fn)
		fmt.Fprintf(&b, "\treturn map[string]any{\n")
		fmt.Fprintf(&b, "\t\t\"type\": \"object\",\n")

		if props, ok := tool["properties"].(map[string]any); ok && len(props) > 0 {
			fmt.Fprintf(&b, "\t\t\"properties\": %s,\n", emitPropsMap(props, 2))
		}

		if req, ok := tool["required"].([]any); ok && len(req) > 0 {
			fmt.Fprintf(&b, "\t\t\"required\": %s,\n", emitStringSlice(req))
		}

		fmt.Fprintf(&b, "\t}\n}\n\n")

		if mo, ok := tool["max_output"].(float64); ok {
			maxOutputs = append(maxOutputs, maxOutputEntry{name, int(mo)})
		}
	}

	if len(maxOutputs) > 0 {
		sort.Slice(maxOutputs, func(i, j int) bool {
			return maxOutputs[i].name < maxOutputs[j].name
		})

		fmt.Fprintf(&b, "// ToolMaxOutputs returns per-tool output character budgets from tool_schemas.json.\n")
		fmt.Fprintf(&b, "// Tools not in this map use agent.DefaultMaxOutput.\n")
		fmt.Fprintf(&b, "func ToolMaxOutputs() map[string]int {\n")
		fmt.Fprintf(&b, "\treturn map[string]int{\n")
		for _, entry := range maxOutputs {
			fmt.Fprintf(&b, "\t\t%s: %d,\n", goStr(entry.name), entry.val)
		}
		fmt.Fprintf(&b, "\t}\n}\n\n")
	}

	return b.String()
}

// ---------------------------------------------------------------------------
// Emitters
// ---------------------------------------------------------------------------

func emitPropsMap(props map[string]any, depth int) string {
	indent := strings.Repeat("\t", depth)
	var b strings.Builder
	b.WriteString("map[string]any{\n")

	for _, key := range sortedKeys(props) {
		def, ok := props[key].(map[string]any)
		if !ok {
			continue
		}
		fmt.Fprintf(&b, "%s\t%s: %s,\n", indent, goStr(key), emitPropDef(def, depth+1))
	}

	fmt.Fprintf(&b, "%s}", indent)
	return b.String()
}

func emitPropDef(def map[string]any, depth int) string {
	indent := strings.Repeat("\t", depth)
	var b strings.Builder
	b.WriteString("map[string]any{\n")

	for _, key := range orderedFieldKeys(def) {
		fmt.Fprintf(&b, "%s\t%s: %s,\n", indent, goStr(key), emitFieldValue(key, def[key], depth+1))
	}

	fmt.Fprintf(&b, "%s}", indent)
	return b.String()
}

func emitFieldValue(key string, val any, depth int) string {
	switch key {
	case "type", "description":
		s, _ := val.(string)
		return goStr(s)
	case "default", "minimum", "maximum", "minItems", "maxItems":
		return emitValue(val)
	case "enum", "required":
		items, _ := val.([]any)
		return emitStringSlice(items)
	case "properties":
		m, _ := val.(map[string]any)
		return emitPropsMap(m, depth)
	case "items":
		m, _ := val.(map[string]any)
		return emitPropDef(m, depth)
	case "additionalProperties":
		switch v := val.(type) {
		case bool:
			if v {
				return "true"
			}
			return "false"
		case map[string]any:
			return emitPropDef(v, depth)
		}
		return goStr(fmt.Sprintf("%v", val))
	default:
		s, ok := val.(string)
		if ok {
			return goStr(s)
		}
		return emitValue(val)
	}
}

func emitValue(val any) string {
	switch v := val.(type) {
	case bool:
		if v {
			return "true"
		}
		return "false"
	case float64:
		// Whole-number floats → emit as int.
		if v == float64(int64(v)) {
			return fmt.Sprintf("%d", int64(v))
		}
		return fmt.Sprintf("%v", v)
	case string:
		return goStr(v)
	default:
		return fmt.Sprintf("%v", val)
	}
}

func emitStringSlice(items []any) string {
	strs := make([]string, len(items))
	for i, item := range items {
		s, _ := item.(string)
		strs[i] = goStr(s)
	}
	return "[]string{" + strings.Join(strs, ", ") + "}"
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// fieldRank defines the preferred emission order for property definition fields.
// Keys not in this map sort alphabetically after the ranked keys.
var fieldRank = map[string]int{
	"type":                 0,
	"description":          1,
	"default":              2,
	"minimum":              3,
	"maximum":              4,
	"minItems":             5,
	"maxItems":             6,
	"enum":                 7,
	"required":             8,
	"properties":           9,
	"items":                10,
	"additionalProperties": 11,
}

// orderedFieldKeys returns map keys sorted by fieldRank, then alphabetically.
func orderedFieldKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		ri, oki := fieldRank[keys[i]]
		rj, okj := fieldRank[keys[j]]
		if oki && okj {
			return ri < rj
		}
		if oki {
			return true
		}
		if okj {
			return false
		}
		return keys[i] < keys[j]
	})
	return keys
}

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func camelCase(name string) string {
	parts := strings.Split(name, "_")
	for i := 1; i < len(parts); i++ {
		if parts[i] != "" {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func goStr(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	s = strings.ReplaceAll(s, "\t", `\t`)
	return `"` + s + `"`
}
