// Code generated by data-gen. DO NOT EDIT.
// Source: gateway-go/internal/chat/tool_classification.yaml
// Regenerate: make data-gen

package chat

// mutatingTools are tools that change the filesystem or run commands.
// When a run uses these, it likely needs a verification follow-up.
var mutatingTools = map[string]bool{
	"edit":          true,
	"write":         true,
	"exec":          true,
	"git":           true,
	"multi_edit":    true,
	"notebook_edit": true,
}

// toolApprovalPolicy classifies tools by their autonomous execution safety.
// "auto": safe for autonomous execution without user confirmation.
// "confirm": requires user confirmation before execution (mutating/external).
// "block": never executed by autonomous agents (dangerous system operations).
// Used by the agent executor to gate tool calls in autonomous contexts
// (cron jobs, subagents, deep work mode).
var toolApprovalPolicy = map[string]string{
	"read":            "auto",
	"grep":            "auto",
	"find":            "auto",
	"tree":            "auto",
	"diff":            "auto",
	"analyze":         "auto",
	"batch_read":      "auto",
	"search_and_read": "auto",
	"inspect":         "auto",
	"read_spillover":  "auto",
	"health_check":    "auto",
	"sessions_list":   "auto",
	"skills_list":     "auto",
	"agent_logs":      "auto",
	"gateway_logs":    "auto",
	"web_search":      "auto",
	"web_fetch":       "auto",
	"image_describe":  "auto",
	"memory":          "auto",
	"wiki":            "auto",
	"kv":              "auto",
	"process":         "auto",
	"edit":            "confirm",
	"write":           "confirm",
	"multi_edit":      "confirm",
	"notebook_edit":   "confirm",
	"exec":            "confirm",
	"git":             "confirm",
	"send_file":       "confirm",
	"bridge":          "block",
}

// channelSilentTools lists tools that suppress chat delivery on specific
// channels. When the agent calls one of these tools, the response is not
// delivered as a chat message — the tool executes normally but the chat
// output is silenced. Management tools (cron, etc.) execute in the
// background; results are accessible via MCP/API.
var channelSilentTools = map[string][]string{
	"telegram": []string{"cron", "gmail", "morning_letter", "gateway", "health_check", "message", "process", "sessions_list", "sessions_history", "sessions_search", "sessions_send", "sessions_spawn", "subagents", "agent_logs", "gateway_logs", "kv", "bridge", "autoresearch", "skills_list", "skill_manage"},
}

// toolCompressSkipSet contains tools whose output should not be compressed.
// Structured-output tools are already handled by post-processors.
// Internal / already-small tools add no compression value.
var toolCompressSkipSet = map[string]bool{
	"grep":          true,
	"find":          true,
	"tree":          true,
	"git":           true,
	"analyze":       true,
	"diff":          true,
	"memory":        true,
	"wiki":          true,
	"kv":            true,
	"sessions_list": true,
}
