// Code generated by data-gen. DO NOT EDIT.
// Source: gateway-go/internal/chat/tool_classification.yaml
// Regenerate: make data-gen

package chat

// mutatingTools are tools that change the filesystem or run commands.
// When a run uses these, it likely needs a verification follow-up.
var mutatingTools = map[string]bool{
	"edit":          true,
	"write":         true,
	"exec":          true,
	"git":           true,
	"multi_edit":    true,
	"notebook_edit": true,
}

// toolCompressSkipSet contains tools whose output should not be compressed.
// Structured-output tools are already handled by post-processors.
// Internal / already-small tools add no compression value.
var toolCompressSkipSet = map[string]bool{
	"grep":          true,
	"find":          true,
	"tree":          true,
	"git":           true,
	"analyze":       true,
	"diff":          true,
	"memory":        true,
	"kv":            true,
	"sessions_list": true,
}
